/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AbilityOpenIcon } from '../generated/components/ability-open.tsx';
export { abilityOpenIconDefinition } from '../generated/definitions/ability-open.ts';
