/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AbstractIcon } from '../generated/components/abstract.tsx';
export { abstractIconDefinition } from '../generated/definitions/abstract.ts';
