/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AdjustmentFilledIcon } from '../generated/components/adjustment-filled.tsx';
export { adjustmentFilledIconDefinition } from '../generated/definitions/adjustment-filled.ts';
