/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiBookOpenFilledIcon } from '../generated/components/ai-book-open-filled.tsx';
export { aiBookOpenFilledIconDefinition } from '../generated/definitions/ai-book-open-filled.ts';
