/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiBookOpenIcon } from '../generated/components/ai-book-open.tsx';
export { aiBookOpenIconDefinition } from '../generated/definitions/ai-book-open.ts';
