/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiCutIcon } from '../generated/components/ai-cut.tsx';
export { aiCutIconDefinition } from '../generated/definitions/ai-cut.ts';
