/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiChartBarIcon } from '../generated/components/ai-chart-bar.tsx';
export { aiChartBarIconDefinition } from '../generated/definitions/ai-chart-bar.ts';
