/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiCoordinateSystemIcon } from '../generated/components/ai-coordinate-system.tsx';
export { aiCoordinateSystemIconDefinition } from '../generated/definitions/ai-coordinate-system.ts';
