/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiEducationFilledIcon } from '../generated/components/ai-education-filled.tsx';
export { aiEducationFilledIconDefinition } from '../generated/definitions/ai-education-filled.ts';
