/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiEdit1Icon } from '../generated/components/ai-edit-1.tsx';
export { aiEdit1IconDefinition } from '../generated/definitions/ai-edit-1.ts';
