/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiGitBranchFilledIcon } from '../generated/components/ai-git-branch-filled.tsx';
export { aiGitBranchFilledIconDefinition } from '../generated/definitions/ai-git-branch-filled.ts';
