/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiImageFilledIcon } from '../generated/components/ai-image-filled.tsx';
export { aiImageFilledIconDefinition } from '../generated/definitions/ai-image-filled.ts';
