/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiTerminal1Icon } from '../generated/components/ai-terminal-1.tsx';
export { aiTerminal1IconDefinition } from '../generated/definitions/ai-terminal-1.ts';
