/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiVideoFilledIcon } from '../generated/components/ai-video-filled.tsx';
export { aiVideoFilledIconDefinition } from '../generated/definitions/ai-video-filled.ts';
