/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AirplayWaveFilledIcon } from '../generated/components/airplay-wave-filled.tsx';
export { airplayWaveFilledIconDefinition } from '../generated/definitions/airplay-wave-filled.ts';
