/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AirplayWaveIcon } from '../generated/components/airplay-wave.tsx';
export { airplayWaveIconDefinition } from '../generated/definitions/airplay-wave.ts';
