/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AlarmFilledIcon } from '../generated/components/alarm-filled.tsx';
export { alarmFilledIconDefinition } from '../generated/definitions/alarm-filled.ts';
