/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AlignTopIcon } from '../generated/components/align-top.tsx';
export { alignTopIconDefinition } from '../generated/definitions/align-top.ts';
