/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ApplicationFilledIcon } from '../generated/components/application-filled.tsx';
export { applicationFilledIconDefinition } from '../generated/definitions/application-filled.ts';
