/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ApplicationIcon } from '../generated/components/application.tsx';
export { applicationIconDefinition } from '../generated/definitions/application.ts';
