/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArchitectureHuiStyleFilledIcon } from '../generated/components/architecture-hui-style-filled.tsx';
export { architectureHuiStyleFilledIconDefinition } from '../generated/definitions/architecture-hui-style-filled.ts';
