/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArchwayIcon } from '../generated/components/archway.tsx';
export { archwayIconDefinition } from '../generated/definitions/archway.ts';
