/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpDownCircleIcon } from '../generated/components/arrow-up-down-circle.tsx';
export { arrowUpDownCircleIconDefinition } from '../generated/definitions/arrow-up-down-circle.ts';
