/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftDownIcon } from '../generated/components/arrow-left-down.tsx';
export { arrowLeftDownIconDefinition } from '../generated/definitions/arrow-left-down.ts';
