/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftIcon } from '../generated/components/arrow-left.tsx';
export { arrowLeftIconDefinition } from '../generated/definitions/arrow-left.ts';
