/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowDownRectangleFilledIcon } from '../generated/components/arrow-down-rectangle-filled.tsx';
export { arrowDownRectangleFilledIconDefinition } from '../generated/definitions/arrow-down-rectangle-filled.ts';
