/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpDown1Icon } from '../generated/components/arrow-up-down-1.tsx';
export { arrowUpDown1IconDefinition } from '../generated/definitions/arrow-up-down-1.ts';
