/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftUpCircleFilledIcon } from '../generated/components/arrow-left-up-circle-filled.tsx';
export { arrowLeftUpCircleFilledIconDefinition } from '../generated/definitions/arrow-left-up-circle-filled.ts';
