/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpIcon } from '../generated/components/arrow-up.tsx';
export { arrowUpIconDefinition } from '../generated/definitions/arrow-up.ts';
