/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowDownIcon } from '../generated/components/arrow-down.tsx';
export { arrowDownIconDefinition } from '../generated/definitions/arrow-down.ts';
