/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpCircleFilledIcon } from '../generated/components/arrow-up-circle-filled.tsx';
export { arrowUpCircleFilledIconDefinition } from '../generated/definitions/arrow-up-circle-filled.ts';
