/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowDownCircleFilledIcon } from '../generated/components/arrow-down-circle-filled.tsx';
export { arrowDownCircleFilledIconDefinition } from '../generated/definitions/arrow-down-circle-filled.ts';
