/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowTriangleDownFilledIcon } from '../generated/components/arrow-triangle-down-filled.tsx';
export { arrowTriangleDownFilledIconDefinition } from '../generated/definitions/arrow-triangle-down-filled.ts';
