/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentCheckedIcon } from '../generated/components/assignment-checked.tsx';
export { assignmentCheckedIconDefinition } from '../generated/definitions/assignment-checked.ts';
