/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentErrorFilledIcon } from '../generated/components/assignment-error-filled.tsx';
export { assignmentErrorFilledIconDefinition } from '../generated/definitions/assignment-error-filled.ts';
