/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AttachIcon } from '../generated/components/attach.tsx';
export { attachIconDefinition } from '../generated/definitions/attach.ts';
