/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Attic1Icon } from '../generated/components/attic-1.tsx';
export { attic1IconDefinition } from '../generated/definitions/attic-1.ts';
