/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AtticFilledIcon } from '../generated/components/attic-filled.tsx';
export { atticFilledIconDefinition } from '../generated/definitions/attic-filled.ts';
