/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AudioFilledIcon } from '../generated/components/audio-filled.tsx';
export { audioFilledIconDefinition } from '../generated/definitions/audio-filled.ts';
