/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AutomationIcon } from '../generated/components/automation.tsx';
export { automationIconDefinition } from '../generated/definitions/automation.ts';
