/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BacktopRectangleFilledIcon } from '../generated/components/backtop-rectangle-filled.tsx';
export { backtopRectangleFilledIconDefinition } from '../generated/definitions/backtop-rectangle-filled.ts';
