/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BackupFilledIcon } from '../generated/components/backup-filled.tsx';
export { backupFilledIconDefinition } from '../generated/definitions/backup-filled.ts';
