/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BananaIcon } from '../generated/components/banana.tsx';
export { bananaIconDefinition } from '../generated/definitions/banana.ts';
