/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BarbecueFilledIcon } from '../generated/components/barbecue-filled.tsx';
export { barbecueFilledIconDefinition } from '../generated/definitions/barbecue-filled.ts';
