/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BillIcon } from '../generated/components/bill.tsx';
export { billIconDefinition } from '../generated/definitions/bill.ts';
