/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BoneIcon } from '../generated/components/bone.tsx';
export { boneIconDefinition } from '../generated/definitions/bone.ts';
