/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkCheckedIcon } from '../generated/components/bookmark-checked.tsx';
export { bookmarkCheckedIconDefinition } from '../generated/definitions/bookmark-checked.ts';
