/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkDoubleFilledIcon } from '../generated/components/bookmark-double-filled.tsx';
export { bookmarkDoubleFilledIconDefinition } from '../generated/definitions/bookmark-double-filled.ts';
