/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookOpenIcon } from '../generated/components/book-open.tsx';
export { bookOpenIconDefinition } from '../generated/definitions/book-open.ts';
