/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkDoubleIcon } from '../generated/components/bookmark-double.tsx';
export { bookmarkDoubleIconDefinition } from '../generated/definitions/bookmark-double.ts';
