/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge1Icon } from '../generated/components/bridge-1.tsx';
export { bridge1IconDefinition } from '../generated/definitions/bridge-1.ts';
