/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge5Icon } from '../generated/components/bridge-5.tsx';
export { bridge5IconDefinition } from '../generated/definitions/bridge-5.ts';
