/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge2FilledIcon } from '../generated/components/bridge-2-filled.tsx';
export { bridge2FilledIconDefinition } from '../generated/definitions/bridge-2-filled.ts';
