/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge6FilledIcon } from '../generated/components/bridge-6-filled.tsx';
export { bridge6FilledIconDefinition } from '../generated/definitions/bridge-6-filled.ts';
