/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge1FilledIcon } from '../generated/components/bridge-1-filled.tsx';
export { bridge1FilledIconDefinition } from '../generated/definitions/bridge-1-filled.ts';
