/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Brightness1FilledIcon } from '../generated/components/brightness-1-filled.tsx';
export { brightness1FilledIconDefinition } from '../generated/definitions/brightness-1-filled.ts';
