/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrightnessFilledIcon } from '../generated/components/brightness-filled.tsx';
export { brightnessFilledIconDefinition } from '../generated/definitions/brightness-filled.ts';
