/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BroccoliIcon } from '../generated/components/broccoli.tsx';
export { broccoliIconDefinition } from '../generated/definitions/broccoli.ts';
