/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseFilledIcon } from '../generated/components/browse-filled.tsx';
export { browseFilledIconDefinition } from '../generated/definitions/browse-filled.ts';
