/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrushFilledIcon } from '../generated/components/brush-filled.tsx';
export { brushFilledIconDefinition } from '../generated/definitions/brush-filled.ts';
