/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BugFilledIcon } from '../generated/components/bug-filled.tsx';
export { bugFilledIconDefinition } from '../generated/definitions/bug-filled.ts';
