/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BugReportIcon } from '../generated/components/bug-report.tsx';
export { bugReportIconDefinition } from '../generated/definitions/bug-report.ts';
