/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building1Icon } from '../generated/components/building-1.tsx';
export { building1IconDefinition } from '../generated/definitions/building-1.ts';
