/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building2Icon } from '../generated/components/building-2.tsx';
export { building2IconDefinition } from '../generated/definitions/building-2.ts';
