/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building5Icon } from '../generated/components/building-5.tsx';
export { building5IconDefinition } from '../generated/definitions/building-5.ts';
