/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building4FilledIcon } from '../generated/components/building-4-filled.tsx';
export { building4FilledIconDefinition } from '../generated/definitions/building-4-filled.ts';
