/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallCancelFilledIcon } from '../generated/components/call-cancel-filled.tsx';
export { callCancelFilledIconDefinition } from '../generated/definitions/call-cancel-filled.ts';
