/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallIncomingIcon } from '../generated/components/call-incoming.tsx';
export { callIncomingIconDefinition } from '../generated/definitions/call-incoming.ts';
