/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalmIcon } from '../generated/components/calm.tsx';
export { calmIconDefinition } from '../generated/definitions/calm.ts';
