/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Camera2Icon } from '../generated/components/camera-2.tsx';
export { camera2IconDefinition } from '../generated/definitions/camera-2.ts';
