/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Camera1FilledIcon } from '../generated/components/camera-1-filled.tsx';
export { camera1FilledIconDefinition } from '../generated/definitions/camera-1-filled.ts';
