/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CameraFilledIcon } from '../generated/components/camera-filled.tsx';
export { cameraFilledIconDefinition } from '../generated/definitions/camera-filled.ts';
