/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretDownIcon } from '../generated/components/caret-down.tsx';
export { caretDownIconDefinition } from '../generated/definitions/caret-down.ts';
