/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretUpIcon } from '../generated/components/caret-up.tsx';
export { caretUpIconDefinition } from '../generated/definitions/caret-up.ts';
