/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CartAddIcon } from '../generated/components/cart-add.tsx';
export { cartAddIconDefinition } from '../generated/definitions/cart-add.ts';
