/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle6Icon } from '../generated/components/castle-6.tsx';
export { castle6IconDefinition } from '../generated/definitions/castle-6.ts';
