/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CastleIcon } from '../generated/components/castle.tsx';
export { castleIconDefinition } from '../generated/definitions/castle.ts';
