/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CelsiusIcon } from '../generated/components/celsius.tsx';
export { celsiusIconDefinition } from '../generated/definitions/celsius.ts';
