/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CenterFocusStrongIcon } from '../generated/components/center-focus-strong.tsx';
export { centerFocusStrongIconDefinition } from '../generated/definitions/center-focus-strong.ts';
