/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartLineBoardIcon } from '../generated/components/chart-line-board.tsx';
export { chartLineBoardIconDefinition } from '../generated/definitions/chart-line-board.ts';
