/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartIcon } from '../generated/components/chart.tsx';
export { chartIconDefinition } from '../generated/definitions/chart.ts';
