/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRadialIcon } from '../generated/components/chart-radial.tsx';
export { chartRadialIconDefinition } from '../generated/definitions/chart-radial.ts';
