/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartBarIcon } from '../generated/components/chart-bar.tsx';
export { chartBarIconDefinition } from '../generated/definitions/chart-bar.ts';
