/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRing1Icon } from '../generated/components/chart-ring-1.tsx';
export { chartRing1IconDefinition } from '../generated/definitions/chart-ring-1.ts';
