/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartLineMultiIcon } from '../generated/components/chart-line-multi.tsx';
export { chartLineMultiIconDefinition } from '../generated/definitions/chart-line-multi.ts';
