/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartPieIcon } from '../generated/components/chart-pie.tsx';
export { chartPieIconDefinition } from '../generated/definitions/chart-pie.ts';
