/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartAddIcon } from '../generated/components/chart-add.tsx';
export { chartAddIconDefinition } from '../generated/definitions/chart-add.ts';
