/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartPieFilledIcon } from '../generated/components/chart-pie-filled.tsx';
export { chartPieFilledIconDefinition } from '../generated/definitions/chart-pie-filled.ts';
