/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartFilledIcon } from '../generated/components/chart-filled.tsx';
export { chartFilledIconDefinition } from '../generated/definitions/chart-filled.ts';
