/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRadarFilledIcon } from '../generated/components/chart-radar-filled.tsx';
export { chartRadarFilledIconDefinition } from '../generated/definitions/chart-radar-filled.ts';
