/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatClearFilledIcon } from '../generated/components/chat-clear-filled.tsx';
export { chatClearFilledIconDefinition } from '../generated/definitions/chat-clear-filled.ts';
