/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubble1FilledIcon } from '../generated/components/chat-bubble-1-filled.tsx';
export { chatBubble1FilledIconDefinition } from '../generated/definitions/chat-bubble-1-filled.ts';
