/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatFilledIcon } from '../generated/components/chat-filled.tsx';
export { chatFilledIconDefinition } from '../generated/definitions/chat-filled.ts';
