/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatHeartIcon } from '../generated/components/chat-heart.tsx';
export { chatHeartIconDefinition } from '../generated/definitions/chat-heart.ts';
