/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatMessageIcon } from '../generated/components/chat-message.tsx';
export { chatMessageIconDefinition } from '../generated/definitions/chat-message.ts';
