/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatCheckedFilledIcon } from '../generated/components/chat-checked-filled.tsx';
export { chatCheckedFilledIconDefinition } from '../generated/definitions/chat-checked-filled.ts';
