/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatMessageFilledIcon } from '../generated/components/chat-message-filled.tsx';
export { chatMessageFilledIconDefinition } from '../generated/definitions/chat-message-filled.ts';
