/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CherryIcon } from '../generated/components/cherry.tsx';
export { cherryIconDefinition } from '../generated/definitions/cherry.ts';
