/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CherryFilledIcon } from '../generated/components/cherry-filled.tsx';
export { cherryFilledIconDefinition } from '../generated/definitions/cherry-filled.ts';
