/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronRightCircleFilledIcon } from '../generated/components/chevron-right-circle-filled.tsx';
export { chevronRightCircleFilledIconDefinition } from '../generated/definitions/chevron-right-circle-filled.ts';
