/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronRightRectangleFilledIcon } from '../generated/components/chevron-right-rectangle-filled.tsx';
export { chevronRightRectangleFilledIconDefinition } from '../generated/definitions/chevron-right-rectangle-filled.ts';
