/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronUpIcon } from '../generated/components/chevron-up.tsx';
export { chevronUpIconDefinition } from '../generated/definitions/chevron-up.ts';
