/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronDownRectangleIcon } from '../generated/components/chevron-down-rectangle.tsx';
export { chevronDownRectangleIconDefinition } from '../generated/definitions/chevron-down-rectangle.ts';
