/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronUpCircleFilledIcon } from '../generated/components/chevron-up-circle-filled.tsx';
export { chevronUpCircleFilledIconDefinition } from '../generated/definitions/chevron-up-circle-filled.ts';
