/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronUpRectangleIcon } from '../generated/components/chevron-up-rectangle.tsx';
export { chevronUpRectangleIconDefinition } from '../generated/definitions/chevron-up-rectangle.ts';
