/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronDownCircleIcon } from '../generated/components/chevron-down-circle.tsx';
export { chevronDownCircleIconDefinition } from '../generated/definitions/chevron-down-circle.ts';
