/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChiliIcon } from '../generated/components/chili.tsx';
export { chiliIconDefinition } from '../generated/definitions/chili.ts';
