/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChiliFilledIcon } from '../generated/components/chili-filled.tsx';
export { chiliFilledIconDefinition } from '../generated/definitions/chili-filled.ts';
