/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Chimney2FilledIcon } from '../generated/components/chimney-2-filled.tsx';
export { chimney2FilledIconDefinition } from '../generated/definitions/chimney-2-filled.ts';
