/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Chimney1FilledIcon } from '../generated/components/chimney-1-filled.tsx';
export { chimney1FilledIconDefinition } from '../generated/definitions/chimney-1-filled.ts';
