/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChineseRectangleIcon } from '../generated/components/chinese-rectangle.tsx';
export { chineseRectangleIconDefinition } from '../generated/definitions/chinese-rectangle.ts';
