/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChineseCabbageIcon } from '../generated/components/chinese-cabbage.tsx';
export { chineseCabbageIconDefinition } from '../generated/definitions/chinese-cabbage.ts';
