/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChurchIcon } from '../generated/components/church.tsx';
export { churchIconDefinition } from '../generated/definitions/church.ts';
