/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityAncient1FilledIcon } from '../generated/components/city-ancient-1-filled.tsx';
export { cityAncient1FilledIconDefinition } from '../generated/definitions/city-ancient-1-filled.ts';
