/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City5Icon } from '../generated/components/city-5.tsx';
export { city5IconDefinition } from '../generated/definitions/city-5.ts';
