/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City10FilledIcon } from '../generated/components/city-10-filled.tsx';
export { city10FilledIconDefinition } from '../generated/definitions/city-10-filled.ts';
