/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City5FilledIcon } from '../generated/components/city-5-filled.tsx';
export { city5FilledIconDefinition } from '../generated/definitions/city-5-filled.ts';
