/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City12Icon } from '../generated/components/city-12.tsx';
export { city12IconDefinition } from '../generated/definitions/city-12.ts';
