/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City15FilledIcon } from '../generated/components/city-15-filled.tsx';
export { city15FilledIconDefinition } from '../generated/definitions/city-15-filled.ts';
