/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City8Icon } from '../generated/components/city-8.tsx';
export { city8IconDefinition } from '../generated/definitions/city-8.ts';
