/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City9Icon } from '../generated/components/city-9.tsx';
export { city9IconDefinition } from '../generated/definitions/city-9.ts';
