/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City12FilledIcon } from '../generated/components/city-12-filled.tsx';
export { city12FilledIconDefinition } from '../generated/definitions/city-12-filled.ts';
