/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City6FilledIcon } from '../generated/components/city-6-filled.tsx';
export { city6FilledIconDefinition } from '../generated/definitions/city-6-filled.ts';
