/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ClearFormatting1FilledIcon } from '../generated/components/clear-formatting-1-filled.tsx';
export { clearFormatting1FilledIconDefinition } from '../generated/definitions/clear-formatting-1-filled.ts';
