/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ClearFilledIcon } from '../generated/components/clear-filled.tsx';
export { clearFilledIconDefinition } from '../generated/definitions/clear-filled.ts';
