/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudFilledIcon } from '../generated/components/cloud-filled.tsx';
export { cloudFilledIconDefinition } from '../generated/definitions/cloud-filled.ts';
