/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudIcon } from '../generated/components/cloud.tsx';
export { cloudIconDefinition } from '../generated/definitions/cloud.ts';
