/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudyRainIcon } from '../generated/components/cloudy-rain.tsx';
export { cloudyRainIconDefinition } from '../generated/definitions/cloudy-rain.ts';
