/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudySunnyIcon } from '../generated/components/cloudy-sunny.tsx';
export { cloudySunnyIconDefinition } from '../generated/definitions/cloudy-sunny.ts';
