/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CodeIcon } from '../generated/components/code.tsx';
export { codeIconDefinition } from '../generated/definitions/code.ts';
