/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Code1Icon } from '../generated/components/code-1.tsx';
export { code1IconDefinition } from '../generated/definitions/code-1.ts';
