/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ColaFilledIcon } from '../generated/components/cola-filled.tsx';
export { colaFilledIconDefinition } from '../generated/definitions/cola-filled.ts';
