/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CollectionIcon } from '../generated/components/collection.tsx';
export { collectionIconDefinition } from '../generated/definitions/collection.ts';
