/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ColorInvertIcon } from '../generated/components/color-invert.tsx';
export { colorInvertIconDefinition } from '../generated/definitions/color-invert.ts';
