/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ColumnLayoutIcon } from '../generated/components/column-layout.tsx';
export { columnLayoutIconDefinition } from '../generated/definitions/column-layout.ts';
