/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CombinationIcon } from '../generated/components/combination.tsx';
export { combinationIconDefinition } from '../generated/definitions/combination.ts';
