/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentDropdownIcon } from '../generated/components/component-dropdown.tsx';
export { componentDropdownIconDefinition } from '../generated/definitions/component-dropdown.ts';
