/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentLayoutFilledIcon } from '../generated/components/component-layout-filled.tsx';
export { componentLayoutFilledIconDefinition } from '../generated/definitions/component-layout-filled.ts';
