/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentGridFilledIcon } from '../generated/components/component-grid-filled.tsx';
export { componentGridFilledIconDefinition } from '../generated/definitions/component-grid-filled.ts';
