/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentRadioIcon } from '../generated/components/component-radio.tsx';
export { componentRadioIconDefinition } from '../generated/definitions/component-radio.ts';
