/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentStepsIcon } from '../generated/components/component-steps.tsx';
export { componentStepsIconDefinition } from '../generated/definitions/component-steps.ts';
