/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentDividerVerticalIcon } from '../generated/components/component-divider-vertical.tsx';
export { componentDividerVerticalIconDefinition } from '../generated/definitions/component-divider-vertical.ts';
