/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentSteps1FilledIcon } from '../generated/components/component-steps-1-filled.tsx';
export { componentSteps1FilledIconDefinition } from '../generated/definitions/component-steps-1-filled.ts';
