/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentGridIcon } from '../generated/components/component-grid.tsx';
export { componentGridIconDefinition } from '../generated/definitions/component-grid.ts';
