/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentDividerHorizontalFilledIcon } from '../generated/components/component-divider-horizontal-filled.tsx';
export { componentDividerHorizontalFilledIconDefinition } from '../generated/definitions/component-divider-horizontal-filled.ts';
