/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ContrastIcon } from '../generated/components/contrast.tsx';
export { contrastIconDefinition } from '../generated/definitions/contrast.ts';
