/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ContributeIcon } from '../generated/components/contribute.tsx';
export { contributeIconDefinition } from '../generated/definitions/contribute.ts';
