/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ContributeFilledIcon } from '../generated/components/contribute-filled.tsx';
export { contributeFilledIconDefinition } from '../generated/definitions/contribute-filled.ts';
