/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CooperateIcon } from '../generated/components/cooperate.tsx';
export { cooperateIconDefinition } from '../generated/definitions/cooperate.ts';
