/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CoordinateSystemIcon } from '../generated/components/coordinate-system.tsx';
export { coordinateSystemIconDefinition } from '../generated/definitions/coordinate-system.ts';
