/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CopyrightIcon } from '../generated/components/copyright.tsx';
export { copyrightIconDefinition } from '../generated/definitions/copyright.ts';
