/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CopyIcon } from '../generated/components/copy.tsx';
export { copyIconDefinition } from '../generated/definitions/copy.ts';
