/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CouponFilledIcon } from '../generated/components/coupon-filled.tsx';
export { couponFilledIconDefinition } from '../generated/definitions/coupon-filled.ts';
