/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CouponIcon } from '../generated/components/coupon.tsx';
export { couponIconDefinition } from '../generated/definitions/coupon.ts';
