/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CourseFilledIcon } from '../generated/components/course-filled.tsx';
export { courseFilledIconDefinition } from '../generated/definitions/course-filled.ts';
