/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CourseIcon } from '../generated/components/course.tsx';
export { courseIconDefinition } from '../generated/definitions/course.ts';
