/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CreditcardIcon } from '../generated/components/creditcard.tsx';
export { creditcardIconDefinition } from '../generated/definitions/creditcard.ts';
