/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CurtainFilledIcon } from '../generated/components/curtain-filled.tsx';
export { curtainFilledIconDefinition } from '../generated/definitions/curtain-filled.ts';
