/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CurtainIcon } from '../generated/components/curtain.tsx';
export { curtainIconDefinition } from '../generated/definitions/curtain.ts';
