/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DamIcon } from '../generated/components/dam.tsx';
export { damIconDefinition } from '../generated/definitions/dam.ts';
