/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DashboardFilledIcon } from '../generated/components/dashboard-filled.tsx';
export { dashboardFilledIconDefinition } from '../generated/definitions/dashboard-filled.ts';
