/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataCheckedFilledIcon } from '../generated/components/data-checked-filled.tsx';
export { dataCheckedFilledIconDefinition } from '../generated/definitions/data-checked-filled.ts';
