/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataErrorFilledIcon } from '../generated/components/data-error-filled.tsx';
export { dataErrorFilledIconDefinition } from '../generated/definitions/data-error-filled.ts';
