/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataSearchFilledIcon } from '../generated/components/data-search-filled.tsx';
export { dataSearchFilledIconDefinition } from '../generated/definitions/data-search-filled.ts';
