/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeleteFilledIcon } from '../generated/components/delete-filled.tsx';
export { deleteFilledIconDefinition } from '../generated/definitions/delete-filled.ts';
