/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeleteTimeIcon } from '../generated/components/delete-time.tsx';
export { deleteTimeIconDefinition } from '../generated/definitions/delete-time.ts';
