/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeleteTimeFilledIcon } from '../generated/components/delete-time-filled.tsx';
export { deleteTimeFilledIconDefinition } from '../generated/definitions/delete-time-filled.ts';
