/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DesktopFilledIcon } from '../generated/components/desktop-filled.tsx';
export { desktopFilledIconDefinition } from '../generated/definitions/desktop-filled.ts';
