/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Desktop1Icon } from '../generated/components/desktop-1.tsx';
export { desktop1IconDefinition } from '../generated/definitions/desktop-1.ts';
