/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeviceFilledIcon } from '../generated/components/device-filled.tsx';
export { deviceFilledIconDefinition } from '../generated/definitions/device-filled.ts';
