/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DocumentUpdateFilledIcon } from '../generated/components/document-update-filled.tsx';
export { documentUpdateFilledIconDefinition } from '../generated/definitions/document-update-filled.ts';
