/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Download1Icon } from '../generated/components/download-1.tsx';
export { download1IconDefinition } from '../generated/definitions/download-1.ts';
