/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DownscaleIcon } from '../generated/components/downscale.tsx';
export { downscaleIconDefinition } from '../generated/definitions/downscale.ts';
