/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Download2Icon } from '../generated/components/download-2.tsx';
export { download2IconDefinition } from '../generated/definitions/download-2.ts';
