/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DragDropIcon } from '../generated/components/drag-drop.tsx';
export { dragDropIconDefinition } from '../generated/definitions/drag-drop.ts';
