/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DvFilledIcon } from '../generated/components/dv-filled.tsx';
export { dvFilledIconDefinition } from '../generated/definitions/dv-filled.ts';
