/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DvdIcon } from '../generated/components/dvd.tsx';
export { dvdIconDefinition } from '../generated/definitions/dvd.ts';
