/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Edit2FilledIcon } from '../generated/components/edit-2-filled.tsx';
export { edit2FilledIconDefinition } from '../generated/definitions/edit-2-filled.ts';
