/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EggplantIcon } from '../generated/components/eggplant.tsx';
export { eggplantIconDefinition } from '../generated/definitions/eggplant.ts';
