/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ErrorCircleIcon } from '../generated/components/error-circle.tsx';
export { errorCircleIconDefinition } from '../generated/definitions/error-circle.ts';
