/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ErrorTriangleFilledIcon } from '../generated/components/error-triangle-filled.tsx';
export { errorTriangleFilledIconDefinition } from '../generated/definitions/error-triangle-filled.ts';
