/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExcitedIcon } from '../generated/components/excited.tsx';
export { excitedIconDefinition } from '../generated/definitions/excited.ts';
