/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Excited1FilledIcon } from '../generated/components/excited-1-filled.tsx';
export { excited1FilledIconDefinition } from '../generated/definitions/excited-1-filled.ts';
