/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExpandDownFilledIcon } from '../generated/components/expand-down-filled.tsx';
export { expandDownFilledIconDefinition } from '../generated/definitions/expand-down-filled.ts';
