/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExpandDownIcon } from '../generated/components/expand-down.tsx';
export { expandDownIconDefinition } from '../generated/definitions/expand-down.ts';
