/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExploreOffFilledIcon } from '../generated/components/explore-off-filled.tsx';
export { exploreOffFilledIconDefinition } from '../generated/definitions/explore-off-filled.ts';
