/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExtensionFilledIcon } from '../generated/components/extension-filled.tsx';
export { extensionFilledIconDefinition } from '../generated/definitions/extension-filled.ts';
