/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FaceRetouchingFilledIcon } from '../generated/components/face-retouching-filled.tsx';
export { faceRetouchingFilledIconDefinition } from '../generated/definitions/face-retouching-filled.ts';
