/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileZipIcon } from '../generated/components/file-zip.tsx';
export { fileZipIconDefinition } from '../generated/definitions/file-zip.ts';
