/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileSafetyFilledIcon } from '../generated/components/file-safety-filled.tsx';
export { fileSafetyFilledIconDefinition } from '../generated/definitions/file-safety-filled.ts';
