/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileTransmitFilledIcon } from '../generated/components/file-transmit-filled.tsx';
export { fileTransmitFilledIconDefinition } from '../generated/definitions/file-transmit-filled.ts';
