/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileMinusIcon } from '../generated/components/file-minus.tsx';
export { fileMinusIconDefinition } from '../generated/definitions/file-minus.ts';
