/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileLockedIcon } from '../generated/components/file-locked.tsx';
export { fileLockedIconDefinition } from '../generated/definitions/file-locked.ts';
