/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileUnlockedFilledIcon } from '../generated/components/file-unlocked-filled.tsx';
export { fileUnlockedFilledIconDefinition } from '../generated/definitions/file-unlocked-filled.ts';
