/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileJsonFilledIcon } from '../generated/components/file-json-filled.tsx';
export { fileJsonFilledIconDefinition } from '../generated/definitions/file-json-filled.ts';
