/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileIconIcon } from '../generated/components/file-icon.tsx';
export { fileIconIconDefinition } from '../generated/definitions/file-icon.ts';
