/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileFilledIcon } from '../generated/components/file-filled.tsx';
export { fileFilledIconDefinition } from '../generated/definitions/file-filled.ts';
