/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileImageIcon } from '../generated/components/file-image.tsx';
export { fileImageIconDefinition } from '../generated/definitions/file-image.ts';
