/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileMinusFilledIcon } from '../generated/components/file-minus-filled.tsx';
export { fileMinusFilledIconDefinition } from '../generated/definitions/file-minus-filled.ts';
