/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileWordFilledIcon } from '../generated/components/file-word-filled.tsx';
export { fileWordFilledIconDefinition } from '../generated/definitions/file-word-filled.ts';
