/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileTransmitIcon } from '../generated/components/file-transmit.tsx';
export { fileTransmitIconDefinition } from '../generated/definitions/file-transmit.ts';
