/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileDownloadIcon } from '../generated/components/file-download.tsx';
export { fileDownloadIconDefinition } from '../generated/definitions/file-download.ts';
