/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileUnknownIcon } from '../generated/components/file-unknown.tsx';
export { fileUnknownIconDefinition } from '../generated/definitions/file-unknown.ts';
