/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileImportIcon } from '../generated/components/file-import.tsx';
export { fileImportIconDefinition } from '../generated/definitions/file-import.ts';
