/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileOutlookIcon } from '../generated/components/file-outlook.tsx';
export { fileOutlookIconDefinition } from '../generated/definitions/file-outlook.ts';
