/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileRestoreIcon } from '../generated/components/file-restore.tsx';
export { fileRestoreIconDefinition } from '../generated/definitions/file-restore.ts';
