/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileMarkdownIcon } from '../generated/components/file-markdown.tsx';
export { fileMarkdownIconDefinition } from '../generated/definitions/file-markdown.ts';
