/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileAttachmentIcon } from '../generated/components/file-attachment.tsx';
export { fileAttachmentIconDefinition } from '../generated/definitions/file-attachment.ts';
