/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileAddIcon } from '../generated/components/file-add.tsx';
export { fileAddIconDefinition } from '../generated/definitions/file-add.ts';
