/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileEditFilledIcon } from '../generated/components/file-edit-filled.tsx';
export { fileEditFilledIconDefinition } from '../generated/definitions/file-edit-filled.ts';
