/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCsvIcon } from '../generated/components/file-csv.tsx';
export { fileCsvIconDefinition } from '../generated/definitions/file-csv.ts';
