/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilePasteFilledIcon } from '../generated/components/file-paste-filled.tsx';
export { filePasteFilledIconDefinition } from '../generated/definitions/file-paste-filled.ts';
