/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileEditIcon } from '../generated/components/file-edit.tsx';
export { fileEditIconDefinition } from '../generated/definitions/file-edit.ts';
