/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Film1Icon } from '../generated/components/film-1.tsx';
export { film1IconDefinition } from '../generated/definitions/film-1.ts';
