/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilmIcon } from '../generated/components/film.tsx';
export { filmIconDefinition } from '../generated/definitions/film.ts';
