/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Filter1FilledIcon } from '../generated/components/filter-1-filled.tsx';
export { filter1FilledIconDefinition } from '../generated/definitions/filter-1-filled.ts';
