/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilterClearIcon } from '../generated/components/filter-clear.tsx';
export { filterClearIconDefinition } from '../generated/definitions/filter-clear.ts';
