/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilterSortIcon } from '../generated/components/filter-sort.tsx';
export { filterSortIconDefinition } from '../generated/definitions/filter-sort.ts';
