/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilterOffFilledIcon } from '../generated/components/filter-off-filled.tsx';
export { filterOffFilledIconDefinition } from '../generated/definitions/filter-off-filled.ts';
