/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FingerprintIcon } from '../generated/components/fingerprint.tsx';
export { fingerprintIconDefinition } from '../generated/definitions/fingerprint.ts';
