/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FishFilledIcon } from '../generated/components/fish-filled.tsx';
export { fishFilledIconDefinition } from '../generated/definitions/fish-filled.ts';
