/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlagIcon } from '../generated/components/flag.tsx';
export { flagIconDefinition } from '../generated/definitions/flag.ts';
