/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag1FilledIcon } from '../generated/components/flag-1-filled.tsx';
export { flag1FilledIconDefinition } from '../generated/definitions/flag-1-filled.ts';
