/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlightTakeoffIcon } from '../generated/components/flight-takeoff.tsx';
export { flightTakeoffIconDefinition } from '../generated/definitions/flight-takeoff.ts';
