/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FocusFilledIcon } from '../generated/components/focus-filled.tsx';
export { focusFilledIconDefinition } from '../generated/definitions/focus-filled.ts';
