/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderDetailsFilledIcon } from '../generated/components/folder-details-filled.tsx';
export { folderDetailsFilledIconDefinition } from '../generated/definitions/folder-details-filled.ts';
