/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderOpen1Icon } from '../generated/components/folder-open-1.tsx';
export { folderOpen1IconDefinition } from '../generated/definitions/folder-open-1.ts';
