/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderSharedFilledIcon } from '../generated/components/folder-shared-filled.tsx';
export { folderSharedFilledIconDefinition } from '../generated/definitions/folder-shared-filled.ts';
