/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderImportIcon } from '../generated/components/folder-import.tsx';
export { folderImportIconDefinition } from '../generated/definitions/folder-import.ts';
