/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderAddFilledIcon } from '../generated/components/folder-add-filled.tsx';
export { folderAddFilledIconDefinition } from '../generated/definitions/folder-add-filled.ts';
