/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderUnlockedFilledIcon } from '../generated/components/folder-unlocked-filled.tsx';
export { folderUnlockedFilledIconDefinition } from '../generated/definitions/folder-unlocked-filled.ts';
