/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderIcon } from '../generated/components/folder.tsx';
export { folderIconDefinition } from '../generated/definitions/folder.ts';
