/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderSearchFilledIcon } from '../generated/components/folder-search-filled.tsx';
export { folderSearchFilledIconDefinition } from '../generated/definitions/folder-search-filled.ts';
