/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderExportFilledIcon } from '../generated/components/folder-export-filled.tsx';
export { folderExportFilledIconDefinition } from '../generated/definitions/folder-export-filled.ts';
