/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderZipFilledIcon } from '../generated/components/folder-zip-filled.tsx';
export { folderZipFilledIconDefinition } from '../generated/definitions/folder-zip-filled.ts';
