/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForestFilledIcon } from '../generated/components/forest-filled.tsx';
export { forestFilledIconDefinition } from '../generated/definitions/forest-filled.ts';
