/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForestIcon } from '../generated/components/forest.tsx';
export { forestIconDefinition } from '../generated/definitions/forest.ts';
