/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormatVerticalAlignRightIcon } from '../generated/components/format-vertical-align-right.tsx';
export { formatVerticalAlignRightIconDefinition } from '../generated/definitions/format-vertical-align-right.ts';
