/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormatHorizontalAlignBottomIcon } from '../generated/components/format-horizontal-align-bottom.tsx';
export { formatHorizontalAlignBottomIconDefinition } from '../generated/definitions/format-horizontal-align-bottom.ts';
