/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Frame1FilledIcon } from '../generated/components/frame-1-filled.tsx';
export { frame1FilledIconDefinition } from '../generated/definitions/frame-1-filled.ts';
