/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FunctionCurveIcon } from '../generated/components/function-curve.tsx';
export { functionCurveIconDefinition } from '../generated/definitions/function-curve.ts';
