/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FunctionsIcon } from '../generated/components/functions.tsx';
export { functionsIconDefinition } from '../generated/definitions/functions.ts';
