/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GamepadIcon } from '../generated/components/gamepad.tsx';
export { gamepadIconDefinition } from '../generated/definitions/gamepad.ts';
