/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GenderMaleIcon } from '../generated/components/gender-male.tsx';
export { genderMaleIconDefinition } from '../generated/definitions/gender-male.ts';
