/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GesturePrayIcon } from '../generated/components/gesture-pray.tsx';
export { gesturePrayIconDefinition } from '../generated/definitions/gesture-pray.ts';
