/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureWipeDownFilledIcon } from '../generated/components/gesture-wipe-down-filled.tsx';
export { gestureWipeDownFilledIconDefinition } from '../generated/definitions/gesture-wipe-down-filled.ts';
