/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureRightFilledIcon } from '../generated/components/gesture-right-filled.tsx';
export { gestureRightFilledIconDefinition } from '../generated/definitions/gesture-right-filled.ts';
