/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureTypingIcon } from '../generated/components/gesture-typing.tsx';
export { gestureTypingIconDefinition } from '../generated/definitions/gesture-typing.ts';
