/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureOpenIcon } from '../generated/components/gesture-open.tsx';
export { gestureOpenIconDefinition } from '../generated/definitions/gesture-open.ts';
