/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GiggleFilledIcon } from '../generated/components/giggle-filled.tsx';
export { giggleFilledIconDefinition } from '../generated/definitions/giggle-filled.ts';
