/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GitMergeFilledIcon } from '../generated/components/git-merge-filled.tsx';
export { gitMergeFilledIconDefinition } from '../generated/definitions/git-merge-filled.ts';
