/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GitMergeIcon } from '../generated/components/git-merge.tsx';
export { gitMergeIconDefinition } from '../generated/definitions/git-merge.ts';
