/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GpsIcon } from '../generated/components/gps.tsx';
export { gpsIconDefinition } from '../generated/definitions/gps.ts';
