/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GraphvizIcon } from '../generated/components/graphviz.tsx';
export { graphvizIconDefinition } from '../generated/definitions/graphviz.ts';
