/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HdIcon } from '../generated/components/hd.tsx';
export { hdIconDefinition } from '../generated/definitions/hd.ts';
