/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HeartIcon } from '../generated/components/heart.tsx';
export { heartIconDefinition } from '../generated/definitions/heart.ts';
