/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HelpRectangleFilledIcon } from '../generated/components/help-rectangle-filled.tsx';
export { helpRectangleFilledIconDefinition } from '../generated/definitions/help-rectangle-filled.ts';
