/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HelpRectangleIcon } from '../generated/components/help-rectangle.tsx';
export { helpRectangleIconDefinition } from '../generated/definitions/help-rectangle.ts';
