/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HighLevelIcon } from '../generated/components/high-level.tsx';
export { highLevelIconDefinition } from '../generated/definitions/high-level.ts';
