/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HistorySettingIcon } from '../generated/components/history-setting.tsx';
export { historySettingIconDefinition } from '../generated/definitions/history-setting.ts';
