/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HorizontalIcon } from '../generated/components/horizontal.tsx';
export { horizontalIconDefinition } from '../generated/definitions/horizontal.ts';
