/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HospitalFilledIcon } from '../generated/components/hospital-filled.tsx';
export { hospitalFilledIconDefinition } from '../generated/definitions/hospital-filled.ts';
