/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HotspotWaveFilledIcon } from '../generated/components/hotspot-wave-filled.tsx';
export { hotspotWaveFilledIconDefinition } from '../generated/definitions/hotspot-wave-filled.ts';
