/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HourglassIcon } from '../generated/components/hourglass.tsx';
export { hourglassIconDefinition } from '../generated/definitions/hourglass.ts';
