/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Houses1Icon } from '../generated/components/houses-1.tsx';
export { houses1IconDefinition } from '../generated/definitions/houses-1.ts';
