/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Houses1FilledIcon } from '../generated/components/houses-1-filled.tsx';
export { houses1FilledIconDefinition } from '../generated/definitions/houses-1-filled.ts';
