/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { IceCreamFilledIcon } from '../generated/components/ice-cream-filled.tsx';
export { iceCreamFilledIconDefinition } from '../generated/definitions/ice-cream-filled.ts';
