/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageOffIcon } from '../generated/components/image-off.tsx';
export { imageOffIconDefinition } from '../generated/definitions/image-off.ts';
