/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageCarouselIcon } from '../generated/components/image-carousel.tsx';
export { imageCarouselIconDefinition } from '../generated/definitions/image-carousel.ts';
