/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageSearchFilledIcon } from '../generated/components/image-search-filled.tsx';
export { imageSearchFilledIconDefinition } from '../generated/definitions/image-search-filled.ts';
