/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InkFilledIcon } from '../generated/components/ink-filled.tsx';
export { inkFilledIconDefinition } from '../generated/definitions/ink-filled.ts';
