/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InkIcon } from '../generated/components/ink.tsx';
export { inkIconDefinition } from '../generated/definitions/ink.ts';
