/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InstitutionFilledIcon } from '../generated/components/institution-filled.tsx';
export { institutionFilledIconDefinition } from '../generated/definitions/institution-filled.ts';
