/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InstallMobileIcon } from '../generated/components/install-mobile.tsx';
export { installMobileIconDefinition } from '../generated/definitions/install-mobile.ts';
