/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InstallMobileFilledIcon } from '../generated/components/install-mobile-filled.tsx';
export { installMobileFilledIconDefinition } from '../generated/definitions/install-mobile-filled.ts';
