/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { IpodFilledIcon } from '../generated/components/ipod-filled.tsx';
export { ipodFilledIconDefinition } from '../generated/definitions/ipod-filled.ts';
