/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { JapaneseRectangleIcon } from '../generated/components/japanese-rectangle.tsx';
export { japaneseRectangleIconDefinition } from '../generated/definitions/japanese-rectangle.ts';
