/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { JoyfulFilledIcon } from '../generated/components/joyful-filled.tsx';
export { joyfulFilledIconDefinition } from '../generated/definitions/joyful-filled.ts';
