/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { JumpOffIcon } from '../generated/components/jump-off.tsx';
export { jumpOffIconDefinition } from '../generated/definitions/jump-off.ts';
