/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { KeyboardFilledIcon } from '../generated/components/keyboard-filled.tsx';
export { keyboardFilledIconDefinition } from '../generated/definitions/keyboard-filled.ts';
