/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { KeyboardIcon } from '../generated/components/keyboard.tsx';
export { keyboardIconDefinition } from '../generated/definitions/keyboard.ts';
