/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LeaderboardFilledIcon } from '../generated/components/leaderboard-filled.tsx';
export { leaderboardFilledIconDefinition } from '../generated/definitions/leaderboard-filled.ts';
