/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LessThanOrEqualIcon } from '../generated/components/less-than-or-equal.tsx';
export { lessThanOrEqualIconDefinition } from '../generated/definitions/less-than-or-equal.ts';
