/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersBIcon } from '../generated/components/letters-b.tsx';
export { lettersBIconDefinition } from '../generated/definitions/letters-b.ts';
