/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersPIcon } from '../generated/components/letters-p.tsx';
export { lettersPIconDefinition } from '../generated/definitions/letters-p.ts';
