/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersRIcon } from '../generated/components/letters-r.tsx';
export { lettersRIconDefinition } from '../generated/definitions/letters-r.ts';
