/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LightbulbIcon } from '../generated/components/lightbulb.tsx';
export { lightbulbIconDefinition } from '../generated/definitions/lightbulb.ts';
