/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LighthouseIcon } from '../generated/components/lighthouse.tsx';
export { lighthouseIconDefinition } from '../generated/definitions/lighthouse.ts';
