/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LiquorIcon } from '../generated/components/liquor.tsx';
export { liquorIconDefinition } from '../generated/definitions/liquor.ts';
