/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ListNumberedIcon } from '../generated/components/list-numbered.tsx';
export { listNumberedIconDefinition } from '../generated/definitions/list-numbered.ts';
