/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LoadingIcon } from '../generated/components/loading.tsx';
export { loadingIconDefinition } from '../generated/definitions/loading.ts';
