/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LoadIcon } from '../generated/components/load.tsx';
export { loadIconDefinition } from '../generated/definitions/load.ts';
