/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Location1FilledIcon } from '../generated/components/location-1-filled.tsx';
export { location1FilledIconDefinition } from '../generated/definitions/location-1-filled.ts';
