/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationIcon } from '../generated/components/location.tsx';
export { locationIconDefinition } from '../generated/definitions/location.ts';
