/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationErrorIcon } from '../generated/components/location-error.tsx';
export { locationErrorIconDefinition } from '../generated/definitions/location-error.ts';
