/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationFilledIcon } from '../generated/components/location-filled.tsx';
export { locationFilledIconDefinition } from '../generated/definitions/location-filled.ts';
