/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LockCheckedIcon } from '../generated/components/lock-checked.tsx';
export { lockCheckedIconDefinition } from '../generated/definitions/lock-checked.ts';
