/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCnbIcon } from '../generated/components/logo-cnb.tsx';
export { logoCnbIconDefinition } from '../generated/definitions/logo-cnb.ts';
