/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTwitterIcon } from '../generated/components/logo-twitter.tsx';
export { logoTwitterIconDefinition } from '../generated/definitions/logo-twitter.ts';
