/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoBehanceFilledIcon } from '../generated/components/logo-behance-filled.tsx';
export { logoBehanceFilledIconDefinition } from '../generated/definitions/logo-behance-filled.ts';
