/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoIwikiIcon } from '../generated/components/logo-iwiki.tsx';
export { logoIwikiIconDefinition } from '../generated/definitions/logo-iwiki.ts';
