/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTencentmeetingIcon } from '../generated/components/logo-tencentmeeting.tsx';
export { logoTencentmeetingIconDefinition } from '../generated/definitions/logo-tencentmeeting.ts';
