/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAdobeIllustrateIcon } from '../generated/components/logo-adobe-illustrate.tsx';
export { logoAdobeIllustrateIconDefinition } from '../generated/definitions/logo-adobe-illustrate.ts';
