/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAppleFilledIcon } from '../generated/components/logo-apple-filled.tsx';
export { logoAppleFilledIconDefinition } from '../generated/definitions/logo-apple-filled.ts';
