/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoYoutubeIcon } from '../generated/components/logo-youtube.tsx';
export { logoYoutubeIconDefinition } from '../generated/definitions/logo-youtube.ts';
