/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoWindowsFilledIcon } from '../generated/components/logo-windows-filled.tsx';
export { logoWindowsFilledIconDefinition } from '../generated/definitions/logo-windows-filled.ts';
