/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoDribbbleFilledIcon } from '../generated/components/logo-dribbble-filled.tsx';
export { logoDribbbleFilledIconDefinition } from '../generated/definitions/logo-dribbble-filled.ts';
