/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCnbFilledIcon } from '../generated/components/logo-cnb-filled.tsx';
export { logoCnbFilledIconDefinition } from '../generated/definitions/logo-cnb-filled.ts';
