/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAdobeIllustrateFilledIcon } from '../generated/components/logo-adobe-illustrate-filled.tsx';
export { logoAdobeIllustrateFilledIconDefinition } from '../generated/definitions/logo-adobe-illustrate-filled.ts';
