/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAppleIcon } from '../generated/components/logo-apple.tsx';
export { logoAppleIconDefinition } from '../generated/definitions/logo-apple.ts';
