/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoQqIcon } from '../generated/components/logo-qq.tsx';
export { logoQqIconDefinition } from '../generated/definitions/logo-qq.ts';
