/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFramerFilledIcon } from '../generated/components/logo-framer-filled.tsx';
export { logoFramerFilledIconDefinition } from '../generated/definitions/logo-framer-filled.ts';
