/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoGithubFilledIcon } from '../generated/components/logo-github-filled.tsx';
export { logoGithubFilledIconDefinition } from '../generated/definitions/logo-github-filled.ts';
