/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoWecomIcon } from '../generated/components/logo-wecom.tsx';
export { logoWecomIconDefinition } from '../generated/definitions/logo-wecom.ts';
