/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MailFilledIcon } from '../generated/components/mail-filled.tsx';
export { mailFilledIconDefinition } from '../generated/definitions/mail-filled.ts';
