/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformation1FilledIcon } from '../generated/components/map-information-1-filled.tsx';
export { mapInformation1FilledIconDefinition } from '../generated/definitions/map-information-1-filled.ts';
