/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapCancelFilledIcon } from '../generated/components/map-cancel-filled.tsx';
export { mapCancelFilledIconDefinition } from '../generated/definitions/map-cancel-filled.ts';
