/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapFilledIcon } from '../generated/components/map-filled.tsx';
export { mapFilledIconDefinition } from '../generated/definitions/map-filled.ts';
