/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapMarkedFilledIcon } from '../generated/components/map-marked-filled.tsx';
export { mapMarkedFilledIconDefinition } from '../generated/definitions/map-marked-filled.ts';
