/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapOutlineIcon } from '../generated/components/map-outline.tsx';
export { mapOutlineIconDefinition } from '../generated/definitions/map-outline.ts';
