/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapEditIcon } from '../generated/components/map-edit.tsx';
export { mapEditIconDefinition } from '../generated/definitions/map-edit.ts';
