/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapEditFilledIcon } from '../generated/components/map-edit-filled.tsx';
export { mapEditFilledIconDefinition } from '../generated/definitions/map-edit-filled.ts';
