/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSearchIcon } from '../generated/components/map-search.tsx';
export { mapSearchIconDefinition } from '../generated/definitions/map-search.ts';
