/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSettingFilledIcon } from '../generated/components/map-setting-filled.tsx';
export { mapSettingFilledIconDefinition } from '../generated/definitions/map-setting-filled.ts';
