/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapAddIcon } from '../generated/components/map-add.tsx';
export { mapAddIconDefinition } from '../generated/definitions/map-add.ts';
