/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformationIcon } from '../generated/components/map-information.tsx';
export { mapInformationIconDefinition } from '../generated/definitions/map-information.ts';
