/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSafetyFilledIcon } from '../generated/components/map-safety-filled.tsx';
export { mapSafetyFilledIconDefinition } from '../generated/definitions/map-safety-filled.ts';
