/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapCollectionIcon } from '../generated/components/map-collection.tsx';
export { mapCollectionIconDefinition } from '../generated/definitions/map-collection.ts';
