/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformation1Icon } from '../generated/components/map-information-1.tsx';
export { mapInformation1IconDefinition } from '../generated/definitions/map-information-1.ts';
