/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSearch1Icon } from '../generated/components/map-search-1.tsx';
export { mapSearch1IconDefinition } from '../generated/definitions/map-search-1.ts';
