/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapChatIcon } from '../generated/components/map-chat.tsx';
export { mapChatIconDefinition } from '../generated/definitions/map-chat.ts';
