/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapLocationFilledIcon } from '../generated/components/map-location-filled.tsx';
export { mapLocationFilledIconDefinition } from '../generated/definitions/map-location-filled.ts';
