/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapAimingFilledIcon } from '../generated/components/map-aiming-filled.tsx';
export { mapAimingFilledIconDefinition } from '../generated/definitions/map-aiming-filled.ts';
