/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapCheckedIcon } from '../generated/components/map-checked.tsx';
export { mapCheckedIconDefinition } from '../generated/definitions/map-checked.ts';
