/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MediaLibraryIcon } from '../generated/components/media-library.tsx';
export { mediaLibraryIconDefinition } from '../generated/definitions/media-library.ts';
