/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MemberFilledIcon } from '../generated/components/member-filled.tsx';
export { memberFilledIconDefinition } from '../generated/definitions/member-filled.ts';
