/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MenuUnfoldIcon } from '../generated/components/menu-unfold.tsx';
export { menuUnfoldIconDefinition } from '../generated/definitions/menu-unfold.ts';
