/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MenuFoldIcon } from '../generated/components/menu-fold.tsx';
export { menuFoldIconDefinition } from '../generated/definitions/menu-fold.ts';
