/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MergeCellsIcon } from '../generated/components/merge-cells.tsx';
export { mergeCellsIconDefinition } from '../generated/definitions/merge-cells.ts';
