/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MilkFilledIcon } from '../generated/components/milk-filled.tsx';
export { milkFilledIconDefinition } from '../generated/definitions/milk-filled.ts';
