/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MinusCircleIcon } from '../generated/components/minus-circle.tsx';
export { minusCircleIconDefinition } from '../generated/definitions/minus-circle.ts';
