/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MinusCircleFilledIcon } from '../generated/components/minus-circle-filled.tsx';
export { minusCircleFilledIconDefinition } from '../generated/definitions/minus-circle-filled.ts';
