/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MobileBlockedFilledIcon } from '../generated/components/mobile-blocked-filled.tsx';
export { mobileBlockedFilledIconDefinition } from '../generated/definitions/mobile-blocked-filled.ts';
