/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MobileIcon } from '../generated/components/mobile.tsx';
export { mobileIconDefinition } from '../generated/definitions/mobile.ts';
