/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MobileNavigationIcon } from '../generated/components/mobile-navigation.tsx';
export { mobileNavigationIconDefinition } from '../generated/definitions/mobile-navigation.ts';
