/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MobileVibrateIcon } from '../generated/components/mobile-vibrate.tsx';
export { mobileVibrateIconDefinition } from '../generated/definitions/mobile-vibrate.ts';
