/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModeTextIcon } from '../generated/components/mode-text.tsx';
export { modeTextIconDefinition } from '../generated/definitions/mode-text.ts';
