/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModeDarkFilledIcon } from '../generated/components/mode-dark-filled.tsx';
export { modeDarkFilledIconDefinition } from '../generated/definitions/mode-dark-filled.ts';
