/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoonFallFilledIcon } from '../generated/components/moon-fall-filled.tsx';
export { moonFallFilledIconDefinition } from '../generated/definitions/moon-fall-filled.ts';
