/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MosqueIcon } from '../generated/components/mosque.tsx';
export { mosqueIconDefinition } from '../generated/definitions/mosque.ts';
