/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MosqueFilledIcon } from '../generated/components/mosque-filled.tsx';
export { mosqueFilledIconDefinition } from '../generated/definitions/mosque-filled.ts';
