/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Mosque1FilledIcon } from '../generated/components/mosque-1-filled.tsx';
export { mosque1FilledIconDefinition } from '../generated/definitions/mosque-1-filled.ts';
