/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MultiplyIcon } from '../generated/components/multiply.tsx';
export { multiplyIconDefinition } from '../generated/definitions/multiply.ts';
