/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Museum2FilledIcon } from '../generated/components/museum-2-filled.tsx';
export { museum2FilledIconDefinition } from '../generated/definitions/museum-2-filled.ts';
