/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Museum2Icon } from '../generated/components/museum-2.tsx';
export { museum2IconDefinition } from '../generated/definitions/museum-2.ts';
