/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Museum1Icon } from '../generated/components/museum-1.tsx';
export { museum1IconDefinition } from '../generated/definitions/museum-1.ts';
