/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MusicIcon } from '../generated/components/music.tsx';
export { musicIconDefinition } from '../generated/definitions/music.ts';
