/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Music1Icon } from '../generated/components/music-1.tsx';
export { music1IconDefinition } from '../generated/definitions/music-1.ts';
