/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NoExpressionFilledIcon } from '../generated/components/no-expression-filled.tsx';
export { noExpressionFilledIconDefinition } from '../generated/definitions/no-expression-filled.ts';
