/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NotificationErrorFilledIcon } from '../generated/components/notification-error-filled.tsx';
export { notificationErrorFilledIconDefinition } from '../generated/definitions/notification-error-filled.ts';
