/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers71Icon } from '../generated/components/numbers-7-1.tsx';
export { numbers71IconDefinition } from '../generated/definitions/numbers-7-1.ts';
