/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers21Icon } from '../generated/components/numbers-2-1.tsx';
export { numbers21IconDefinition } from '../generated/definitions/numbers-2-1.ts';
