/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers91Icon } from '../generated/components/numbers-9-1.tsx';
export { numbers91IconDefinition } from '../generated/definitions/numbers-9-1.ts';
