/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers7Icon } from '../generated/components/numbers-7.tsx';
export { numbers7IconDefinition } from '../generated/definitions/numbers-7.ts';
