/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NumbersCircle4Icon } from '../generated/components/numbers-circle-4.tsx';
export { numbersCircle4IconDefinition } from '../generated/definitions/numbers-circle-4.ts';
