/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers4Icon } from '../generated/components/numbers-4.tsx';
export { numbers4IconDefinition } from '../generated/definitions/numbers-4.ts';
