/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NumbersCircle3FilledIcon } from '../generated/components/numbers-circle-3-filled.tsx';
export { numbersCircle3FilledIconDefinition } from '../generated/definitions/numbers-circle-3-filled.ts';
