/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers2Icon } from '../generated/components/numbers-2.tsx';
export { numbers2IconDefinition } from '../generated/definitions/numbers-2.ts';
