/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OpenMouthFilledIcon } from '../generated/components/open-mouth-filled.tsx';
export { openMouthFilledIconDefinition } from '../generated/definitions/open-mouth-filled.ts';
