/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OperaIcon } from '../generated/components/opera.tsx';
export { operaIconDefinition } from '../generated/definitions/opera.ts';
