/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OrderAscendingIcon } from '../generated/components/order-ascending.tsx';
export { orderAscendingIconDefinition } from '../generated/definitions/order-ascending.ts';
