/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PanoramaHorizontalFilledIcon } from '../generated/components/panorama-horizontal-filled.tsx';
export { panoramaHorizontalFilledIconDefinition } from '../generated/definitions/panorama-horizontal-filled.ts';
