/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PanoramaHorizontalIcon } from '../generated/components/panorama-horizontal.tsx';
export { panoramaHorizontalIconDefinition } from '../generated/definitions/panorama-horizontal.ts';
