/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PantoneFilledIcon } from '../generated/components/pantone-filled.tsx';
export { pantoneFilledIconDefinition } from '../generated/definitions/pantone-filled.ts';
