/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PatioIcon } from '../generated/components/patio.tsx';
export { patioIconDefinition } from '../generated/definitions/patio.ts';
