/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PauseCircleFilledIcon } from '../generated/components/pause-circle-filled.tsx';
export { pauseCircleFilledIconDefinition } from '../generated/definitions/pause-circle-filled.ts';
