/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PeaIcon } from '../generated/components/pea.tsx';
export { peaIconDefinition } from '../generated/definitions/pea.ts';
