/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PeachFilledIcon } from '../generated/components/peach-filled.tsx';
export { peachFilledIconDefinition } from '../generated/definitions/peach-filled.ts';
