/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PearFilledIcon } from '../generated/components/pear-filled.tsx';
export { pearFilledIconDefinition } from '../generated/definitions/pear-filled.ts';
