/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenBrushIcon } from '../generated/components/pen-brush.tsx';
export { penBrushIconDefinition } from '../generated/definitions/pen-brush.ts';
