/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenFluorescenceIcon } from '../generated/components/pen-fluorescence.tsx';
export { penFluorescenceIconDefinition } from '../generated/definitions/pen-fluorescence.ts';
