/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenMarkIcon } from '../generated/components/pen-mark.tsx';
export { penMarkIconDefinition } from '../generated/definitions/pen-mark.ts';
