/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PersonalInformationIcon } from '../generated/components/personal-information.tsx';
export { personalInformationIconDefinition } from '../generated/definitions/personal-information.ts';
