/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PhoneLockedIcon } from '../generated/components/phone-locked.tsx';
export { phoneLockedIconDefinition } from '../generated/definitions/phone-locked.ts';
