/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PiIcon } from '../generated/components/pi.tsx';
export { piIconDefinition } from '../generated/definitions/pi.ts';
