/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlantumlIcon } from '../generated/components/plantuml.tsx';
export { plantumlIconDefinition } from '../generated/definitions/plantuml.ts';
