/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlantumlFilledIcon } from '../generated/components/plantuml-filled.tsx';
export { plantumlFilledIconDefinition } from '../generated/definitions/plantuml-filled.ts';
