/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayCircleStrokeAddIcon } from '../generated/components/play-circle-stroke-add.tsx';
export { playCircleStrokeAddIconDefinition } from '../generated/definitions/play-circle-stroke-add.ts';
