/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayCircleStrokeAddFilledIcon } from '../generated/components/play-circle-stroke-add-filled.tsx';
export { playCircleStrokeAddFilledIconDefinition } from '../generated/definitions/play-circle-stroke-add-filled.ts';
