/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayRectangleIcon } from '../generated/components/play-rectangle.tsx';
export { playRectangleIconDefinition } from '../generated/definitions/play-rectangle.ts';
