/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlusIcon } from '../generated/components/plus.tsx';
export { plusIconDefinition } from '../generated/definitions/plus.ts';
