/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PreviousIcon } from '../generated/components/previous.tsx';
export { previousIconDefinition } from '../generated/definitions/previous.ts';
