/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PyramidMayaFilledIcon } from '../generated/components/pyramid-maya-filled.tsx';
export { pyramidMayaFilledIconDefinition } from '../generated/definitions/pyramid-maya-filled.ts';
