/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QrcodeIcon } from '../generated/components/qrcode.tsx';
export { qrcodeIconDefinition } from '../generated/definitions/qrcode.ts';
