/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QueueIcon } from '../generated/components/queue.tsx';
export { queueIconDefinition } from '../generated/definitions/queue.ts';
