/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QuoteFilledIcon } from '../generated/components/quote-filled.tsx';
export { quoteFilledIconDefinition } from '../generated/definitions/quote-filled.ts';
