/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Radio2FilledIcon } from '../generated/components/radio-2-filled.tsx';
export { radio2FilledIconDefinition } from '../generated/definitions/radio-2-filled.ts';
