/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RadishIcon } from '../generated/components/radish.tsx';
export { radishIconDefinition } from '../generated/definitions/radish.ts';
