/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RectangleFilledIcon } from '../generated/components/rectangle-filled.tsx';
export { rectangleFilledIconDefinition } from '../generated/definitions/rectangle-filled.ts';
