/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RelativityFilledIcon } from '../generated/components/relativity-filled.tsx';
export { relativityFilledIconDefinition } from '../generated/definitions/relativity-filled.ts';
