/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RelativityIcon } from '../generated/components/relativity.tsx';
export { relativityIconDefinition } from '../generated/definitions/relativity.ts';
