/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RenameFilledIcon } from '../generated/components/rename-filled.tsx';
export { renameFilledIconDefinition } from '../generated/definitions/rename-filled.ts';
