/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RiceBallFilledIcon } from '../generated/components/rice-ball-filled.tsx';
export { riceBallFilledIconDefinition } from '../generated/definitions/rice-ball-filled.ts';
