/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RobotFilledIcon } from '../generated/components/robot-filled.tsx';
export { robotFilledIconDefinition } from '../generated/definitions/robot-filled.ts';
