/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RobotIcon } from '../generated/components/robot.tsx';
export { robotIconDefinition } from '../generated/definitions/robot.ts';
