/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Robot2Icon } from '../generated/components/robot-2.tsx';
export { robot2IconDefinition } from '../generated/definitions/robot-2.ts';
