/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RootListIcon } from '../generated/components/root-list.tsx';
export { rootListIconDefinition } from '../generated/definitions/root-list.ts';
