/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RootListFilledIcon } from '../generated/components/root-list-filled.tsx';
export { rootListFilledIconDefinition } from '../generated/definitions/root-list-filled.ts';
