/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SaturationIcon } from '../generated/components/saturation.tsx';
export { saturationIconDefinition } from '../generated/definitions/saturation.ts';
