/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SavingPotFilledIcon } from '../generated/components/saving-pot-filled.tsx';
export { savingPotFilledIconDefinition } from '../generated/definitions/saving-pot-filled.ts';
