/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ScreencastFilledIcon } from '../generated/components/screencast-filled.tsx';
export { screencastFilledIconDefinition } from '../generated/definitions/screencast-filled.ts';
