/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Screen4kFilledIcon } from '../generated/components/screen-4k-filled.tsx';
export { screen4kFilledIconDefinition } from '../generated/definitions/screen-4k-filled.ts';
