/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SdCard1Icon } from '../generated/components/sd-card-1.tsx';
export { sdCard1IconDefinition } from '../generated/definitions/sd-card-1.ts';
