/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SdCard1FilledIcon } from '../generated/components/sd-card-1-filled.tsx';
export { sdCard1FilledIconDefinition } from '../generated/definitions/sd-card-1-filled.ts';
