/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SealFilledIcon } from '../generated/components/seal-filled.tsx';
export { sealFilledIconDefinition } from '../generated/definitions/seal-filled.ts';
