/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SearchErrorFilledIcon } from '../generated/components/search-error-filled.tsx';
export { searchErrorFilledIconDefinition } from '../generated/definitions/search-error-filled.ts';
