/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SecuredFilledIcon } from '../generated/components/secured-filled.tsx';
export { securedFilledIconDefinition } from '../generated/definitions/secured-filled.ts';
