/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SendFilledIcon } from '../generated/components/send-filled.tsx';
export { sendFilledIconDefinition } from '../generated/definitions/send-filled.ts';
