/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SerenityFilledIcon } from '../generated/components/serenity-filled.tsx';
export { serenityFilledIconDefinition } from '../generated/definitions/serenity-filled.ts';
