/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ServiceIcon } from '../generated/components/service.tsx';
export { serviceIconDefinition } from '../generated/definitions/service.ts';
