/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SettingFilledIcon } from '../generated/components/setting-filled.tsx';
export { settingFilledIconDefinition } from '../generated/definitions/setting-filled.ts';
