/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Setting1FilledIcon } from '../generated/components/setting-1-filled.tsx';
export { setting1FilledIconDefinition } from '../generated/definitions/setting-1-filled.ts';
