/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SettingIcon } from '../generated/components/setting.tsx';
export { settingIconDefinition } from '../generated/definitions/setting.ts';
