/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShieldErrorIcon } from '../generated/components/shield-error.tsx';
export { shieldErrorIconDefinition } from '../generated/definitions/shield-error.ts';
