/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop1FilledIcon } from '../generated/components/shop-1-filled.tsx';
export { shop1FilledIconDefinition } from '../generated/definitions/shop-1-filled.ts';
