/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop4Icon } from '../generated/components/shop-4.tsx';
export { shop4IconDefinition } from '../generated/definitions/shop-4.ts';
