/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop5Icon } from '../generated/components/shop-5.tsx';
export { shop5IconDefinition } from '../generated/definitions/shop-5.ts';
