/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop3Icon } from '../generated/components/shop-3.tsx';
export { shop3IconDefinition } from '../generated/definitions/shop-3.ts';
