/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShrimpFilledIcon } from '../generated/components/shrimp-filled.tsx';
export { shrimpFilledIconDefinition } from '../generated/definitions/shrimp-filled.ts';
