/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShutupIcon } from '../generated/components/shutup.tsx';
export { shutupIconDefinition } from '../generated/definitions/shutup.ts';
