/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SimCard2Icon } from '../generated/components/sim-card-2.tsx';
export { simCard2IconDefinition } from '../generated/definitions/sim-card-2.ts';
