/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SimCardFilledIcon } from '../generated/components/sim-card-filled.tsx';
export { simCardFilledIconDefinition } from '../generated/definitions/sim-card-filled.ts';
