/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SimCard1Icon } from '../generated/components/sim-card-1.tsx';
export { simCard1IconDefinition } from '../generated/definitions/sim-card-1.ts';
