/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SinisterSmileFilledIcon } from '../generated/components/sinister-smile-filled.tsx';
export { sinisterSmileFilledIconDefinition } from '../generated/definitions/sinister-smile-filled.ts';
