/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SitemapFilledIcon } from '../generated/components/sitemap-filled.tsx';
export { sitemapFilledIconDefinition } from '../generated/definitions/sitemap-filled.ts';
