/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SleepIcon } from '../generated/components/sleep.tsx';
export { sleepIconDefinition } from '../generated/definitions/sleep.ts';
