/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SlideshowFilledIcon } from '../generated/components/slideshow-filled.tsx';
export { slideshowFilledIconDefinition } from '../generated/definitions/slideshow-filled.ts';
