/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SmileFilledIcon } from '../generated/components/smile-filled.tsx';
export { smileFilledIconDefinition } from '../generated/definitions/smile-filled.ts';
