/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundMute1Icon } from '../generated/components/sound-mute-1.tsx';
export { soundMute1IconDefinition } from '../generated/definitions/sound-mute-1.ts';
