/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SpeechlessIcon } from '../generated/components/speechless.tsx';
export { speechlessIconDefinition } from '../generated/definitions/speechless.ts';
