/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StarFilledIcon } from '../generated/components/star-filled.tsx';
export { starFilledIconDefinition } from '../generated/definitions/star-filled.ts';
