/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StickyNoteFilledIcon } from '../generated/components/sticky-note-filled.tsx';
export { stickyNoteFilledIconDefinition } from '../generated/definitions/sticky-note-filled.ts';
