/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StreetRoad1FilledIcon } from '../generated/components/street-road-1-filled.tsx';
export { streetRoad1FilledIconDefinition } from '../generated/definitions/street-road-1-filled.ts';
