/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SubtitleIcon } from '../generated/components/subtitle.tsx';
export { subtitleIconDefinition } from '../generated/definitions/subtitle.ts';
