/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SurprisedFilledIcon } from '../generated/components/surprised-filled.tsx';
export { surprisedFilledIconDefinition } from '../generated/definitions/surprised-filled.ts';
