/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemCoordinateIcon } from '../generated/components/system-coordinate.tsx';
export { systemCoordinateIconDefinition } from '../generated/definitions/system-coordinate.ts';
