/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemStorageFilledIcon } from '../generated/components/system-storage-filled.tsx';
export { systemStorageFilledIconDefinition } from '../generated/definitions/system-storage-filled.ts';
