/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemCodeIcon } from '../generated/components/system-code.tsx';
export { systemCodeIconDefinition } from '../generated/definitions/system-code.ts';
