/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemSearchIcon } from '../generated/components/system-search.tsx';
export { systemSearchIconDefinition } from '../generated/definitions/system-search.ts';
