/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemLocationIcon } from '../generated/components/system-location.tsx';
export { systemLocationIconDefinition } from '../generated/definitions/system-location.ts';
