/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemUnlockedIcon } from '../generated/components/system-unlocked.tsx';
export { systemUnlockedIconDefinition } from '../generated/definitions/system-unlocked.ts';
