/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemMarkedFilledIcon } from '../generated/components/system-marked-filled.tsx';
export { systemMarkedFilledIconDefinition } from '../generated/definitions/system-marked-filled.ts';
