/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemLockedFilledIcon } from '../generated/components/system-locked-filled.tsx';
export { systemLockedFilledIconDefinition } from '../generated/definitions/system-locked-filled.ts';
