/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemSettingFilledIcon } from '../generated/components/system-setting-filled.tsx';
export { systemSettingFilledIconDefinition } from '../generated/definitions/system-setting-filled.ts';
