/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TableAddIcon } from '../generated/components/table-add.tsx';
export { tableAddIconDefinition } from '../generated/definitions/table-add.ts';
