/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Table2FilledIcon } from '../generated/components/table-2-filled.tsx';
export { table2FilledIconDefinition } from '../generated/definitions/table-2-filled.ts';
