/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskVisibleIcon } from '../generated/components/task-visible.tsx';
export { taskVisibleIconDefinition } from '../generated/definitions/task-visible.ts';
