/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskVisibleFilledIcon } from '../generated/components/task-visible-filled.tsx';
export { taskVisibleFilledIconDefinition } from '../generated/definitions/task-visible-filled.ts';
