/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Task1FilledIcon } from '../generated/components/task-1-filled.tsx';
export { task1FilledIconDefinition } from '../generated/definitions/task-1-filled.ts';
