/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskMarkedIcon } from '../generated/components/task-marked.tsx';
export { taskMarkedIconDefinition } from '../generated/definitions/task-marked.ts';
