/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TeaIcon } from '../generated/components/tea.tsx';
export { teaIconDefinition } from '../generated/definitions/tea.ts';
