/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TeahouseFilledIcon } from '../generated/components/teahouse-filled.tsx';
export { teahouseFilledIconDefinition } from '../generated/definitions/teahouse-filled.ts';
