/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TerminalRectangleIcon } from '../generated/components/terminal-rectangle.tsx';
export { terminalRectangleIconDefinition } from '../generated/definitions/terminal-rectangle.ts';
