/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TerminalRectangle1Icon } from '../generated/components/terminal-rectangle-1.tsx';
export { terminalRectangle1IconDefinition } from '../generated/definitions/terminal-rectangle-1.ts';
