/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextformatItalicIcon } from '../generated/components/textformat-italic.tsx';
export { textformatItalicIconDefinition } from '../generated/definitions/textformat-italic.ts';
