/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextformatColorIcon } from '../generated/components/textformat-color.tsx';
export { textformatColorIconDefinition } from '../generated/definitions/textformat-color.ts';
