/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextformatStrikethroughIcon } from '../generated/components/textformat-strikethrough.tsx';
export { textformatStrikethroughIconDefinition } from '../generated/definitions/textformat-strikethrough.ts';
