/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbDownIcon } from '../generated/components/thumb-down.tsx';
export { thumbDownIconDefinition } from '../generated/definitions/thumb-down.ts';
