/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThunderstormNightIcon } from '../generated/components/thunderstorm-night.tsx';
export { thunderstormNightIconDefinition } from '../generated/definitions/thunderstorm-night.ts';
