/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThunderstormSunnyIcon } from '../generated/components/thunderstorm-sunny.tsx';
export { thunderstormSunnyIconDefinition } from '../generated/definitions/thunderstorm-sunny.ts';
