/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TicketFilledIcon } from '../generated/components/ticket-filled.tsx';
export { ticketFilledIconDefinition } from '../generated/definitions/ticket-filled.ts';
