/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TomatoIcon } from '../generated/components/tomato.tsx';
export { tomatoIconDefinition } from '../generated/definitions/tomato.ts';
