/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TomatoFilledIcon } from '../generated/components/tomato-filled.tsx';
export { tomatoFilledIconDefinition } from '../generated/definitions/tomato-filled.ts';
