/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ToolsIcon } from '../generated/components/tools.tsx';
export { toolsIconDefinition } from '../generated/definitions/tools.ts';
