/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TornadoIcon } from '../generated/components/tornado.tsx';
export { tornadoIconDefinition } from '../generated/definitions/tornado.ts';
