/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tower3Icon } from '../generated/components/tower-3.tsx';
export { tower3IconDefinition } from '../generated/definitions/tower-3.ts';
