/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tower2FilledIcon } from '../generated/components/tower-2-filled.tsx';
export { tower2FilledIconDefinition } from '../generated/definitions/tower-2-filled.ts';
