/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Transform1Icon } from '../generated/components/transform-1.tsx';
export { transform1IconDefinition } from '../generated/definitions/transform-1.ts';
