/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeCatalogIcon } from '../generated/components/tree-catalog.tsx';
export { treeCatalogIconDefinition } from '../generated/definitions/tree-catalog.ts';
