/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeSquareDotIcon } from '../generated/components/tree-square-dot.tsx';
export { treeSquareDotIconDefinition } from '../generated/definitions/tree-square-dot.ts';
