/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tv2FilledIcon } from '../generated/components/tv-2-filled.tsx';
export { tv2FilledIconDefinition } from '../generated/definitions/tv-2-filled.ts';
