/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TvFilledIcon } from '../generated/components/tv-filled.tsx';
export { tvFilledIconDefinition } from '../generated/definitions/tv-filled.ts';
