/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TypographyFilledIcon } from '../generated/components/typography-filled.tsx';
export { typographyFilledIconDefinition } from '../generated/definitions/typography-filled.ts';
