/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Uncomfortable2FilledIcon } from '../generated/components/uncomfortable-2-filled.tsx';
export { uncomfortable2FilledIconDefinition } from '../generated/definitions/uncomfortable-2-filled.ts';
