/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UncomfortableFilledIcon } from '../generated/components/uncomfortable-filled.tsx';
export { uncomfortableFilledIconDefinition } from '../generated/definitions/uncomfortable-filled.ts';
