/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Uncomfortable1FilledIcon } from '../generated/components/uncomfortable-1-filled.tsx';
export { uncomfortable1FilledIconDefinition } from '../generated/definitions/uncomfortable-1-filled.ts';
