/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeFilledIcon } from '../generated/components/undertake-filled.tsx';
export { undertakeFilledIconDefinition } from '../generated/definitions/undertake-filled.ts';
