/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeEnvironmentProtectionIcon } from '../generated/components/undertake-environment-protection.tsx';
export { undertakeEnvironmentProtectionIconDefinition } from '../generated/definitions/undertake-environment-protection.ts';
