/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Unhappy1Icon } from '../generated/components/unhappy-1.tsx';
export { unhappy1IconDefinition } from '../generated/definitions/unhappy-1.ts';
