/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserSearchFilledIcon } from '../generated/components/user-search-filled.tsx';
export { userSearchFilledIconDefinition } from '../generated/definitions/user-search-filled.ts';
