/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupAddFilledIcon } from '../generated/components/usergroup-add-filled.tsx';
export { usergroupAddFilledIconDefinition } from '../generated/definitions/usergroup-add-filled.ts';
