/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowUpFilledIcon } from '../generated/components/user-arrow-up-filled.tsx';
export { userArrowUpFilledIconDefinition } from '../generated/definitions/user-arrow-up-filled.ts';
