/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserCircleIcon } from '../generated/components/user-circle.tsx';
export { userCircleIconDefinition } from '../generated/definitions/user-circle.ts';
