/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { User1Icon } from '../generated/components/user-1.tsx';
export { user1IconDefinition } from '../generated/definitions/user-1.ts';
