/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserAddFilledIcon } from '../generated/components/user-add-filled.tsx';
export { userAddFilledIconDefinition } from '../generated/definitions/user-add-filled.ts';
