/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserLockedIcon } from '../generated/components/user-locked.tsx';
export { userLockedIconDefinition } from '../generated/definitions/user-locked.ts';
