/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserMarkedFilledIcon } from '../generated/components/user-marked-filled.tsx';
export { userMarkedFilledIconDefinition } from '../generated/definitions/user-marked-filled.ts';
