/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserError1FilledIcon } from '../generated/components/user-error-1-filled.tsx';
export { userError1FilledIconDefinition } from '../generated/definitions/user-error-1-filled.ts';
