/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserCheckedIcon } from '../generated/components/user-checked.tsx';
export { userCheckedIconDefinition } from '../generated/definitions/user-checked.ts';
