/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserUnlockedIcon } from '../generated/components/user-unlocked.tsx';
export { userUnlockedIconDefinition } from '../generated/definitions/user-unlocked.ts';
