/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserBusinessIcon } from '../generated/components/user-business.tsx';
export { userBusinessIconDefinition } from '../generated/definitions/user-business.ts';
