/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserCircleFilledIcon } from '../generated/components/user-circle-filled.tsx';
export { userCircleFilledIconDefinition } from '../generated/definitions/user-circle-filled.ts';
