/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserVisibleIcon } from '../generated/components/user-visible.tsx';
export { userVisibleIconDefinition } from '../generated/definitions/user-visible.ts';
