/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupCircleIcon } from '../generated/components/usergroup-circle.tsx';
export { usergroupCircleIconDefinition } from '../generated/definitions/usergroup-circle.ts';
