/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsercaseLinkFilledIcon } from '../generated/components/usercase-link-filled.tsx';
export { usercaseLinkFilledIconDefinition } from '../generated/definitions/usercase-link-filled.ts';
