/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowLeftIcon } from '../generated/components/user-arrow-left.tsx';
export { userArrowLeftIconDefinition } from '../generated/definitions/user-arrow-left.ts';
