/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserClearFilledIcon } from '../generated/components/user-clear-filled.tsx';
export { userClearFilledIconDefinition } from '../generated/definitions/user-clear-filled.ts';
