/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserTalkFilledIcon } from '../generated/components/user-talk-filled.tsx';
export { userTalkFilledIconDefinition } from '../generated/definitions/user-talk-filled.ts';
