/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupIcon } from '../generated/components/usergroup.tsx';
export { usergroupIconDefinition } from '../generated/definitions/usergroup.ts';
