/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserClearIcon } from '../generated/components/user-clear.tsx';
export { userClearIconDefinition } from '../generated/definitions/user-clear.ts';
