/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowLeftFilledIcon } from '../generated/components/user-arrow-left-filled.tsx';
export { userArrowLeftFilledIconDefinition } from '../generated/definitions/user-arrow-left-filled.ts';
