/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserVipFilledIcon } from '../generated/components/user-vip-filled.tsx';
export { userVipFilledIconDefinition } from '../generated/definitions/user-vip-filled.ts';
