/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VehicleIcon } from '../generated/components/vehicle.tsx';
export { vehicleIconDefinition } from '../generated/definitions/vehicle.ts';
