/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraMinusIcon } from '../generated/components/video-camera-minus.tsx';
export { videoCameraMinusIconDefinition } from '../generated/definitions/video-camera-minus.ts';
