/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraFilledIcon } from '../generated/components/video-camera-filled.tsx';
export { videoCameraFilledIconDefinition } from '../generated/definitions/video-camera-filled.ts';
