/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraOffIcon } from '../generated/components/video-camera-off.tsx';
export { videoCameraOffIconDefinition } from '../generated/definitions/video-camera-off.ts';
