/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCamera1FilledIcon } from '../generated/components/video-camera-1-filled.tsx';
export { videoCamera1FilledIconDefinition } from '../generated/definitions/video-camera-1-filled.ts';
