/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoLibraryIcon } from '../generated/components/video-library.tsx';
export { videoLibraryIconDefinition } from '../generated/definitions/video-library.ts';
