/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewListIcon } from '../generated/components/view-list.tsx';
export { viewListIconDefinition } from '../generated/definitions/view-list.ts';
