/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewAgendaIcon } from '../generated/components/view-agenda.tsx';
export { viewAgendaIconDefinition } from '../generated/definitions/view-agenda.ts';
