/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewModuleFilledIcon } from '../generated/components/view-module-filled.tsx';
export { viewModuleFilledIconDefinition } from '../generated/definitions/view-module-filled.ts';
