/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WatermelonIcon } from '../generated/components/watermelon.tsx';
export { watermelonIconDefinition } from '../generated/definitions/watermelon.ts';
