/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WaveLeftIcon } from '../generated/components/wave-left.tsx';
export { waveLeftIconDefinition } from '../generated/definitions/wave-left.ts';
