/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Wifi1FilledIcon } from '../generated/components/wifi-1-filled.tsx';
export { wifi1FilledIconDefinition } from '../generated/definitions/wifi-1-filled.ts';
