/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Window1FilledIcon } from '../generated/components/window-1-filled.tsx';
export { window1FilledIconDefinition } from '../generated/definitions/window-1-filled.ts';
