/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WindyIcon } from '../generated/components/windy.tsx';
export { windyIconDefinition } from '../generated/definitions/windy.ts';
