/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WinkFilledIcon } from '../generated/components/wink-filled.tsx';
export { winkFilledIconDefinition } from '../generated/definitions/wink-filled.ts';
