/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WinkIcon } from '../generated/components/wink.tsx';
export { winkIconDefinition } from '../generated/definitions/wink.ts';
