/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WrySmileFilledIcon } from '../generated/components/wry-smile-filled.tsx';
export { wrySmileFilledIconDefinition } from '../generated/definitions/wry-smile-filled.ts';
