/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ZoomOutIcon } from '../generated/components/zoom-out.tsx';
export { zoomOutIconDefinition } from '../generated/definitions/zoom-out.ts';
