import { internalPrimitives } from '../primitives';

export const lightTheme = {
  '--ui-color-canvas': internalPrimitives.color.neutralCanvas,
  '--ui-color-surface': internalPrimitives.color.neutralSurface,
  '--ui-color-text': internalPrimitives.color.neutralInk,
  '--ui-color-text-muted': internalPrimitives.color.neutralInkMuted,
  '--ui-color-border': internalPrimitives.color.borderSoft,
  '--ui-color-border-strong': internalPrimitives.color.borderStrong,
  '--ui-color-brand-bg': internalPrimitives.color.brandAmber,
  '--ui-color-brand-bg-hover': internalPrimitives.color.brandAmberHover,
  '--ui-color-brand-bg-active': internalPrimitives.color.brandAmberActive,
  '--ui-color-text-on-brand': internalPrimitives.color.brandText,
  '--ui-color-focus-ring': internalPrimitives.color.focusRing,
  '--ui-color-link': internalPrimitives.color.link,
  '--ui-radius-md': internalPrimitives.radius.md,
  '--ui-shadow-soft': internalPrimitives.shadow.soft,
  '--ui-font-body': internalPrimitives.font.body,
  '--ui-font-display': internalPrimitives.font.display,
  '--ui-font-mono': internalPrimitives.font.mono,
  '--ui-font-weight-body': internalPrimitives.font.weights.body,
  '--ui-font-weight-emphasis': internalPrimitives.font.weights.emphasis,
  '--ui-font-weight-title': internalPrimitives.font.weights.title,
  '--ui-font-weight-strong': internalPrimitives.font.weights.strong,
} as const;

export const darkTheme = {
  ...lightTheme,
  '--ui-color-canvas': '#000000',
  '--ui-color-surface': '#0f1311',
  '--ui-color-text': '#edf3ef',
  '--ui-color-text-muted': '#b8c6be',
  '--ui-color-border': '#38443f',
  '--ui-color-border-strong': '#5a6c64',
  '--ui-color-brand-bg': '#729b89',
  '--ui-color-brand-bg-hover': '#85ad9c',
  '--ui-color-brand-bg-active': '#5e8574',
  '--ui-color-text-on-brand': '#f7fbf8',
  '--ui-color-focus-ring': '#9ec8b4',
  '--ui-color-link': '#b6e2cc',
  '--ui-shadow-soft': '0 18px 40px rgba(0, 0, 0, 0.34)',
} as const;
