import { createRequire } from 'node:module';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const packageRoot = resolve(import.meta.dirname, '..');
const packageJsonPath = resolve(packageRoot, 'package.json');
const srcDir = resolve(packageRoot, 'src');
const exportsDir = resolve(srcDir, 'exports');
const require = createRequire(import.meta.url);
const tdesignIconsPackageJson = require.resolve('tdesign-icons-svg/package.json');
const sourceDir = resolve(tdesignIconsPackageJson, '..', 'src');
const generatedDir = resolve(packageRoot, 'src/generated');
const definitionsDir = resolve(generatedDir, 'definitions');
const componentsDir = resolve(generatedDir, 'components');

const svgFiles = readdirSync(sourceDir)
  .filter((file) => file.endsWith('.svg'))
  .sort((left, right) => left.localeCompare(right));

const toPascalCase = (value) => {
  const parts = value.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  const pascal = parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');

  if (!/^[A-Za-z]/.test(pascal)) {
    return `Icon${pascal}`;
  }

  return pascal;
};

const toCamelCase = (value) => {
  const pascal = toPascalCase(value);

  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

const normalizeSvg = (rawSvg, sourceKey) => {
  const viewBoxMatch = rawSvg.match(/view-box="([^"]+)"/i) ?? rawSvg.match(/viewBox="([^"]+)"/i);
  const viewBox = viewBoxMatch?.[1] ?? '0 0 24 24';
  const body = rawSvg
    .replace(/<svg\b[^>]*>/i, '')
    .replace(/<\/svg>\s*$/i, '')
    .trim();

  return {
    body,
    sourceKey,
    viewBox,
  };
};

const entries = svgFiles.map((file) => {
  const iconName = file.replace(/\.svg$/, '');
  const baseName = toPascalCase(iconName);

  return {
    componentName: `${baseName}Icon`,
    definitionName: `${toCamelCase(iconName)}IconDefinition`,
    displayName: `${baseName}Icon`,
    exportName: `${baseName}Icon`,
    iconName,
    normalized: normalizeSvg(readFileSync(join(sourceDir, file), 'utf8'), iconName),
  };
});

const generatedNameUnion = entries.map((entry) => JSON.stringify(entry.iconName)).join(' | ');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));

const iconNamesSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export type GeneratedIconName = ${generatedNameUnion};

export const iconNames = [
${entries.map((entry) => `  ${JSON.stringify(entry.iconName)},`).join('\n')}
] as const satisfies readonly GeneratedIconName[];

const iconNameSet = new Set<string>(iconNames);

export const hasIconName = (name: string): name is GeneratedIconName => {
  return iconNameSet.has(name);
};
`;

const iconLoadersSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

import type { IconDefinition } from '../icon/types';
import type { GeneratedIconName } from './icon-names';

export const iconLoaders: Record<GeneratedIconName, () => Promise<IconDefinition>> = {
${entries
  .map((entry) => {
    return `  ${JSON.stringify(entry.iconName)}: async () => {
    const module = await import('../exports/${entry.iconName}.ts');

    return module.${entry.definitionName};
  },`;
  })
  .join('\n')}
};

export const loadIconDefinition = (name: GeneratedIconName) => {
  return iconLoaders[name]();
};
`;

const componentIndexSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

${entries.map((entry) => `export { ${entry.componentName} } from './${entry.iconName}.tsx';`).join('\n')}
`;

const componentSharedSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

import type { SharedIconProps } from '../../icon/types';

export type NamedIconProps = SharedIconProps;
`;

const definitionsIndexSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

${entries
  .map((entry) => `export { ${entry.definitionName} } from './${entry.iconName}.ts';`)
  .join('\n')}
`;

rmSync(generatedDir, { force: true, recursive: true });
for (const existingFile of readdirSync(srcDir)) {
  if (!existingFile.endsWith('.ts')) {
    continue;
  }

  if (existingFile === 'index.ts' || existingFile === 'modules.d.ts') {
    continue;
  }

  rmSync(join(srcDir, existingFile), { force: true });
}

rmSync(exportsDir, { force: true, recursive: true });
mkdirSync(definitionsDir, { recursive: true });
mkdirSync(componentsDir, { recursive: true });
mkdirSync(exportsDir, { recursive: true });

for (const entry of entries) {
  const definitionSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

import type { IconDefinition } from '../../icon/types';

export const ${entry.definitionName} = ${JSON.stringify(entry.normalized, null, 2)} as const satisfies IconDefinition;
`;

  const componentSource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

import type { ReactElement } from 'react';

import { BaseIcon } from '../../icon/base-icon';
import type { NamedIconProps } from './shared.ts';
import { ${entry.definitionName} } from '../definitions/${entry.iconName}.ts';

export const ${entry.componentName} = (props: NamedIconProps): ReactElement => {
  return <BaseIcon {...props} definition={${entry.definitionName}} name=${JSON.stringify(entry.iconName)} />;
};

${entry.componentName}.displayName = ${JSON.stringify(entry.displayName)};
`;

  const publicEntrySource = `/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ${entry.componentName} } from '../generated/components/${entry.iconName}.tsx';
export { ${entry.definitionName} } from '../generated/definitions/${entry.iconName}.ts';
`;

  writeFileSync(join(definitionsDir, `${entry.iconName}.ts`), definitionSource);
  writeFileSync(join(componentsDir, `${entry.iconName}.tsx`), componentSource);
  writeFileSync(join(exportsDir, `${entry.iconName}.ts`), publicEntrySource);
}

writeFileSync(join(generatedDir, 'icon-loaders.ts'), iconLoadersSource);
writeFileSync(join(generatedDir, 'icon-names.ts'), iconNamesSource);
writeFileSync(join(definitionsDir, 'index.ts'), definitionsIndexSource);
writeFileSync(join(componentsDir, 'index.ts'), componentIndexSource);
writeFileSync(join(componentsDir, 'shared.ts'), componentSharedSource);

packageJson.exports = {
  '.': {
    types: './src/index.ts',
    import: './dist/index.mjs',
    default: './dist/index.mjs',
  },
  './package.json': './package.json',
  ...Object.fromEntries(
    entries.map((entry) => [
      `./${entry.iconName}`,
      {
        types: `./src/exports/${entry.iconName}.ts`,
        import: `./dist/icons/${entry.iconName}.mjs`,
        default: `./dist/icons/${entry.iconName}.mjs`,
      },
    ]),
  ),
};

writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

console.log(`Generated ${entries.length} icons.`);
