/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AccessibilityFilledIcon } from '../generated/components/accessibility-filled.tsx';
export { accessibilityFilledIconDefinition } from '../generated/definitions/accessibility-filled.ts';
