/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ActivityIcon } from '../generated/components/activity.tsx';
export { activityIconDefinition } from '../generated/definitions/activity.ts';
