/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ActivityFilledIcon } from '../generated/components/activity-filled.tsx';
export { activityFilledIconDefinition } from '../generated/definitions/activity-filled.ts';
