/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AddCircleIcon } from '../generated/components/add-circle.tsx';
export { addCircleIconDefinition } from '../generated/definitions/add-circle.ts';
