/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AddCircleFilledIcon } from '../generated/components/add-circle-filled.tsx';
export { addCircleFilledIconDefinition } from '../generated/definitions/add-circle-filled.ts';
