/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AddIcon } from '../generated/components/add.tsx';
export { addIconDefinition } from '../generated/definitions/add.ts';
