/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AddressBookFilledIcon } from '../generated/components/address-book-filled.tsx';
export { addressBookFilledIconDefinition } from '../generated/definitions/address-book-filled.ts';
