/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiArticleFilledIcon } from '../generated/components/ai-article-filled.tsx';
export { aiArticleFilledIconDefinition } from '../generated/definitions/ai-article-filled.ts';
