/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiCoordinateSystemFilledIcon } from '../generated/components/ai-coordinate-system-filled.tsx';
export { aiCoordinateSystemFilledIconDefinition } from '../generated/definitions/ai-coordinate-system-filled.ts';
