/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiEdit1FilledIcon } from '../generated/components/ai-edit-1-filled.tsx';
export { aiEdit1FilledIconDefinition } from '../generated/definitions/ai-edit-1-filled.ts';
