/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiGitBranchIcon } from '../generated/components/ai-git-branch.tsx';
export { aiGitBranchIconDefinition } from '../generated/definitions/ai-git-branch.ts';
