/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiLayoutFilledIcon } from '../generated/components/ai-layout-filled.tsx';
export { aiLayoutFilledIconDefinition } from '../generated/definitions/ai-layout-filled.ts';
