/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiLayoutIcon } from '../generated/components/ai-layout.tsx';
export { aiLayoutIconDefinition } from '../generated/definitions/ai-layout.ts';
