/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiMusicFilledIcon } from '../generated/components/ai-music-filled.tsx';
export { aiMusicFilledIconDefinition } from '../generated/definitions/ai-music-filled.ts';
