/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiSearchIcon } from '../generated/components/ai-search.tsx';
export { aiSearchIconDefinition } from '../generated/definitions/ai-search.ts';
