/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiToolIcon } from '../generated/components/ai-tool.tsx';
export { aiToolIconDefinition } from '../generated/definitions/ai-tool.ts';
