/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiTerminalIcon } from '../generated/components/ai-terminal.tsx';
export { aiTerminalIconDefinition } from '../generated/definitions/ai-terminal.ts';
