/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiTextformatItalicIcon } from '../generated/components/ai-textformat-italic.tsx';
export { aiTextformatItalicIconDefinition } from '../generated/definitions/ai-textformat-italic.ts';
