/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiTerminalFilledIcon } from '../generated/components/ai-terminal-filled.tsx';
export { aiTerminalFilledIconDefinition } from '../generated/definitions/ai-terminal-filled.ts';
