/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiVideoIcon } from '../generated/components/ai-video.tsx';
export { aiVideoIconDefinition } from '../generated/definitions/ai-video.ts';
