/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AiIcon } from '../generated/components/ai.tsx';
export { aiIconDefinition } from '../generated/definitions/ai.ts';
