/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AlarmAddIcon } from '../generated/components/alarm-add.tsx';
export { alarmAddIconDefinition } from '../generated/definitions/alarm-add.ts';
