/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AlignVerticalIcon } from '../generated/components/align-vertical.tsx';
export { alignVerticalIconDefinition } from '../generated/definitions/align-vertical.ts';
