/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AlphaIcon } from '../generated/components/alpha.tsx';
export { alphaIconDefinition } from '../generated/definitions/alpha.ts';
