/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AnchorIcon } from '../generated/components/anchor.tsx';
export { anchorIconDefinition } from '../generated/definitions/anchor.ts';
