/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AngryFilledIcon } from '../generated/components/angry-filled.tsx';
export { angryFilledIconDefinition } from '../generated/definitions/angry-filled.ts';
