/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Animation1Icon } from '../generated/components/animation-1.tsx';
export { animation1IconDefinition } from '../generated/definitions/animation-1.ts';
