/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AnimationIcon } from '../generated/components/animation.tsx';
export { animationIconDefinition } from '../generated/definitions/animation.ts';
