/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AppIcon } from '../generated/components/app.tsx';
export { appIconDefinition } from '../generated/definitions/app.ts';
