/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AppleIcon } from '../generated/components/apple.tsx';
export { appleIconDefinition } from '../generated/definitions/apple.ts';
