/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AppleFilledIcon } from '../generated/components/apple-filled.tsx';
export { appleFilledIconDefinition } from '../generated/definitions/apple-filled.ts';
