/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Archway1FilledIcon } from '../generated/components/archway-1-filled.tsx';
export { archway1FilledIconDefinition } from '../generated/definitions/archway-1-filled.ts';
