/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArchwayFilledIcon } from '../generated/components/archway-filled.tsx';
export { archwayFilledIconDefinition } from '../generated/definitions/archway-filled.ts';
