/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Archway1Icon } from '../generated/components/archway-1.tsx';
export { archway1IconDefinition } from '../generated/definitions/archway-1.ts';
