/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowTriangleDownIcon } from '../generated/components/arrow-triangle-down.tsx';
export { arrowTriangleDownIconDefinition } from '../generated/definitions/arrow-triangle-down.ts';
