/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftUpIcon } from '../generated/components/arrow-left-up.tsx';
export { arrowLeftUpIconDefinition } from '../generated/definitions/arrow-left-up.ts';
