/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightDownCircleFilledIcon } from '../generated/components/arrow-right-down-circle-filled.tsx';
export { arrowRightDownCircleFilledIconDefinition } from '../generated/definitions/arrow-right-down-circle-filled.ts';
