/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftRightCircleIcon } from '../generated/components/arrow-left-right-circle.tsx';
export { arrowLeftRightCircleIconDefinition } from '../generated/definitions/arrow-left-right-circle.ts';
