/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightDownCircleIcon } from '../generated/components/arrow-right-down-circle.tsx';
export { arrowRightDownCircleIconDefinition } from '../generated/definitions/arrow-right-down-circle.ts';
