/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftDownCircleIcon } from '../generated/components/arrow-left-down-circle.tsx';
export { arrowLeftDownCircleIconDefinition } from '../generated/definitions/arrow-left-down-circle.ts';
