/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpDown2Icon } from '../generated/components/arrow-up-down-2.tsx';
export { arrowUpDown2IconDefinition } from '../generated/definitions/arrow-up-down-2.ts';
