/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpCircleIcon } from '../generated/components/arrow-up-circle.tsx';
export { arrowUpCircleIconDefinition } from '../generated/definitions/arrow-up-circle.ts';
