/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightIcon } from '../generated/components/arrow-right.tsx';
export { arrowRightIconDefinition } from '../generated/definitions/arrow-right.ts';
