/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowUpDownCircleFilledIcon } from '../generated/components/arrow-up-down-circle-filled.tsx';
export { arrowUpDownCircleFilledIconDefinition } from '../generated/definitions/arrow-up-down-circle-filled.ts';
