/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftRight2Icon } from '../generated/components/arrow-left-right-2.tsx';
export { arrowLeftRight2IconDefinition } from '../generated/definitions/arrow-left-right-2.ts';
