/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftRightCircleFilledIcon } from '../generated/components/arrow-left-right-circle-filled.tsx';
export { arrowLeftRightCircleFilledIconDefinition } from '../generated/definitions/arrow-left-right-circle-filled.ts';
