/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowDownRectangleIcon } from '../generated/components/arrow-down-rectangle.tsx';
export { arrowDownRectangleIconDefinition } from '../generated/definitions/arrow-down-rectangle.ts';
