/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightUpCircleIcon } from '../generated/components/arrow-right-up-circle.tsx';
export { arrowRightUpCircleIconDefinition } from '../generated/definitions/arrow-right-up-circle.ts';
