/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightCircleIcon } from '../generated/components/arrow-right-circle.tsx';
export { arrowRightCircleIconDefinition } from '../generated/definitions/arrow-right-circle.ts';
