/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftUpCircleIcon } from '../generated/components/arrow-left-up-circle.tsx';
export { arrowLeftUpCircleIconDefinition } from '../generated/definitions/arrow-left-up-circle.ts';
