/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowLeftCircleIcon } from '../generated/components/arrow-left-circle.tsx';
export { arrowLeftCircleIconDefinition } from '../generated/definitions/arrow-left-circle.ts';
