/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowTriangleUpFilledIcon } from '../generated/components/arrow-triangle-up-filled.tsx';
export { arrowTriangleUpFilledIconDefinition } from '../generated/definitions/arrow-triangle-up-filled.ts';
