/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArrowRightUpIcon } from '../generated/components/arrow-right-up.tsx';
export { arrowRightUpIconDefinition } from '../generated/definitions/arrow-right-up.ts';
