/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArtboardIcon } from '../generated/components/artboard.tsx';
export { artboardIconDefinition } from '../generated/definitions/artboard.ts';
