/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ArticleFilledIcon } from '../generated/components/article-filled.tsx';
export { articleFilledIconDefinition } from '../generated/definitions/article-filled.ts';
