/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentCodeIcon } from '../generated/components/assignment-code.tsx';
export { assignmentCodeIconDefinition } from '../generated/definitions/assignment-code.ts';
