/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentUserIcon } from '../generated/components/assignment-user.tsx';
export { assignmentUserIconDefinition } from '../generated/definitions/assignment-user.ts';
