/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentCheckedFilledIcon } from '../generated/components/assignment-checked-filled.tsx';
export { assignmentCheckedFilledIconDefinition } from '../generated/definitions/assignment-checked-filled.ts';
