/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentCodeFilledIcon } from '../generated/components/assignment-code-filled.tsx';
export { assignmentCodeFilledIconDefinition } from '../generated/definitions/assignment-code-filled.ts';
