/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AssignmentErrorIcon } from '../generated/components/assignment-error.tsx';
export { assignmentErrorIconDefinition } from '../generated/definitions/assignment-error.ts';
