/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AutomationFilledIcon } from '../generated/components/automation-filled.tsx';
export { automationFilledIconDefinition } from '../generated/definitions/automation-filled.ts';
