/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { AutomaticNumberingIcon } from '../generated/components/automatic-numbering.tsx';
export { automaticNumberingIconDefinition } from '../generated/definitions/automatic-numbering.ts';
