/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BackwardIcon } from '../generated/components/backward.tsx';
export { backwardIconDefinition } from '../generated/definitions/backward.ts';
