/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BackupIcon } from '../generated/components/backup.tsx';
export { backupIconDefinition } from '../generated/definitions/backup.ts';
