/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BadLaughIcon } from '../generated/components/bad-laugh.tsx';
export { badLaughIconDefinition } from '../generated/definitions/bad-laugh.ts';
