/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BananaFilledIcon } from '../generated/components/banana-filled.tsx';
export { bananaFilledIconDefinition } from '../generated/definitions/banana-filled.ts';
