/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BarbecueIcon } from '../generated/components/barbecue.tsx';
export { barbecueIconDefinition } from '../generated/definitions/barbecue.ts';
