/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BarcodeIcon } from '../generated/components/barcode.tsx';
export { barcodeIconDefinition } from '../generated/definitions/barcode.ts';
