/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BaseStationIcon } from '../generated/components/base-station.tsx';
export { baseStationIconDefinition } from '../generated/definitions/base-station.ts';
