/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BatteryChargingFilledIcon } from '../generated/components/battery-charging-filled.tsx';
export { batteryChargingFilledIconDefinition } from '../generated/definitions/battery-charging-filled.ts';
