/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BatteryIcon } from '../generated/components/battery.tsx';
export { batteryIconDefinition } from '../generated/definitions/battery.ts';
