/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BatteryChargingIcon } from '../generated/components/battery-charging.tsx';
export { batteryChargingIconDefinition } from '../generated/definitions/battery-charging.ts';
