/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BatteryAddFilledIcon } from '../generated/components/battery-add-filled.tsx';
export { batteryAddFilledIconDefinition } from '../generated/definitions/battery-add-filled.ts';
