/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BeanIcon } from '../generated/components/bean.tsx';
export { beanIconDefinition } from '../generated/definitions/bean.ts';
