/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BetaIcon } from '../generated/components/beta.tsx';
export { betaIconDefinition } from '../generated/definitions/beta.ts';
