/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BifurcateFilledIcon } from '../generated/components/bifurcate-filled.tsx';
export { bifurcateFilledIconDefinition } from '../generated/definitions/bifurcate-filled.ts';
