/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BillFilledIcon } from '../generated/components/bill-filled.tsx';
export { billFilledIconDefinition } from '../generated/definitions/bill-filled.ts';
