/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BluetoothIcon } from '../generated/components/bluetooth.tsx';
export { bluetoothIconDefinition } from '../generated/definitions/bluetooth.ts';
