/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BoneFilledIcon } from '../generated/components/bone-filled.tsx';
export { boneFilledIconDefinition } from '../generated/definitions/bone-filled.ts';
