/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookIcon } from '../generated/components/book.tsx';
export { bookIconDefinition } from '../generated/definitions/book.ts';
