/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkMinusFilledIcon } from '../generated/components/bookmark-minus-filled.tsx';
export { bookmarkMinusFilledIconDefinition } from '../generated/definitions/bookmark-minus-filled.ts';
