/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkIcon } from '../generated/components/bookmark.tsx';
export { bookmarkIconDefinition } from '../generated/definitions/bookmark.ts';
