/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookFilledIcon } from '../generated/components/book-filled.tsx';
export { bookFilledIconDefinition } from '../generated/definitions/book-filled.ts';
