/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookmarkAddIcon } from '../generated/components/bookmark-add.tsx';
export { bookmarkAddIconDefinition } from '../generated/definitions/bookmark-add.ts';
