/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BookOpenFilledIcon } from '../generated/components/book-open-filled.tsx';
export { bookOpenFilledIconDefinition } from '../generated/definitions/book-open-filled.ts';
