/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BracesIcon } from '../generated/components/braces.tsx';
export { bracesIconDefinition } from '../generated/definitions/braces.ts';
