/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BreadIcon } from '../generated/components/bread.tsx';
export { breadIconDefinition } from '../generated/definitions/bread.ts';
