/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Bridge6Icon } from '../generated/components/bridge-6.tsx';
export { bridge6IconDefinition } from '../generated/definitions/bridge-6.ts';
