/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BridgeIcon } from '../generated/components/bridge.tsx';
export { bridgeIconDefinition } from '../generated/definitions/bridge.ts';
