/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrightnessIcon } from '../generated/components/brightness.tsx';
export { brightnessIconDefinition } from '../generated/definitions/brightness.ts';
