/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Brightness1Icon } from '../generated/components/brightness-1.tsx';
export { brightness1IconDefinition } from '../generated/definitions/brightness-1.ts';
