/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BroccoliFilledIcon } from '../generated/components/broccoli-filled.tsx';
export { broccoliFilledIconDefinition } from '../generated/definitions/broccoli-filled.ts';
