/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseOffFilledIcon } from '../generated/components/browse-off-filled.tsx';
export { browseOffFilledIconDefinition } from '../generated/definitions/browse-off-filled.ts';
