/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseGalleryFilledIcon } from '../generated/components/browse-gallery-filled.tsx';
export { browseGalleryFilledIconDefinition } from '../generated/definitions/browse-gallery-filled.ts';
