/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseGalleryIcon } from '../generated/components/browse-gallery.tsx';
export { browseGalleryIconDefinition } from '../generated/definitions/browse-gallery.ts';
