/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseOffIcon } from '../generated/components/browse-off.tsx';
export { browseOffIconDefinition } from '../generated/definitions/browse-off.ts';
