/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrowseIcon } from '../generated/components/browse.tsx';
export { browseIconDefinition } from '../generated/definitions/browse.ts';
