/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BrushIcon } from '../generated/components/brush.tsx';
export { brushIconDefinition } from '../generated/definitions/brush.ts';
