/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BugIcon } from '../generated/components/bug.tsx';
export { bugIconDefinition } from '../generated/definitions/bug.ts';
