/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building5FilledIcon } from '../generated/components/building-5-filled.tsx';
export { building5FilledIconDefinition } from '../generated/definitions/building-5-filled.ts';
