/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BuildingFilledIcon } from '../generated/components/building-filled.tsx';
export { buildingFilledIconDefinition } from '../generated/definitions/building-filled.ts';
