/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building3Icon } from '../generated/components/building-3.tsx';
export { building3IconDefinition } from '../generated/definitions/building-3.ts';
