/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Building1FilledIcon } from '../generated/components/building-1-filled.tsx';
export { building1FilledIconDefinition } from '../generated/definitions/building-1-filled.ts';
