/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BuildingIcon } from '../generated/components/building.tsx';
export { buildingIconDefinition } from '../generated/definitions/building.ts';
