/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { BulletpointIcon } from '../generated/components/bulletpoint.tsx';
export { bulletpointIconDefinition } from '../generated/definitions/bulletpoint.ts';
