/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ButtonIcon } from '../generated/components/button.tsx';
export { buttonIconDefinition } from '../generated/definitions/button.ts';
