/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CabbageFilledIcon } from '../generated/components/cabbage-filled.tsx';
export { cabbageFilledIconDefinition } from '../generated/definitions/cabbage-filled.ts';
