/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CakeFilledIcon } from '../generated/components/cake-filled.tsx';
export { cakeFilledIconDefinition } from '../generated/definitions/cake-filled.ts';
