/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalculatorIcon } from '../generated/components/calculator.tsx';
export { calculatorIconDefinition } from '../generated/definitions/calculator.ts';
