/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalendarEventIcon } from '../generated/components/calendar-event.tsx';
export { calendarEventIconDefinition } from '../generated/definitions/calendar-event.ts';
