/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalendarIcon } from '../generated/components/calendar.tsx';
export { calendarIconDefinition } from '../generated/definitions/calendar.ts';
