/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalendarEditIcon } from '../generated/components/calendar-edit.tsx';
export { calendarEditIconDefinition } from '../generated/definitions/calendar-edit.ts';
