/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallForwardedFilledIcon } from '../generated/components/call-forwarded-filled.tsx';
export { callForwardedFilledIconDefinition } from '../generated/definitions/call-forwarded-filled.ts';
