/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallOffIcon } from '../generated/components/call-off.tsx';
export { callOffIconDefinition } from '../generated/definitions/call-off.ts';
