/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallIcon } from '../generated/components/call.tsx';
export { callIconDefinition } from '../generated/definitions/call.ts';
