/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallFilledIcon } from '../generated/components/call-filled.tsx';
export { callFilledIconDefinition } from '../generated/definitions/call-filled.ts';
