/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallCancelIcon } from '../generated/components/call-cancel.tsx';
export { callCancelIconDefinition } from '../generated/definitions/call-cancel.ts';
