/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CallIncomingFilledIcon } from '../generated/components/call-incoming-filled.tsx';
export { callIncomingFilledIconDefinition } from '../generated/definitions/call-incoming-filled.ts';
