/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Calm1Icon } from '../generated/components/calm-1.tsx';
export { calm1IconDefinition } from '../generated/definitions/calm-1.ts';
