/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CalmFilledIcon } from '../generated/components/calm-filled.tsx';
export { calmFilledIconDefinition } from '../generated/definitions/calm-filled.ts';
