/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Camera1Icon } from '../generated/components/camera-1.tsx';
export { camera1IconDefinition } from '../generated/definitions/camera-1.ts';
