/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CameraOffFilledIcon } from '../generated/components/camera-off-filled.tsx';
export { cameraOffFilledIconDefinition } from '../generated/definitions/camera-off-filled.ts';
