/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Camera2FilledIcon } from '../generated/components/camera-2-filled.tsx';
export { camera2FilledIconDefinition } from '../generated/definitions/camera-2-filled.ts';
