/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CandyIcon } from '../generated/components/candy.tsx';
export { candyIconDefinition } from '../generated/definitions/candy.ts';
