/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CardIcon } from '../generated/components/card.tsx';
export { cardIconDefinition } from '../generated/definitions/card.ts';
