/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretRightSmallIcon } from '../generated/components/caret-right-small.tsx';
export { caretRightSmallIconDefinition } from '../generated/definitions/caret-right-small.ts';
