/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretLeftSmallIcon } from '../generated/components/caret-left-small.tsx';
export { caretLeftSmallIconDefinition } from '../generated/definitions/caret-left-small.ts';
