/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretRightIcon } from '../generated/components/caret-right.tsx';
export { caretRightIconDefinition } from '../generated/definitions/caret-right.ts';
