/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretLeftIcon } from '../generated/components/caret-left.tsx';
export { caretLeftIconDefinition } from '../generated/definitions/caret-left.ts';
