/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CaretUpSmallIcon } from '../generated/components/caret-up-small.tsx';
export { caretUpSmallIconDefinition } from '../generated/definitions/caret-up-small.ts';
