/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CartAddFilledIcon } from '../generated/components/cart-add-filled.tsx';
export { cartAddFilledIconDefinition } from '../generated/definitions/cart-add-filled.ts';
