/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CartIcon } from '../generated/components/cart.tsx';
export { cartIconDefinition } from '../generated/definitions/cart.ts';
