/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle1Icon } from '../generated/components/castle-1.tsx';
export { castle1IconDefinition } from '../generated/definitions/castle-1.ts';
