/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle3FilledIcon } from '../generated/components/castle-3-filled.tsx';
export { castle3FilledIconDefinition } from '../generated/definitions/castle-3-filled.ts';
