/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle4FilledIcon } from '../generated/components/castle-4-filled.tsx';
export { castle4FilledIconDefinition } from '../generated/definitions/castle-4-filled.ts';
