/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle2FilledIcon } from '../generated/components/castle-2-filled.tsx';
export { castle2FilledIconDefinition } from '../generated/definitions/castle-2-filled.ts';
