/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle7FilledIcon } from '../generated/components/castle-7-filled.tsx';
export { castle7FilledIconDefinition } from '../generated/definitions/castle-7-filled.ts';
