/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle6FilledIcon } from '../generated/components/castle-6-filled.tsx';
export { castle6FilledIconDefinition } from '../generated/definitions/castle-6-filled.ts';
