/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Castle7Icon } from '../generated/components/castle-7.tsx';
export { castle7IconDefinition } from '../generated/definitions/castle-7.ts';
