/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CatFilledIcon } from '../generated/components/cat-filled.tsx';
export { catFilledIconDefinition } from '../generated/definitions/cat-filled.ts';
