/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CatIcon } from '../generated/components/cat.tsx';
export { catIconDefinition } from '../generated/definitions/cat.ts';
