/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CatalogFilledIcon } from '../generated/components/catalog-filled.tsx';
export { catalogFilledIconDefinition } from '../generated/definitions/catalog-filled.ts';
