/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CenterFocusStrongFilledIcon } from '../generated/components/center-focus-strong-filled.tsx';
export { centerFocusStrongFilledIconDefinition } from '../generated/definitions/center-focus-strong-filled.ts';
