/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CentimeterIcon } from '../generated/components/centimeter.tsx';
export { centimeterIconDefinition } from '../generated/definitions/centimeter.ts';
