/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Certificate1FilledIcon } from '../generated/components/certificate-1-filled.tsx';
export { certificate1FilledIconDefinition } from '../generated/definitions/certificate-1-filled.ts';
