/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartAnalyticsIcon } from '../generated/components/chart-analytics.tsx';
export { chartAnalyticsIconDefinition } from '../generated/definitions/chart-analytics.ts';
