/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartAddFilledIcon } from '../generated/components/chart-add-filled.tsx';
export { chartAddFilledIconDefinition } from '../generated/definitions/chart-add-filled.ts';
