/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartScatterIcon } from '../generated/components/chart-scatter.tsx';
export { chartScatterIconDefinition } from '../generated/definitions/chart-scatter.ts';
