/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRing1FilledIcon } from '../generated/components/chart-ring-1-filled.tsx';
export { chartRing1FilledIconDefinition } from '../generated/definitions/chart-ring-1-filled.ts';
