/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartComboFilledIcon } from '../generated/components/chart-combo-filled.tsx';
export { chartComboFilledIconDefinition } from '../generated/definitions/chart-combo-filled.ts';
