/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRingFilledIcon } from '../generated/components/chart-ring-filled.tsx';
export { chartRingFilledIconDefinition } from '../generated/definitions/chart-ring-filled.ts';
