/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartBubbleFilledIcon } from '../generated/components/chart-bubble-filled.tsx';
export { chartBubbleFilledIconDefinition } from '../generated/definitions/chart-bubble-filled.ts';
