/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartStackedIcon } from '../generated/components/chart-stacked.tsx';
export { chartStackedIconDefinition } from '../generated/definitions/chart-stacked.ts';
