/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartMedianIcon } from '../generated/components/chart-median.tsx';
export { chartMedianIconDefinition } from '../generated/definitions/chart-median.ts';
