/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRingIcon } from '../generated/components/chart-ring.tsx';
export { chartRingIconDefinition } from '../generated/definitions/chart-ring.ts';
