/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartRadarIcon } from '../generated/components/chart-radar.tsx';
export { chartRadarIconDefinition } from '../generated/definitions/chart-radar.ts';
