/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartLineDataIcon } from '../generated/components/chart-line-data.tsx';
export { chartLineDataIconDefinition } from '../generated/definitions/chart-line-data.ts';
