/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Chart3dIcon } from '../generated/components/chart-3d.tsx';
export { chart3dIconDefinition } from '../generated/definitions/chart-3d.ts';
