/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartColumnIcon } from '../generated/components/chart-column.tsx';
export { chartColumnIconDefinition } from '../generated/definitions/chart-column.ts';
