/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartLineData1Icon } from '../generated/components/chart-line-data-1.tsx';
export { chartLineData1IconDefinition } from '../generated/definitions/chart-line-data-1.ts';
