/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartAreaIcon } from '../generated/components/chart-area.tsx';
export { chartAreaIconDefinition } from '../generated/definitions/chart-area.ts';
