/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartColumnFilledIcon } from '../generated/components/chart-column-filled.tsx';
export { chartColumnFilledIconDefinition } from '../generated/definitions/chart-column-filled.ts';
