/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartDrawIoFilledIcon } from '../generated/components/chart-draw-io-filled.tsx';
export { chartDrawIoFilledIconDefinition } from '../generated/definitions/chart-draw-io-filled.ts';
