/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartMaximumIcon } from '../generated/components/chart-maximum.tsx';
export { chartMaximumIconDefinition } from '../generated/definitions/chart-maximum.ts';
