/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Chart3dFilledIcon } from '../generated/components/chart-3d-filled.tsx';
export { chart3dFilledIconDefinition } from '../generated/definitions/chart-3d-filled.ts';
