/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChartBubbleIcon } from '../generated/components/chart-bubble.tsx';
export { chartBubbleIconDefinition } from '../generated/definitions/chart-bubble.ts';
