/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatAddFilledIcon } from '../generated/components/chat-add-filled.tsx';
export { chatAddFilledIconDefinition } from '../generated/definitions/chat-add-filled.ts';
