/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatIcon } from '../generated/components/chat.tsx';
export { chatIconDefinition } from '../generated/definitions/chat.ts';
