/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatOffIcon } from '../generated/components/chat-off.tsx';
export { chatOffIconDefinition } from '../generated/definitions/chat-off.ts';
