/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatSettingIcon } from '../generated/components/chat-setting.tsx';
export { chatSettingIconDefinition } from '../generated/definitions/chat-setting.ts';
