/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatHeartFilledIcon } from '../generated/components/chat-heart-filled.tsx';
export { chatHeartFilledIconDefinition } from '../generated/definitions/chat-heart-filled.ts';
