/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatDoubleFilledIcon } from '../generated/components/chat-double-filled.tsx';
export { chatDoubleFilledIconDefinition } from '../generated/definitions/chat-double-filled.ts';
