/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubble1Icon } from '../generated/components/chat-bubble-1.tsx';
export { chatBubble1IconDefinition } from '../generated/definitions/chat-bubble-1.ts';
