/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatCheckedIcon } from '../generated/components/chat-checked.tsx';
export { chatCheckedIconDefinition } from '../generated/definitions/chat-checked.ts';
