/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatOffFilledIcon } from '../generated/components/chat-off-filled.tsx';
export { chatOffFilledIconDefinition } from '../generated/definitions/chat-off-filled.ts';
