/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleFilledIcon } from '../generated/components/chat-bubble-filled.tsx';
export { chatBubbleFilledIconDefinition } from '../generated/definitions/chat-bubble-filled.ts';
