/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleSmileFilledIcon } from '../generated/components/chat-bubble-smile-filled.tsx';
export { chatBubbleSmileFilledIconDefinition } from '../generated/definitions/chat-bubble-smile-filled.ts';
