/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatDoubleIcon } from '../generated/components/chat-double.tsx';
export { chatDoubleIconDefinition } from '../generated/definitions/chat-double.ts';
