/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatErrorFilledIcon } from '../generated/components/chat-error-filled.tsx';
export { chatErrorFilledIconDefinition } from '../generated/definitions/chat-error-filled.ts';
