/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleSmileIcon } from '../generated/components/chat-bubble-smile.tsx';
export { chatBubbleSmileIconDefinition } from '../generated/definitions/chat-bubble-smile.ts';
