/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleHelpFilledIcon } from '../generated/components/chat-bubble-help-filled.tsx';
export { chatBubbleHelpFilledIconDefinition } from '../generated/definitions/chat-bubble-help-filled.ts';
