/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatSettingFilledIcon } from '../generated/components/chat-setting-filled.tsx';
export { chatSettingFilledIconDefinition } from '../generated/definitions/chat-setting-filled.ts';
