/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatPollIcon } from '../generated/components/chat-poll.tsx';
export { chatPollIconDefinition } from '../generated/definitions/chat-poll.ts';
