/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleHelpIcon } from '../generated/components/chat-bubble-help.tsx';
export { chatBubbleHelpIconDefinition } from '../generated/definitions/chat-bubble-help.ts';
