/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChatBubbleIcon } from '../generated/components/chat-bubble.tsx';
export { chatBubbleIconDefinition } from '../generated/definitions/chat-bubble.ts';
