/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CheckRectangleIcon } from '../generated/components/check-rectangle.tsx';
export { checkRectangleIconDefinition } from '../generated/definitions/check-rectangle.ts';
