/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CheeseFilledIcon } from '../generated/components/cheese-filled.tsx';
export { cheeseFilledIconDefinition } from '../generated/definitions/cheese-filled.ts';
