/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronLeftSIcon } from '../generated/components/chevron-left-s.tsx';
export { chevronLeftSIconDefinition } from '../generated/definitions/chevron-left-s.ts';
