/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronDownIcon } from '../generated/components/chevron-down.tsx';
export { chevronDownIconDefinition } from '../generated/definitions/chevron-down.ts';
