/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronLeftRectangleFilledIcon } from '../generated/components/chevron-left-rectangle-filled.tsx';
export { chevronLeftRectangleFilledIconDefinition } from '../generated/definitions/chevron-left-rectangle-filled.ts';
