/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronRightCircleIcon } from '../generated/components/chevron-right-circle.tsx';
export { chevronRightCircleIconDefinition } from '../generated/definitions/chevron-right-circle.ts';
