/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronDownDoubleSIcon } from '../generated/components/chevron-down-double-s.tsx';
export { chevronDownDoubleSIconDefinition } from '../generated/definitions/chevron-down-double-s.ts';
