/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronRightDoubleSIcon } from '../generated/components/chevron-right-double-s.tsx';
export { chevronRightDoubleSIconDefinition } from '../generated/definitions/chevron-right-double-s.ts';
