/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronDownSIcon } from '../generated/components/chevron-down-s.tsx';
export { chevronDownSIconDefinition } from '../generated/definitions/chevron-down-s.ts';
