/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronLeftIcon } from '../generated/components/chevron-left.tsx';
export { chevronLeftIconDefinition } from '../generated/definitions/chevron-left.ts';
