/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChevronUpDoubleIcon } from '../generated/components/chevron-up-double.tsx';
export { chevronUpDoubleIconDefinition } from '../generated/definitions/chevron-up-double.ts';
