/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Chimney1Icon } from '../generated/components/chimney-1.tsx';
export { chimney1IconDefinition } from '../generated/definitions/chimney-1.ts';
