/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChimneyFilledIcon } from '../generated/components/chimney-filled.tsx';
export { chimneyFilledIconDefinition } from '../generated/definitions/chimney-filled.ts';
