/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChineseRectangleFilledIcon } from '../generated/components/chinese-rectangle-filled.tsx';
export { chineseRectangleFilledIconDefinition } from '../generated/definitions/chinese-rectangle-filled.ts';
