/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ChurchFilledIcon } from '../generated/components/church-filled.tsx';
export { churchFilledIconDefinition } from '../generated/definitions/church-filled.ts';
