/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CircleFilledIcon } from '../generated/components/circle-filled.tsx';
export { circleFilledIconDefinition } from '../generated/definitions/circle-filled.ts';
