/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CircleIcon } from '../generated/components/circle.tsx';
export { circleIconDefinition } from '../generated/definitions/circle.ts';
