/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City11FilledIcon } from '../generated/components/city-11-filled.tsx';
export { city11FilledIconDefinition } from '../generated/definitions/city-11-filled.ts';
