/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City6Icon } from '../generated/components/city-6.tsx';
export { city6IconDefinition } from '../generated/definitions/city-6.ts';
