/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityFilledIcon } from '../generated/components/city-filled.tsx';
export { cityFilledIconDefinition } from '../generated/definitions/city-filled.ts';
