/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityAncient2Icon } from '../generated/components/city-ancient-2.tsx';
export { cityAncient2IconDefinition } from '../generated/definitions/city-ancient-2.ts';
