/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityAncient1Icon } from '../generated/components/city-ancient-1.tsx';
export { cityAncient1IconDefinition } from '../generated/definitions/city-ancient-1.ts';
