/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityIcon } from '../generated/components/city.tsx';
export { cityIconDefinition } from '../generated/definitions/city.ts';
