/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City3Icon } from '../generated/components/city-3.tsx';
export { city3IconDefinition } from '../generated/definitions/city-3.ts';
