/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City14Icon } from '../generated/components/city-14.tsx';
export { city14IconDefinition } from '../generated/definitions/city-14.ts';
