/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City4Icon } from '../generated/components/city-4.tsx';
export { city4IconDefinition } from '../generated/definitions/city-4.ts';
