/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CityAncientFilledIcon } from '../generated/components/city-ancient-filled.tsx';
export { cityAncientFilledIconDefinition } from '../generated/definitions/city-ancient-filled.ts';
