/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City11Icon } from '../generated/components/city-11.tsx';
export { city11IconDefinition } from '../generated/definitions/city-11.ts';
