/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { City8FilledIcon } from '../generated/components/city-8-filled.tsx';
export { city8FilledIconDefinition } from '../generated/definitions/city-8-filled.ts';
