/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ClearIcon } from '../generated/components/clear.tsx';
export { clearIconDefinition } from '../generated/definitions/clear.ts';
