/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ClearFormattingFilledIcon } from '../generated/components/clear-formatting-filled.tsx';
export { clearFormattingFilledIconDefinition } from '../generated/definitions/clear-formatting-filled.ts';
