/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloseRectangleFilledIcon } from '../generated/components/close-rectangle-filled.tsx';
export { closeRectangleFilledIconDefinition } from '../generated/definitions/close-rectangle-filled.ts';
