/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloseRectangleIcon } from '../generated/components/close-rectangle.tsx';
export { closeRectangleIconDefinition } from '../generated/definitions/close-rectangle.ts';
