/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloseOctagonFilledIcon } from '../generated/components/close-octagon-filled.tsx';
export { closeOctagonFilledIconDefinition } from '../generated/definitions/close-octagon-filled.ts';
