/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloseOctagonIcon } from '../generated/components/close-octagon.tsx';
export { closeOctagonIconDefinition } from '../generated/definitions/close-octagon.ts';
