/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudyDayIcon } from '../generated/components/cloudy-day.tsx';
export { cloudyDayIconDefinition } from '../generated/definitions/cloudy-day.ts';
