/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudUploadIcon } from '../generated/components/cloud-upload.tsx';
export { cloudUploadIconDefinition } from '../generated/definitions/cloud-upload.ts';
