/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CloudDownloadIcon } from '../generated/components/cloud-download.tsx';
export { cloudDownloadIconDefinition } from '../generated/definitions/cloud-download.ts';
