/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ColaIcon } from '../generated/components/cola.tsx';
export { colaIconDefinition } from '../generated/definitions/cola.ts';
