/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CollapsibleBlockIcon } from '../generated/components/collapsible-block.tsx';
export { collapsibleBlockIconDefinition } from '../generated/definitions/collapsible-block.ts';
