/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Collection1Icon } from '../generated/components/collection-1.tsx';
export { collection1IconDefinition } from '../generated/definitions/collection-1.ts';
