/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CollageIcon } from '../generated/components/collage.tsx';
export { collageIconDefinition } from '../generated/definitions/collage.ts';
