/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CollectionFilledIcon } from '../generated/components/collection-filled.tsx';
export { collectionFilledIconDefinition } from '../generated/definitions/collection-filled.ts';
