/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ColumnLayoutFilledIcon } from '../generated/components/column-layout-filled.tsx';
export { columnLayoutFilledIconDefinition } from '../generated/definitions/column-layout-filled.ts';
