/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CombinationFilledIcon } from '../generated/components/combination-filled.tsx';
export { combinationFilledIconDefinition } from '../generated/definitions/combination-filled.ts';
