/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CommandIcon } from '../generated/components/command.tsx';
export { commandIconDefinition } from '../generated/definitions/command.ts';
