/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentLayoutIcon } from '../generated/components/component-layout.tsx';
export { componentLayoutIconDefinition } from '../generated/definitions/component-layout.ts';
