/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentSwitchFilledIcon } from '../generated/components/component-switch-filled.tsx';
export { componentSwitchFilledIconDefinition } from '../generated/definitions/component-switch-filled.ts';
