/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentCheckboxFilledIcon } from '../generated/components/component-checkbox-filled.tsx';
export { componentCheckboxFilledIconDefinition } from '../generated/definitions/component-checkbox-filled.ts';
