/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CompassIcon } from '../generated/components/compass.tsx';
export { compassIconDefinition } from '../generated/definitions/compass.ts';
