/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentSpaceIcon } from '../generated/components/component-space.tsx';
export { componentSpaceIconDefinition } from '../generated/definitions/component-space.ts';
