/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentStepsFilledIcon } from '../generated/components/component-steps-filled.tsx';
export { componentStepsFilledIconDefinition } from '../generated/definitions/component-steps-filled.ts';
