/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentBreadcrumbFilledIcon } from '../generated/components/component-breadcrumb-filled.tsx';
export { componentBreadcrumbFilledIconDefinition } from '../generated/definitions/component-breadcrumb-filled.ts';
