/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Compass1Icon } from '../generated/components/compass-1.tsx';
export { compass1IconDefinition } from '../generated/definitions/compass-1.ts';
