/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentDividerVerticalFilledIcon } from '../generated/components/component-divider-vertical-filled.tsx';
export { componentDividerVerticalFilledIconDefinition } from '../generated/definitions/component-divider-vertical-filled.ts';
