/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentInputFilledIcon } from '../generated/components/component-input-filled.tsx';
export { componentInputFilledIconDefinition } from '../generated/definitions/component-input-filled.ts';
