/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentDropdownFilledIcon } from '../generated/components/component-dropdown-filled.tsx';
export { componentDropdownFilledIconDefinition } from '../generated/definitions/component-dropdown-filled.ts';
