/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentStickytoolFilledIcon } from '../generated/components/component-stickytool-filled.tsx';
export { componentStickytoolFilledIconDefinition } from '../generated/definitions/component-stickytool-filled.ts';
