/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentBreadcrumbIcon } from '../generated/components/component-breadcrumb.tsx';
export { componentBreadcrumbIconDefinition } from '../generated/definitions/component-breadcrumb.ts';
