/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CompassFilledIcon } from '../generated/components/compass-filled.tsx';
export { compassFilledIconDefinition } from '../generated/definitions/compass-filled.ts';
