/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentSwitchIcon } from '../generated/components/component-switch.tsx';
export { componentSwitchIconDefinition } from '../generated/definitions/component-switch.ts';
