/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ComponentSpaceFilledIcon } from '../generated/components/component-space-filled.tsx';
export { componentSpaceFilledIconDefinition } from '../generated/definitions/component-space-filled.ts';
