/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ConstraintIcon } from '../generated/components/constraint.tsx';
export { constraintIconDefinition } from '../generated/definitions/constraint.ts';
