/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Contrast1Icon } from '../generated/components/contrast-1.tsx';
export { contrast1IconDefinition } from '../generated/definitions/contrast-1.ts';
