/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ControlPlatformFilledIcon } from '../generated/components/control-platform-filled.tsx';
export { controlPlatformFilledIconDefinition } from '../generated/definitions/control-platform-filled.ts';
