/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Contrast1FilledIcon } from '../generated/components/contrast-1-filled.tsx';
export { contrast1FilledIconDefinition } from '../generated/definitions/contrast-1-filled.ts';
