/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ContrastFilledIcon } from '../generated/components/contrast-filled.tsx';
export { contrastFilledIconDefinition } from '../generated/definitions/contrast-filled.ts';
