/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CopyFilledIcon } from '../generated/components/copy-filled.tsx';
export { copyFilledIconDefinition } from '../generated/definitions/copy-filled.ts';
