/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CpuFilledIcon } from '../generated/components/cpu-filled.tsx';
export { cpuFilledIconDefinition } from '../generated/definitions/cpu-filled.ts';
