/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CpuIcon } from '../generated/components/cpu.tsx';
export { cpuIconDefinition } from '../generated/definitions/cpu.ts';
