/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CrackFilledIcon } from '../generated/components/crack-filled.tsx';
export { crackFilledIconDefinition } from '../generated/definitions/crack-filled.ts';
