/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CreditcardOffIcon } from '../generated/components/creditcard-off.tsx';
export { creditcardOffIconDefinition } from '../generated/definitions/creditcard-off.ts';
