/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CreditcardFilledIcon } from '../generated/components/creditcard-filled.tsx';
export { creditcardFilledIconDefinition } from '../generated/definitions/creditcard-filled.ts';
