/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CreditcardOffFilledIcon } from '../generated/components/creditcard-off-filled.tsx';
export { creditcardOffFilledIconDefinition } from '../generated/definitions/creditcard-off-filled.ts';
