/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CreditcardAddIcon } from '../generated/components/creditcard-add.tsx';
export { creditcardAddIconDefinition } from '../generated/definitions/creditcard-add.ts';
