/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CrookedSmileIcon } from '../generated/components/crooked-smile.tsx';
export { crookedSmileIconDefinition } from '../generated/definitions/crooked-smile.ts';
