/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CryLoudlyFilledIcon } from '../generated/components/cry-loudly-filled.tsx';
export { cryLoudlyFilledIconDefinition } from '../generated/definitions/cry-loudly-filled.ts';
