/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CryAndLaughFilledIcon } from '../generated/components/cry-and-laugh-filled.tsx';
export { cryAndLaughFilledIconDefinition } from '../generated/definitions/cry-and-laugh-filled.ts';
