/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Css3Icon } from '../generated/components/css3.tsx';
export { css3IconDefinition } from '../generated/definitions/css3.ts';
