/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CurrencyExchangeIcon } from '../generated/components/currency-exchange.tsx';
export { currencyExchangeIconDefinition } from '../generated/definitions/currency-exchange.ts';
