/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CursorIcon } from '../generated/components/cursor.tsx';
export { cursorIconDefinition } from '../generated/definitions/cursor.ts';
