/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CursorFilledIcon } from '../generated/components/cursor-filled.tsx';
export { cursorFilledIconDefinition } from '../generated/definitions/cursor-filled.ts';
