/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CurveIcon } from '../generated/components/curve.tsx';
export { curveIconDefinition } from '../generated/definitions/curve.ts';
