/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Cut1Icon } from '../generated/components/cut-1.tsx';
export { cut1IconDefinition } from '../generated/definitions/cut-1.ts';
