/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { CutIcon } from '../generated/components/cut.tsx';
export { cutIconDefinition } from '../generated/definitions/cut.ts';
