/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam6Icon } from '../generated/components/dam-6.tsx';
export { dam6IconDefinition } from '../generated/definitions/dam-6.ts';
