/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam3Icon } from '../generated/components/dam-3.tsx';
export { dam3IconDefinition } from '../generated/definitions/dam-3.ts';
