/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam1FilledIcon } from '../generated/components/dam-1-filled.tsx';
export { dam1FilledIconDefinition } from '../generated/definitions/dam-1-filled.ts';
