/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam5FilledIcon } from '../generated/components/dam-5-filled.tsx';
export { dam5FilledIconDefinition } from '../generated/definitions/dam-5-filled.ts';
