/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam3FilledIcon } from '../generated/components/dam-3-filled.tsx';
export { dam3FilledIconDefinition } from '../generated/definitions/dam-3-filled.ts';
