/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam5Icon } from '../generated/components/dam-5.tsx';
export { dam5IconDefinition } from '../generated/definitions/dam-5.ts';
