/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam2Icon } from '../generated/components/dam-2.tsx';
export { dam2IconDefinition } from '../generated/definitions/dam-2.ts';
