/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam2FilledIcon } from '../generated/components/dam-2-filled.tsx';
export { dam2FilledIconDefinition } from '../generated/definitions/dam-2-filled.ts';
