/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam6FilledIcon } from '../generated/components/dam-6-filled.tsx';
export { dam6FilledIconDefinition } from '../generated/definitions/dam-6-filled.ts';
