/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam7Icon } from '../generated/components/dam-7.tsx';
export { dam7IconDefinition } from '../generated/definitions/dam-7.ts';
