/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dam4FilledIcon } from '../generated/components/dam-4-filled.tsx';
export { dam4FilledIconDefinition } from '../generated/definitions/dam-4-filled.ts';
