/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DartBoardFilledIcon } from '../generated/components/dart-board-filled.tsx';
export { dartBoardFilledIconDefinition } from '../generated/definitions/dart-board-filled.ts';
