/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DartBoardIcon } from '../generated/components/dart-board.tsx';
export { dartBoardIconDefinition } from '../generated/definitions/dart-board.ts';
