/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dashboard1FilledIcon } from '../generated/components/dashboard-1-filled.tsx';
export { dashboard1FilledIconDefinition } from '../generated/definitions/dashboard-1-filled.ts';
