/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Dashboard1Icon } from '../generated/components/dashboard-1.tsx';
export { dashboard1IconDefinition } from '../generated/definitions/dashboard-1.ts';
