/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataBaseFilledIcon } from '../generated/components/data-base-filled.tsx';
export { dataBaseFilledIconDefinition } from '../generated/definitions/data-base-filled.ts';
