/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataCheckedIcon } from '../generated/components/data-checked.tsx';
export { dataCheckedIconDefinition } from '../generated/definitions/data-checked.ts';
