/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataFilledIcon } from '../generated/components/data-filled.tsx';
export { dataFilledIconDefinition } from '../generated/definitions/data-filled.ts';
