/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DataBaseIcon } from '../generated/components/data-base.tsx';
export { dataBaseIconDefinition } from '../generated/definitions/data-base.ts';
