/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeleteIcon } from '../generated/components/delete.tsx';
export { deleteIconDefinition } from '../generated/definitions/delete.ts';
