/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Delete1FilledIcon } from '../generated/components/delete-1-filled.tsx';
export { delete1FilledIconDefinition } from '../generated/definitions/delete-1-filled.ts';
