/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeltaFilledIcon } from '../generated/components/delta-filled.tsx';
export { deltaFilledIconDefinition } from '../generated/definitions/delta-filled.ts';
