/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DeltaIcon } from '../generated/components/delta.tsx';
export { deltaIconDefinition } from '../generated/definitions/delta.ts';
