/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Desktop1FilledIcon } from '../generated/components/desktop-1-filled.tsx';
export { desktop1FilledIconDefinition } from '../generated/definitions/desktop-1-filled.ts';
