/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DesktopIcon } from '../generated/components/desktop.tsx';
export { desktopIconDefinition } from '../generated/definitions/desktop.ts';
