/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DespiseIcon } from '../generated/components/despise.tsx';
export { despiseIconDefinition } from '../generated/definitions/despise.ts';
