/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DialogHistoryFilledIcon } from '../generated/components/dialog-history-filled.tsx';
export { dialogHistoryFilledIconDefinition } from '../generated/definitions/dialog-history-filled.ts';
