/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DialogHistoryIcon } from '../generated/components/dialog-history.tsx';
export { dialogHistoryIconDefinition } from '../generated/definitions/dialog-history.ts';
