/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DiscountFilledIcon } from '../generated/components/discount-filled.tsx';
export { discountFilledIconDefinition } from '../generated/definitions/discount-filled.ts';
