/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DiscountIcon } from '../generated/components/discount.tsx';
export { discountIconDefinition } from '../generated/definitions/discount.ts';
