/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DissatisfactionIcon } from '../generated/components/dissatisfaction.tsx';
export { dissatisfactionIconDefinition } from '../generated/definitions/dissatisfaction.ts';
