/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DissatisfactionFilledIcon } from '../generated/components/dissatisfaction-filled.tsx';
export { dissatisfactionFilledIconDefinition } from '../generated/definitions/dissatisfaction-filled.ts';
