/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DividersIcon } from '../generated/components/dividers.tsx';
export { dividersIconDefinition } from '../generated/definitions/dividers.ts';
