/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DocumentUpdateIcon } from '../generated/components/document-update.tsx';
export { documentUpdateIconDefinition } from '../generated/definitions/document-update.ts';
