/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DocumentLocationIcon } from '../generated/components/document-location.tsx';
export { documentLocationIconDefinition } from '../generated/definitions/document-location.ts';
