/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DogeIcon } from '../generated/components/doge.tsx';
export { dogeIconDefinition } from '../generated/definitions/doge.ts';
