/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DoubleStoreyIcon } from '../generated/components/double-storey.tsx';
export { doubleStoreyIconDefinition } from '../generated/definitions/double-storey.ts';
