/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DoubleStoreyFilledIcon } from '../generated/components/double-storey-filled.tsx';
export { doubleStoreyFilledIconDefinition } from '../generated/definitions/double-storey-filled.ts';
