/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DragMoveIcon } from '../generated/components/drag-move.tsx';
export { dragMoveIconDefinition } from '../generated/definitions/drag-move.ts';
