/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DrinkIcon } from '../generated/components/drink.tsx';
export { drinkIconDefinition } from '../generated/definitions/drink.ts';
