/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DrinkFilledIcon } from '../generated/components/drink-filled.tsx';
export { drinkFilledIconDefinition } from '../generated/definitions/drink-filled.ts';
