/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DrumstickIcon } from '../generated/components/drumstick.tsx';
export { drumstickIconDefinition } from '../generated/definitions/drumstick.ts';
