/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { DvdFilledIcon } from '../generated/components/dvd-filled.tsx';
export { dvdFilledIconDefinition } from '../generated/definitions/dvd-filled.ts';
