/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EarphoneFilledIcon } from '../generated/components/earphone-filled.tsx';
export { earphoneFilledIconDefinition } from '../generated/definitions/earphone-filled.ts';
