/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EarthIcon } from '../generated/components/earth.tsx';
export { earthIconDefinition } from '../generated/definitions/earth.ts';
