/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EditIcon } from '../generated/components/edit.tsx';
export { editIconDefinition } from '../generated/definitions/edit.ts';
