/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Edit1Icon } from '../generated/components/edit-1.tsx';
export { edit1IconDefinition } from '../generated/definitions/edit-1.ts';
