/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Edit1FilledIcon } from '../generated/components/edit-1-filled.tsx';
export { edit1FilledIconDefinition } from '../generated/definitions/edit-1-filled.ts';
