/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EditOffIcon } from '../generated/components/edit-off.tsx';
export { editOffIconDefinition } from '../generated/definitions/edit-off.ts';
