/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EducationFilledIcon } from '../generated/components/education-filled.tsx';
export { educationFilledIconDefinition } from '../generated/definitions/education-filled.ts';
