/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { EmoEmotionalIcon } from '../generated/components/emo-emotional.tsx';
export { emoEmotionalIconDefinition } from '../generated/definitions/emo-emotional.ts';
