/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ErrorTriangleIcon } from '../generated/components/error-triangle.tsx';
export { errorTriangleIconDefinition } from '../generated/definitions/error-triangle.ts';
