/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ErrorIcon } from '../generated/components/error.tsx';
export { errorIconDefinition } from '../generated/definitions/error.ts';
