/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExpandHorizontalIcon } from '../generated/components/expand-horizontal.tsx';
export { expandHorizontalIconDefinition } from '../generated/definitions/expand-horizontal.ts';
