/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExpandUpFilledIcon } from '../generated/components/expand-up-filled.tsx';
export { expandUpFilledIconDefinition } from '../generated/definitions/expand-up-filled.ts';
