/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExpandUpIcon } from '../generated/components/expand-up.tsx';
export { expandUpIconDefinition } from '../generated/definitions/expand-up.ts';
