/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExploreFilledIcon } from '../generated/components/explore-filled.tsx';
export { exploreFilledIconDefinition } from '../generated/definitions/explore-filled.ts';
