/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExposureFilledIcon } from '../generated/components/exposure-filled.tsx';
export { exposureFilledIconDefinition } from '../generated/definitions/exposure-filled.ts';
