/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ExtensionIcon } from '../generated/components/extension.tsx';
export { extensionIconDefinition } from '../generated/definitions/extension.ts';
