/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FaceRetouchingIcon } from '../generated/components/face-retouching.tsx';
export { faceRetouchingIconDefinition } from '../generated/definitions/face-retouching.ts';
