/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FactCheckIcon } from '../generated/components/fact-check.tsx';
export { factCheckIconDefinition } from '../generated/definitions/fact-check.ts';
