/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FahrenheitScaleIcon } from '../generated/components/fahrenheit-scale.tsx';
export { fahrenheitScaleIconDefinition } from '../generated/definitions/fahrenheit-scale.ts';
