/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FeelAtEaseIcon } from '../generated/components/feel-at-ease.tsx';
export { feelAtEaseIconDefinition } from '../generated/definitions/feel-at-ease.ts';
