/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FerociousIcon } from '../generated/components/ferocious.tsx';
export { ferociousIconDefinition } from '../generated/definitions/ferocious.ts';
