/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FerrisWheelIcon } from '../generated/components/ferris-wheel.tsx';
export { ferrisWheelIconDefinition } from '../generated/definitions/ferris-wheel.ts';
