/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileRestoreFilledIcon } from '../generated/components/file-restore-filled.tsx';
export { fileRestoreFilledIconDefinition } from '../generated/definitions/file-restore-filled.ts';
