/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileSearchFilledIcon } from '../generated/components/file-search-filled.tsx';
export { fileSearchFilledIconDefinition } from '../generated/definitions/file-search-filled.ts';
