/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileMusicIcon } from '../generated/components/file-music.tsx';
export { fileMusicIconDefinition } from '../generated/definitions/file-music.ts';
