/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCsvFilledIcon } from '../generated/components/file-csv-filled.tsx';
export { fileCsvFilledIconDefinition } from '../generated/definitions/file-csv-filled.ts';
