/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileYamlIcon } from '../generated/components/file-yaml.tsx';
export { fileYamlIconDefinition } from '../generated/definitions/file-yaml.ts';
