/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileExcelIcon } from '../generated/components/file-excel.tsx';
export { fileExcelIconDefinition } from '../generated/definitions/file-excel.ts';
