/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCode1Icon } from '../generated/components/file-code-1.tsx';
export { fileCode1IconDefinition } from '../generated/definitions/file-code-1.ts';
