/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileMusicFilledIcon } from '../generated/components/file-music-filled.tsx';
export { fileMusicFilledIconDefinition } from '../generated/definitions/file-music-filled.ts';
