/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilePowerpointFilledIcon } from '../generated/components/file-powerpoint-filled.tsx';
export { filePowerpointFilledIconDefinition } from '../generated/definitions/file-powerpoint-filled.ts';
