/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilePowerpointIcon } from '../generated/components/file-powerpoint.tsx';
export { filePowerpointIconDefinition } from '../generated/definitions/file-powerpoint.ts';
