/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileBlockedIcon } from '../generated/components/file-blocked.tsx';
export { fileBlockedIconDefinition } from '../generated/definitions/file-blocked.ts';
