/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileSettingIcon } from '../generated/components/file-setting.tsx';
export { fileSettingIconDefinition } from '../generated/definitions/file-setting.ts';
