/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileUnknownFilledIcon } from '../generated/components/file-unknown-filled.tsx';
export { fileUnknownFilledIconDefinition } from '../generated/definitions/file-unknown-filled.ts';
