/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCode1FilledIcon } from '../generated/components/file-code-1-filled.tsx';
export { fileCode1FilledIconDefinition } from '../generated/definitions/file-code-1-filled.ts';
