/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileExportIcon } from '../generated/components/file-export.tsx';
export { fileExportIconDefinition } from '../generated/definitions/file-export.ts';
