/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileDownloadFilledIcon } from '../generated/components/file-download-filled.tsx';
export { fileDownloadFilledIconDefinition } from '../generated/definitions/file-download-filled.ts';
