/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileAddFilledIcon } from '../generated/components/file-add-filled.tsx';
export { fileAddFilledIconDefinition } from '../generated/definitions/file-add-filled.ts';
