/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileImportFilledIcon } from '../generated/components/file-import-filled.tsx';
export { fileImportFilledIconDefinition } from '../generated/definitions/file-import-filled.ts';
