/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileIconFilledIcon } from '../generated/components/file-icon-filled.tsx';
export { fileIconFilledIconDefinition } from '../generated/definitions/file-icon-filled.ts';
