/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileImageFilledIcon } from '../generated/components/file-image-filled.tsx';
export { fileImageFilledIconDefinition } from '../generated/definitions/file-image-filled.ts';
