/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCodeIcon } from '../generated/components/file-code.tsx';
export { fileCodeIconDefinition } from '../generated/definitions/file-code.ts';
