/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileIcon } from '../generated/components/file.tsx';
export { fileIconDefinition } from '../generated/definitions/file.ts';
