/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileOnenoteFilledIcon } from '../generated/components/file-onenote-filled.tsx';
export { fileOnenoteFilledIconDefinition } from '../generated/definitions/file-onenote-filled.ts';
