/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileTransmitDoubleFilledIcon } from '../generated/components/file-transmit-double-filled.tsx';
export { fileTransmitDoubleFilledIconDefinition } from '../generated/definitions/file-transmit-double-filled.ts';
