/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileLockedFilledIcon } from '../generated/components/file-locked-filled.tsx';
export { fileLockedFilledIconDefinition } from '../generated/definitions/file-locked-filled.ts';
