/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileTxtFilledIcon } from '../generated/components/file-txt-filled.tsx';
export { fileTxtFilledIconDefinition } from '../generated/definitions/file-txt-filled.ts';
