/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileJsonIcon } from '../generated/components/file-json.tsx';
export { fileJsonIconDefinition } from '../generated/definitions/file-json.ts';
