/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileCopyFilledIcon } from '../generated/components/file-copy-filled.tsx';
export { fileCopyFilledIconDefinition } from '../generated/definitions/file-copy-filled.ts';
