/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FileUnlockedIcon } from '../generated/components/file-unlocked.tsx';
export { fileUnlockedIconDefinition } from '../generated/definitions/file-unlocked.ts';
