/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FillColorFilledIcon } from '../generated/components/fill-color-filled.tsx';
export { fillColorFilledIconDefinition } from '../generated/definitions/fill-color-filled.ts';
