/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FillColorIcon } from '../generated/components/fill-color.tsx';
export { fillColorIconDefinition } from '../generated/definitions/fill-color.ts';
