/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilmFilledIcon } from '../generated/components/film-filled.tsx';
export { filmFilledIconDefinition } from '../generated/definitions/film-filled.ts';
