/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Filter3FilledIcon } from '../generated/components/filter-3-filled.tsx';
export { filter3FilledIconDefinition } from '../generated/definitions/filter-3-filled.ts';
