/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Filter1Icon } from '../generated/components/filter-1.tsx';
export { filter1IconDefinition } from '../generated/definitions/filter-1.ts';
