/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Filter2FilledIcon } from '../generated/components/filter-2-filled.tsx';
export { filter2FilledIconDefinition } from '../generated/definitions/filter-2-filled.ts';
