/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Filter2Icon } from '../generated/components/filter-2.tsx';
export { filter2IconDefinition } from '../generated/definitions/filter-2.ts';
