/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilterSortFilledIcon } from '../generated/components/filter-sort-filled.tsx';
export { filterSortFilledIconDefinition } from '../generated/definitions/filter-sort-filled.ts';
