/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FilterClearFilledIcon } from '../generated/components/filter-clear-filled.tsx';
export { filterClearFilledIconDefinition } from '../generated/definitions/filter-clear-filled.ts';
