/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Fingerprint3Icon } from '../generated/components/fingerprint-3.tsx';
export { fingerprint3IconDefinition } from '../generated/definitions/fingerprint-3.ts';
