/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Fingerprint2Icon } from '../generated/components/fingerprint-2.tsx';
export { fingerprint2IconDefinition } from '../generated/definitions/fingerprint-2.ts';
