/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag4FilledIcon } from '../generated/components/flag-4-filled.tsx';
export { flag4FilledIconDefinition } from '../generated/definitions/flag-4-filled.ts';
