/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag4Icon } from '../generated/components/flag-4.tsx';
export { flag4IconDefinition } from '../generated/definitions/flag-4.ts';
