/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag3FilledIcon } from '../generated/components/flag-3-filled.tsx';
export { flag3FilledIconDefinition } from '../generated/definitions/flag-3-filled.ts';
