/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag1Icon } from '../generated/components/flag-1.tsx';
export { flag1IconDefinition } from '../generated/definitions/flag-1.ts';
