/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag2FilledIcon } from '../generated/components/flag-2-filled.tsx';
export { flag2FilledIconDefinition } from '../generated/definitions/flag-2-filled.ts';
