/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Flag3Icon } from '../generated/components/flag-3.tsx';
export { flag3IconDefinition } from '../generated/definitions/flag-3.ts';
