/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlashlightIcon } from '../generated/components/flashlight.tsx';
export { flashlightIconDefinition } from '../generated/definitions/flashlight.ts';
