/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlashlightFilledIcon } from '../generated/components/flashlight-filled.tsx';
export { flashlightFilledIconDefinition } from '../generated/definitions/flashlight-filled.ts';
