/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlightTakeoffFilledIcon } from '../generated/components/flight-takeoff-filled.tsx';
export { flightTakeoffFilledIconDefinition } from '../generated/definitions/flight-takeoff-filled.ts';
