/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlightLandingIcon } from '../generated/components/flight-landing.tsx';
export { flightLandingIconDefinition } from '../generated/definitions/flight-landing.ts';
