/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlipToFrontFilledIcon } from '../generated/components/flip-to-front-filled.tsx';
export { flipToFrontFilledIconDefinition } from '../generated/definitions/flip-to-front-filled.ts';
