/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FlipSmilingFaceFilledIcon } from '../generated/components/flip-smiling-face-filled.tsx';
export { flipSmilingFaceFilledIconDefinition } from '../generated/definitions/flip-smiling-face-filled.ts';
