/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FocusIcon } from '../generated/components/focus.tsx';
export { focusIconDefinition } from '../generated/definitions/focus.ts';
