/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FogSunnyFilledIcon } from '../generated/components/fog-sunny-filled.tsx';
export { fogSunnyFilledIconDefinition } from '../generated/definitions/fog-sunny-filled.ts';
