/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderMoveFilledIcon } from '../generated/components/folder-move-filled.tsx';
export { folderMoveFilledIconDefinition } from '../generated/definitions/folder-move-filled.ts';
