/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderSettingFilledIcon } from '../generated/components/folder-setting-filled.tsx';
export { folderSettingFilledIconDefinition } from '../generated/definitions/folder-setting-filled.ts';
