/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Folder1FilledIcon } from '../generated/components/folder-1-filled.tsx';
export { folder1FilledIconDefinition } from '../generated/definitions/folder-1-filled.ts';
