/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderOpen1FilledIcon } from '../generated/components/folder-open-1-filled.tsx';
export { folderOpen1FilledIconDefinition } from '../generated/definitions/folder-open-1-filled.ts';
