/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderMoveIcon } from '../generated/components/folder-move.tsx';
export { folderMoveIconDefinition } from '../generated/definitions/folder-move.ts';
