/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderFilledIcon } from '../generated/components/folder-filled.tsx';
export { folderFilledIconDefinition } from '../generated/definitions/folder-filled.ts';
