/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderDetailsIcon } from '../generated/components/folder-details.tsx';
export { folderDetailsIconDefinition } from '../generated/definitions/folder-details.ts';
