/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderSearchIcon } from '../generated/components/folder-search.tsx';
export { folderSearchIconDefinition } from '../generated/definitions/folder-search.ts';
