/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderOpenIcon } from '../generated/components/folder-open.tsx';
export { folderOpenIconDefinition } from '../generated/definitions/folder-open.ts';
