/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderOffFilledIcon } from '../generated/components/folder-off-filled.tsx';
export { folderOffFilledIconDefinition } from '../generated/definitions/folder-off-filled.ts';
