/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FolderAdd1FilledIcon } from '../generated/components/folder-add-1-filled.tsx';
export { folderAdd1FilledIconDefinition } from '../generated/definitions/folder-add-1-filled.ts';
