/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForkFilledIcon } from '../generated/components/fork-filled.tsx';
export { forkFilledIconDefinition } from '../generated/definitions/fork-filled.ts';
