/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormatPainterIcon } from '../generated/components/format-painter.tsx';
export { formatPainterIconDefinition } from '../generated/definitions/format-painter.ts';
