/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormFilledIcon } from '../generated/components/form-filled.tsx';
export { formFilledIconDefinition } from '../generated/definitions/form-filled.ts';
