/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormatHorizontalAlignCenterIcon } from '../generated/components/format-horizontal-align-center.tsx';
export { formatHorizontalAlignCenterIconDefinition } from '../generated/definitions/format-horizontal-align-center.ts';
