/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormatHorizontalAlignTopIcon } from '../generated/components/format-horizontal-align-top.tsx';
export { formatHorizontalAlignTopIconDefinition } from '../generated/definitions/format-horizontal-align-top.ts';
