/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormIcon } from '../generated/components/form.tsx';
export { formIconDefinition } from '../generated/definitions/form.ts';
