/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FormulaIcon } from '../generated/components/formula.tsx';
export { formulaIconDefinition } from '../generated/definitions/formula.ts';
