/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForumIcon } from '../generated/components/forum.tsx';
export { forumIconDefinition } from '../generated/definitions/forum.ts';
