/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForwardFilledIcon } from '../generated/components/forward-filled.tsx';
export { forwardFilledIconDefinition } from '../generated/definitions/forward-filled.ts';
