/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ForwardIcon } from '../generated/components/forward.tsx';
export { forwardIconDefinition } from '../generated/definitions/forward.ts';
