/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Frame1Icon } from '../generated/components/frame-1.tsx';
export { frame1IconDefinition } from '../generated/definitions/frame-1.ts';
