/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Fullscreen1Icon } from '../generated/components/fullscreen-1.tsx';
export { fullscreen1IconDefinition } from '../generated/definitions/fullscreen-1.ts';
