/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { FullscreenExitIcon } from '../generated/components/fullscreen-exit.tsx';
export { fullscreenExitIconDefinition } from '../generated/definitions/fullscreen-exit.ts';
