/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Fullscreen2Icon } from '../generated/components/fullscreen-2.tsx';
export { fullscreen2IconDefinition } from '../generated/definitions/fullscreen-2.ts';
