/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Gamepad1Icon } from '../generated/components/gamepad-1.tsx';
export { gamepad1IconDefinition } from '../generated/definitions/gamepad-1.ts';
