/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GarlicFilledIcon } from '../generated/components/garlic-filled.tsx';
export { garlicFilledIconDefinition } from '../generated/definitions/garlic-filled.ts';
