/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GarlicIcon } from '../generated/components/garlic.tsx';
export { garlicIconDefinition } from '../generated/definitions/garlic.ts';
