/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureRanslationFilledIcon } from '../generated/components/gesture-ranslation-filled.tsx';
export { gestureRanslationFilledIconDefinition } from '../generated/definitions/gesture-ranslation-filled.ts';
