/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureUpAndDownFilledIcon } from '../generated/components/gesture-up-and-down-filled.tsx';
export { gestureUpAndDownFilledIconDefinition } from '../generated/definitions/gesture-up-and-down-filled.ts';
