/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureExpansionFilledIcon } from '../generated/components/gesture-expansion-filled.tsx';
export { gestureExpansionFilledIconDefinition } from '../generated/definitions/gesture-expansion-filled.ts';
