/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureApplauseIcon } from '../generated/components/gesture-applause.tsx';
export { gestureApplauseIconDefinition } from '../generated/definitions/gesture-applause.ts';
