/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GesturePrayFilledIcon } from '../generated/components/gesture-pray-filled.tsx';
export { gesturePrayFilledIconDefinition } from '../generated/definitions/gesture-pray-filled.ts';
