/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GesturePressIcon } from '../generated/components/gesture-press.tsx';
export { gesturePressIconDefinition } from '../generated/definitions/gesture-press.ts';
