/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureWipeDownIcon } from '../generated/components/gesture-wipe-down.tsx';
export { gestureWipeDownIconDefinition } from '../generated/definitions/gesture-wipe-down.ts';
