/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureLeftSlipFilledIcon } from '../generated/components/gesture-left-slip-filled.tsx';
export { gestureLeftSlipFilledIconDefinition } from '../generated/definitions/gesture-left-slip-filled.ts';
