/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureUpAndDownIcon } from '../generated/components/gesture-up-and-down.tsx';
export { gestureUpAndDownIconDefinition } from '../generated/definitions/gesture-up-and-down.ts';
