/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureDownIcon } from '../generated/components/gesture-down.tsx';
export { gestureDownIconDefinition } from '../generated/definitions/gesture-down.ts';
