/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureRightSlipFilledIcon } from '../generated/components/gesture-right-slip-filled.tsx';
export { gestureRightSlipFilledIconDefinition } from '../generated/definitions/gesture-right-slip-filled.ts';
