/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureDownFilledIcon } from '../generated/components/gesture-down-filled.tsx';
export { gestureDownFilledIconDefinition } from '../generated/definitions/gesture-down-filled.ts';
