/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureRightIcon } from '../generated/components/gesture-right.tsx';
export { gestureRightIconDefinition } from '../generated/definitions/gesture-right.ts';
