/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureExpansionIcon } from '../generated/components/gesture-expansion.tsx';
export { gestureExpansionIconDefinition } from '../generated/definitions/gesture-expansion.ts';
