/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureLeftSlipIcon } from '../generated/components/gesture-left-slip.tsx';
export { gestureLeftSlipIconDefinition } from '../generated/definitions/gesture-left-slip.ts';
