/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureClickIcon } from '../generated/components/gesture-click.tsx';
export { gestureClickIconDefinition } from '../generated/definitions/gesture-click.ts';
