/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GestureSlideLeftAndRightIcon } from '../generated/components/gesture-slide-left-and-right.tsx';
export { gestureSlideLeftAndRightIconDefinition } from '../generated/definitions/gesture-slide-left-and-right.ts';
