/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GiftIcon } from '../generated/components/gift.tsx';
export { giftIconDefinition } from '../generated/definitions/gift.ts';
