/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GiftFilledIcon } from '../generated/components/gift-filled.tsx';
export { giftFilledIconDefinition } from '../generated/definitions/gift-filled.ts';
