/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GiggleIcon } from '../generated/components/giggle.tsx';
export { giggleIconDefinition } from '../generated/definitions/giggle.ts';
