/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GitPullRequestFilledIcon } from '../generated/components/git-pull-request-filled.tsx';
export { gitPullRequestFilledIconDefinition } from '../generated/definitions/git-pull-request-filled.ts';
