/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GitRepositoryFilledIcon } from '../generated/components/git-repository-filled.tsx';
export { gitRepositoryFilledIconDefinition } from '../generated/definitions/git-repository-filled.ts';
