/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GitRepositoryCommitsFilledIcon } from '../generated/components/git-repository-commits-filled.tsx';
export { gitRepositoryCommitsFilledIconDefinition } from '../generated/definitions/git-repository-commits-filled.ts';
