/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GrapeFilledIcon } from '../generated/components/grape-filled.tsx';
export { grapeFilledIconDefinition } from '../generated/definitions/grape-filled.ts';
