/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GridViewFilledIcon } from '../generated/components/grid-view-filled.tsx';
export { gridViewFilledIconDefinition } from '../generated/definitions/grid-view-filled.ts';
