/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GridViewIcon } from '../generated/components/grid-view.tsx';
export { gridViewIconDefinition } from '../generated/definitions/grid-view.ts';
