/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GridAddFilledIcon } from '../generated/components/grid-add-filled.tsx';
export { gridAddFilledIconDefinition } from '../generated/definitions/grid-add-filled.ts';
