/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GridAddIcon } from '../generated/components/grid-add.tsx';
export { gridAddIconDefinition } from '../generated/definitions/grid-add.ts';
