/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GuitarFilledIcon } from '../generated/components/guitar-filled.tsx';
export { guitarFilledIconDefinition } from '../generated/definitions/guitar-filled.ts';
