/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { GuitarIcon } from '../generated/components/guitar.tsx';
export { guitarIconDefinition } from '../generated/definitions/guitar.ts';
