/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HappyFilledIcon } from '../generated/components/happy-filled.tsx';
export { happyFilledIconDefinition } from '../generated/definitions/happy-filled.ts';
