/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HardDriveFilledIcon } from '../generated/components/hard-drive-filled.tsx';
export { hardDriveFilledIconDefinition } from '../generated/definitions/hard-drive-filled.ts';
