/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HardDiskStorageIcon } from '../generated/components/hard-disk-storage.tsx';
export { hardDiskStorageIconDefinition } from '../generated/definitions/hard-disk-storage.ts';
