/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HardDiskStorageFilledIcon } from '../generated/components/hard-disk-storage-filled.tsx';
export { hardDiskStorageFilledIconDefinition } from '../generated/definitions/hard-disk-storage-filled.ts';
