/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HashtagIcon } from '../generated/components/hashtag.tsx';
export { hashtagIconDefinition } from '../generated/definitions/hashtag.ts';
