/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HelpIcon } from '../generated/components/help.tsx';
export { helpIconDefinition } from '../generated/definitions/help.ts';
