/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HelpCircleFilledIcon } from '../generated/components/help-circle-filled.tsx';
export { helpCircleFilledIconDefinition } from '../generated/definitions/help-circle-filled.ts';
