/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HighlightedBlockFilledIcon } from '../generated/components/highlighted-block-filled.tsx';
export { highlightedBlockFilledIconDefinition } from '../generated/definitions/highlighted-block-filled.ts';
