/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HighlightedBlockIcon } from '../generated/components/highlighted-block.tsx';
export { highlightedBlockIconDefinition } from '../generated/definitions/highlighted-block.ts';
