/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HighlightIcon } from '../generated/components/highlight.tsx';
export { highlightIconDefinition } from '../generated/definitions/highlight.ts';
