/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Highlight1FilledIcon } from '../generated/components/highlight-1-filled.tsx';
export { highlight1FilledIconDefinition } from '../generated/definitions/highlight-1-filled.ts';
