/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Highlight1Icon } from '../generated/components/highlight-1.tsx';
export { highlight1IconDefinition } from '../generated/definitions/highlight-1.ts';
