/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HighLevelFilledIcon } from '../generated/components/high-level-filled.tsx';
export { highLevelFilledIconDefinition } from '../generated/definitions/high-level-filled.ts';
