/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HistoryIcon } from '../generated/components/history.tsx';
export { historyIconDefinition } from '../generated/definitions/history.ts';
