/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HomeFilledIcon } from '../generated/components/home-filled.tsx';
export { homeFilledIconDefinition } from '../generated/definitions/home-filled.ts';
