/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HorizontalFilledIcon } from '../generated/components/horizontal-filled.tsx';
export { horizontalFilledIconDefinition } from '../generated/definitions/horizontal-filled.ts';
