/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Hospital1Icon } from '../generated/components/hospital-1.tsx';
export { hospital1IconDefinition } from '../generated/definitions/hospital-1.ts';
