/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HospitalIcon } from '../generated/components/hospital.tsx';
export { hospitalIconDefinition } from '../generated/definitions/hospital.ts';
