/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HotspotWaveIcon } from '../generated/components/hotspot-wave.tsx';
export { hotspotWaveIconDefinition } from '../generated/definitions/hotspot-wave.ts';
