/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HourglassFilledIcon } from '../generated/components/hourglass-filled.tsx';
export { hourglassFilledIconDefinition } from '../generated/definitions/hourglass-filled.ts';
