/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HousesFilledIcon } from '../generated/components/houses-filled.tsx';
export { housesFilledIconDefinition } from '../generated/definitions/houses-filled.ts';
