/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Houses2Icon } from '../generated/components/houses-2.tsx';
export { houses2IconDefinition } from '../generated/definitions/houses-2.ts';
