/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Houses2FilledIcon } from '../generated/components/houses-2-filled.tsx';
export { houses2FilledIconDefinition } from '../generated/definitions/houses-2-filled.ts';
