/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HousesIcon } from '../generated/components/houses.tsx';
export { housesIconDefinition } from '../generated/definitions/houses.ts';
