/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Html5Icon } from '../generated/components/html5.tsx';
export { html5IconDefinition } from '../generated/definitions/html5.ts';
