/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { HttpsIcon } from '../generated/components/https.tsx';
export { httpsIconDefinition } from '../generated/definitions/https.ts';
