/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { IconIcon } from '../generated/components/icon.tsx';
export { iconIconDefinition } from '../generated/definitions/icon.ts';
