/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageAddFilledIcon } from '../generated/components/image-add-filled.tsx';
export { imageAddFilledIconDefinition } from '../generated/definitions/image-add-filled.ts';
