/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageAddIcon } from '../generated/components/image-add.tsx';
export { imageAddIconDefinition } from '../generated/definitions/image-add.ts';
