/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Image1FilledIcon } from '../generated/components/image-1-filled.tsx';
export { image1FilledIconDefinition } from '../generated/definitions/image-1-filled.ts';
