/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageFilledIcon } from '../generated/components/image-filled.tsx';
export { imageFilledIconDefinition } from '../generated/definitions/image-filled.ts';
