/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageSearchIcon } from '../generated/components/image-search.tsx';
export { imageSearchIconDefinition } from '../generated/definitions/image-search.ts';
