/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ImageErrorFilledIcon } from '../generated/components/image-error-filled.tsx';
export { imageErrorFilledIconDefinition } from '../generated/definitions/image-error-filled.ts';
