/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { IndentRightIcon } from '../generated/components/indent-right.tsx';
export { indentRightIconDefinition } from '../generated/definitions/indent-right.ts';
