/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InfoCircleIcon } from '../generated/components/info-circle.tsx';
export { infoCircleIconDefinition } from '../generated/definitions/info-circle.ts';
