/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InfoCircleFilledIcon } from '../generated/components/info-circle-filled.tsx';
export { infoCircleFilledIconDefinition } from '../generated/definitions/info-circle-filled.ts';
