/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InstitutionCheckedFilledIcon } from '../generated/components/institution-checked-filled.tsx';
export { institutionCheckedFilledIconDefinition } from '../generated/definitions/institution-checked-filled.ts';
