/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InstallDesktopFilledIcon } from '../generated/components/install-desktop-filled.tsx';
export { installDesktopFilledIconDefinition } from '../generated/definitions/install-desktop-filled.ts';
