/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { InternetIcon } from '../generated/components/internet.tsx';
export { internetIconDefinition } from '../generated/definitions/internet.ts';
