/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { JapaneseRectangleFilledIcon } from '../generated/components/japanese-rectangle-filled.tsx';
export { japaneseRectangleFilledIconDefinition } from '../generated/definitions/japanese-rectangle-filled.ts';
