/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { JumpDoubleIcon } from '../generated/components/jump-double.tsx';
export { jumpDoubleIconDefinition } from '../generated/definitions/jump-double.ts';
