/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { KeyIcon } from '../generated/components/key.tsx';
export { keyIconDefinition } from '../generated/definitions/key.ts';
