/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { KoreanRectangleFilledIcon } from '../generated/components/korean-rectangle-filled.tsx';
export { koreanRectangleFilledIconDefinition } from '../generated/definitions/korean-rectangle-filled.ts';
