/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LaptopFilledIcon } from '../generated/components/laptop-filled.tsx';
export { laptopFilledIconDefinition } from '../generated/definitions/laptop-filled.ts';
