/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LayersIcon } from '../generated/components/layers.tsx';
export { layersIconDefinition } from '../generated/definitions/layers.ts';
