/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LayoutFilledIcon } from '../generated/components/layout-filled.tsx';
export { layoutFilledIconDefinition } from '../generated/definitions/layout-filled.ts';
