/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LeaderboardIcon } from '../generated/components/leaderboard.tsx';
export { leaderboardIconDefinition } from '../generated/definitions/leaderboard.ts';
