/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LemonSliceIcon } from '../generated/components/lemon-slice.tsx';
export { lemonSliceIconDefinition } from '../generated/definitions/lemon-slice.ts';
