/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LemonIcon } from '../generated/components/lemon.tsx';
export { lemonIconDefinition } from '../generated/definitions/lemon.ts';
