/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LessThanIcon } from '../generated/components/less-than.tsx';
export { lessThanIconDefinition } from '../generated/definitions/less-than.ts';
