/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersVIcon } from '../generated/components/letters-v.tsx';
export { lettersVIconDefinition } from '../generated/definitions/letters-v.ts';
