/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersJIcon } from '../generated/components/letters-j.tsx';
export { lettersJIconDefinition } from '../generated/definitions/letters-j.ts';
