/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersHIcon } from '../generated/components/letters-h.tsx';
export { lettersHIconDefinition } from '../generated/definitions/letters-h.ts';
