/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersSIcon } from '../generated/components/letters-s.tsx';
export { lettersSIconDefinition } from '../generated/definitions/letters-s.ts';
