/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersIIcon } from '../generated/components/letters-i.tsx';
export { lettersIIconDefinition } from '../generated/definitions/letters-i.ts';
