/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersTIcon } from '../generated/components/letters-t.tsx';
export { lettersTIconDefinition } from '../generated/definitions/letters-t.ts';
