/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersAIcon } from '../generated/components/letters-a.tsx';
export { lettersAIconDefinition } from '../generated/definitions/letters-a.ts';
