/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersFIcon } from '../generated/components/letters-f.tsx';
export { lettersFIconDefinition } from '../generated/definitions/letters-f.ts';
