/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LettersNIcon } from '../generated/components/letters-n.tsx';
export { lettersNIconDefinition } from '../generated/definitions/letters-n.ts';
