/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Lighthouse1FilledIcon } from '../generated/components/lighthouse-1-filled.tsx';
export { lighthouse1FilledIconDefinition } from '../generated/definitions/lighthouse-1-filled.ts';
