/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LightingCircleFilledIcon } from '../generated/components/lighting-circle-filled.tsx';
export { lightingCircleFilledIconDefinition } from '../generated/definitions/lighting-circle-filled.ts';
