/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Lighthouse1Icon } from '../generated/components/lighthouse-1.tsx';
export { lighthouse1IconDefinition } from '../generated/definitions/lighthouse-1.ts';
