/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LineHeightIcon } from '../generated/components/line-height.tsx';
export { lineHeightIconDefinition } from '../generated/definitions/line-height.ts';
