/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ListBugIcon } from '../generated/components/list-bug.tsx';
export { listBugIconDefinition } from '../generated/definitions/list-bug.ts';
