/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationParkingPlaceIcon } from '../generated/components/location-parking-place.tsx';
export { locationParkingPlaceIconDefinition } from '../generated/definitions/location-parking-place.ts';
