/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationEnlargementFilledIcon } from '../generated/components/location-enlargement-filled.tsx';
export { locationEnlargementFilledIconDefinition } from '../generated/definitions/location-enlargement-filled.ts';
