/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationParkingPlaceFilledIcon } from '../generated/components/location-parking-place-filled.tsx';
export { locationParkingPlaceFilledIconDefinition } from '../generated/definitions/location-parking-place-filled.ts';
