/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LocationReductionIcon } from '../generated/components/location-reduction.tsx';
export { locationReductionIconDefinition } from '../generated/definitions/location-reduction.ts';
