/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LockOnIcon } from '../generated/components/lock-on.tsx';
export { lockOnIconDefinition } from '../generated/definitions/lock-on.ts';
