/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LockTimeIcon } from '../generated/components/lock-time.tsx';
export { lockTimeIconDefinition } from '../generated/definitions/lock-time.ts';
