/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoWecomFilledIcon } from '../generated/components/logo-wecom-filled.tsx';
export { logoWecomFilledIconDefinition } from '../generated/definitions/logo-wecom-filled.ts';
