/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoWechatWorkdocsFilledIcon } from '../generated/components/logo-wechat-workdocs-filled.tsx';
export { logoWechatWorkdocsFilledIconDefinition } from '../generated/definitions/logo-wechat-workdocs-filled.ts';
