/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCodesignIcon } from '../generated/components/logo-codesign.tsx';
export { logoCodesignIconDefinition } from '../generated/definitions/logo-codesign.ts';
