/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoHiflowIcon } from '../generated/components/logo-hiflow.tsx';
export { logoHiflowIconDefinition } from '../generated/definitions/logo-hiflow.ts';
