/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAlipayFilledIcon } from '../generated/components/logo-alipay-filled.tsx';
export { logoAlipayFilledIconDefinition } from '../generated/definitions/logo-alipay-filled.ts';
