/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoIwikiFilledIcon } from '../generated/components/logo-iwiki-filled.tsx';
export { logoIwikiFilledIconDefinition } from '../generated/definitions/logo-iwiki-filled.ts';
