/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTwitterFilledIcon } from '../generated/components/logo-twitter-filled.tsx';
export { logoTwitterFilledIconDefinition } from '../generated/definitions/logo-twitter-filled.ts';
