/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCinema4dIcon } from '../generated/components/logo-cinema4d.tsx';
export { logoCinema4dIconDefinition } from '../generated/definitions/logo-cinema4d.ts';
