/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoWechatStrokeIcon } from '../generated/components/logo-wechat-stroke.tsx';
export { logoWechatStrokeIconDefinition } from '../generated/definitions/logo-wechat-stroke.ts';
