/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCinema4dFilledIcon } from '../generated/components/logo-cinema4d-filled.tsx';
export { logoCinema4dFilledIconDefinition } from '../generated/definitions/logo-cinema4d-filled.ts';
