/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoYoutubeFilledIcon } from '../generated/components/logo-youtube-filled.tsx';
export { logoYoutubeFilledIconDefinition } from '../generated/definitions/logo-youtube-filled.ts';
