/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoCodesandboxIcon } from '../generated/components/logo-codesandbox.tsx';
export { logoCodesandboxIconDefinition } from '../generated/definitions/logo-codesandbox.ts';
