/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFacebookIcon } from '../generated/components/logo-facebook.tsx';
export { logoFacebookIconDefinition } from '../generated/definitions/logo-facebook.ts';
