/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoChromeFilledIcon } from '../generated/components/logo-chrome-filled.tsx';
export { logoChromeFilledIconDefinition } from '../generated/definitions/logo-chrome-filled.ts';
