/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTencentmeetingFilledIcon } from '../generated/components/logo-tencentmeeting-filled.tsx';
export { logoTencentmeetingFilledIconDefinition } from '../generated/definitions/logo-tencentmeeting-filled.ts';
