/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTencentcodeIcon } from '../generated/components/logo-tencentcode.tsx';
export { logoTencentcodeIconDefinition } from '../generated/definitions/logo-tencentcode.ts';
