/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFigmaIcon } from '../generated/components/logo-figma.tsx';
export { logoFigmaIconDefinition } from '../generated/definitions/logo-figma.ts';
