/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTdesignIcon } from '../generated/components/logo-tdesign.tsx';
export { logoTdesignIconDefinition } from '../generated/definitions/logo-tdesign.ts';
