/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoStackblitzFilledIcon } from '../generated/components/logo-stackblitz-filled.tsx';
export { logoStackblitzFilledIconDefinition } from '../generated/definitions/logo-stackblitz-filled.ts';
