/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoQqFilledIcon } from '../generated/components/logo-qq-filled.tsx';
export { logoQqFilledIconDefinition } from '../generated/definitions/logo-qq-filled.ts';
