/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoMiniprogramFilledIcon } from '../generated/components/logo-miniprogram-filled.tsx';
export { logoMiniprogramFilledIconDefinition } from '../generated/definitions/logo-miniprogram-filled.ts';
