/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAdobeLightroomFilledIcon } from '../generated/components/logo-adobe-lightroom-filled.tsx';
export { logoAdobeLightroomFilledIconDefinition } from '../generated/definitions/logo-adobe-lightroom-filled.ts';
