/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoXiaomareportIcon } from '../generated/components/logo-xiaomareport.tsx';
export { logoXiaomareportIconDefinition } from '../generated/definitions/logo-xiaomareport.ts';
