/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoDribbbleIcon } from '../generated/components/logo-dribbble.tsx';
export { logoDribbbleIconDefinition } from '../generated/definitions/logo-dribbble.ts';
