/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFramerIcon } from '../generated/components/logo-framer.tsx';
export { logoFramerIconDefinition } from '../generated/definitions/logo-framer.ts';
