/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAlipayIcon } from '../generated/components/logo-alipay.tsx';
export { logoAlipayIconDefinition } from '../generated/definitions/logo-alipay.ts';
