/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTapdIcon } from '../generated/components/logo-tapd.tsx';
export { logoTapdIconDefinition } from '../generated/definitions/logo-tapd.ts';
