/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFigmaFilledIcon } from '../generated/components/logo-figma-filled.tsx';
export { logoFigmaFilledIconDefinition } from '../generated/definitions/logo-figma-filled.ts';
