/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoAndroidIcon } from '../generated/components/logo-android.tsx';
export { logoAndroidIconDefinition } from '../generated/definitions/logo-android.ts';
