/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTbeaconIcon } from '../generated/components/logo-tbeacon.tsx';
export { logoTbeaconIconDefinition } from '../generated/definitions/logo-tbeacon.ts';
