/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoInstagramFilledIcon } from '../generated/components/logo-instagram-filled.tsx';
export { logoInstagramFilledIconDefinition } from '../generated/definitions/logo-instagram-filled.ts';
