/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoTdesignFilledIcon } from '../generated/components/logo-tdesign-filled.tsx';
export { logoTdesignFilledIconDefinition } from '../generated/definitions/logo-tdesign-filled.ts';
