/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { LogoFacebookFilledIcon } from '../generated/components/logo-facebook-filled.tsx';
export { logoFacebookFilledIconDefinition } from '../generated/definitions/logo-facebook-filled.ts';
