/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapConnectionIcon } from '../generated/components/map-connection.tsx';
export { mapConnectionIconDefinition } from '../generated/definitions/map-connection.ts';
