/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapNavigationFilledIcon } from '../generated/components/map-navigation-filled.tsx';
export { mapNavigationFilledIconDefinition } from '../generated/definitions/map-navigation-filled.ts';
