/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapBubbleFilledIcon } from '../generated/components/map-bubble-filled.tsx';
export { mapBubbleFilledIconDefinition } from '../generated/definitions/map-bubble-filled.ts';
