/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapDistanceIcon } from '../generated/components/map-distance.tsx';
export { mapDistanceIconDefinition } from '../generated/definitions/map-distance.ts';
