/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSafetyIcon } from '../generated/components/map-safety.tsx';
export { mapSafetyIconDefinition } from '../generated/definitions/map-safety.ts';
