/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapOutlineFilledIcon } from '../generated/components/map-outline-filled.tsx';
export { mapOutlineFilledIconDefinition } from '../generated/definitions/map-outline-filled.ts';
