/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapRoutePlanningFilledIcon } from '../generated/components/map-route-planning-filled.tsx';
export { mapRoutePlanningFilledIconDefinition } from '../generated/definitions/map-route-planning-filled.ts';
