/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSettingIcon } from '../generated/components/map-setting.tsx';
export { mapSettingIconDefinition } from '../generated/definitions/map-setting.ts';
