/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapDoubleFilledIcon } from '../generated/components/map-double-filled.tsx';
export { mapDoubleFilledIconDefinition } from '../generated/definitions/map-double-filled.ts';
