/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSearchFilledIcon } from '../generated/components/map-search-filled.tsx';
export { mapSearchFilledIconDefinition } from '../generated/definitions/map-search-filled.ts';
