/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapRulerIcon } from '../generated/components/map-ruler.tsx';
export { mapRulerIconDefinition } from '../generated/definitions/map-ruler.ts';
