/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformation2FilledIcon } from '../generated/components/map-information-2-filled.tsx';
export { mapInformation2FilledIconDefinition } from '../generated/definitions/map-information-2-filled.ts';
