/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapSearch1FilledIcon } from '../generated/components/map-search-1-filled.tsx';
export { mapSearch1FilledIconDefinition } from '../generated/definitions/map-search-1-filled.ts';
