/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformation2Icon } from '../generated/components/map-information-2.tsx';
export { mapInformation2IconDefinition } from '../generated/definitions/map-information-2.ts';
