/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapBlockedIcon } from '../generated/components/map-blocked.tsx';
export { mapBlockedIconDefinition } from '../generated/definitions/map-blocked.ts';
