/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapInformationFilledIcon } from '../generated/components/map-information-filled.tsx';
export { mapInformationFilledIconDefinition } from '../generated/definitions/map-information-filled.ts';
