/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapConnectionFilledIcon } from '../generated/components/map-connection-filled.tsx';
export { mapConnectionFilledIconDefinition } from '../generated/definitions/map-connection-filled.ts';
