/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Map3dIcon } from '../generated/components/map-3d.tsx';
export { map3dIconDefinition } from '../generated/definitions/map-3d.ts';
