/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapNavigationIcon } from '../generated/components/map-navigation.tsx';
export { mapNavigationIconDefinition } from '../generated/definitions/map-navigation.ts';
