/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MapIcon } from '../generated/components/map.tsx';
export { mapIconDefinition } from '../generated/definitions/map.ts';
