/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MarkupFilledIcon } from '../generated/components/markup-filled.tsx';
export { markupFilledIconDefinition } from '../generated/definitions/markup-filled.ts';
