/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MarkupIcon } from '../generated/components/markup.tsx';
export { markupIconDefinition } from '../generated/definitions/markup.ts';
