/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MarkAsUnreadIcon } from '../generated/components/mark-as-unread.tsx';
export { markAsUnreadIconDefinition } from '../generated/definitions/mark-as-unread.ts';
