/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MarkAsUnreadFilledIcon } from '../generated/components/mark-as-unread-filled.tsx';
export { markAsUnreadFilledIconDefinition } from '../generated/definitions/mark-as-unread-filled.ts';
