/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Measurement1FilledIcon } from '../generated/components/measurement-1-filled.tsx';
export { measurement1FilledIconDefinition } from '../generated/definitions/measurement-1-filled.ts';
