/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Measurement2Icon } from '../generated/components/measurement-2.tsx';
export { measurement2IconDefinition } from '../generated/definitions/measurement-2.ts';
