/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MeatPepperIcon } from '../generated/components/meat-pepper.tsx';
export { meatPepperIconDefinition } from '../generated/definitions/meat-pepper.ts';
