/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MeatPepperFilledIcon } from '../generated/components/meat-pepper-filled.tsx';
export { meatPepperFilledIconDefinition } from '../generated/definitions/meat-pepper-filled.ts';
