/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MemberIcon } from '../generated/components/member.tsx';
export { memberIconDefinition } from '../generated/definitions/member.ts';
