/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MenuApplicationIcon } from '../generated/components/menu-application.tsx';
export { menuApplicationIconDefinition } from '../generated/definitions/menu-application.ts';
