/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MenuFilledIcon } from '../generated/components/menu-filled.tsx';
export { menuFilledIconDefinition } from '../generated/definitions/menu-filled.ts';
