/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MergeCellsFilledIcon } from '../generated/components/merge-cells-filled.tsx';
export { mergeCellsFilledIconDefinition } from '../generated/definitions/merge-cells-filled.ts';
