/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MermaidIcon } from '../generated/components/mermaid.tsx';
export { mermaidIconDefinition } from '../generated/definitions/mermaid.ts';
