/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MilkIcon } from '../generated/components/milk.tsx';
export { milkIconDefinition } from '../generated/definitions/milk.ts';
