/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MindMapIcon } from '../generated/components/mind-map.tsx';
export { mindMapIconDefinition } from '../generated/definitions/mind-map.ts';
