/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MirrorFilledIcon } from '../generated/components/mirror-filled.tsx';
export { mirrorFilledIconDefinition } from '../generated/definitions/mirror-filled.ts';
