/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MobileShortcutIcon } from '../generated/components/mobile-shortcut.tsx';
export { mobileShortcutIconDefinition } from '../generated/definitions/mobile-shortcut.ts';
