/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModeDarkIcon } from '../generated/components/mode-dark.tsx';
export { modeDarkIconDefinition } from '../generated/definitions/mode-dark.ts';
