/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModeEmbeddingFilledIcon } from '../generated/components/mode-embedding-filled.tsx';
export { modeEmbeddingFilledIconDefinition } from '../generated/definitions/mode-embedding-filled.ts';
