/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModuleIcon } from '../generated/components/module.tsx';
export { moduleIconDefinition } from '../generated/definitions/module.ts';
