/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ModuleFilledIcon } from '../generated/components/module-filled.tsx';
export { moduleFilledIconDefinition } from '../generated/definitions/module-filled.ts';
