/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoneyIcon } from '../generated/components/money.tsx';
export { moneyIconDefinition } from '../generated/definitions/money.ts';
