/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoneyFilledIcon } from '../generated/components/money-filled.tsx';
export { moneyFilledIconDefinition } from '../generated/definitions/money-filled.ts';
