/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MonumentIcon } from '../generated/components/monument.tsx';
export { monumentIconDefinition } from '../generated/definitions/monument.ts';
