/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoonFallIcon } from '../generated/components/moon-fall.tsx';
export { moonFallIconDefinition } from '../generated/definitions/moon-fall.ts';
