/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoonFilledIcon } from '../generated/components/moon-filled.tsx';
export { moonFilledIconDefinition } from '../generated/definitions/moon-filled.ts';
