/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoonIcon } from '../generated/components/moon.tsx';
export { moonIconDefinition } from '../generated/definitions/moon.ts';
