/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MouseFilledIcon } from '../generated/components/mouse-filled.tsx';
export { mouseFilledIconDefinition } from '../generated/definitions/mouse-filled.ts';
