/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MoveIcon } from '../generated/components/move.tsx';
export { moveIconDefinition } from '../generated/definitions/move.ts';
