/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MovieClapperFilledIcon } from '../generated/components/movie-clapper-filled.tsx';
export { movieClapperFilledIconDefinition } from '../generated/definitions/movie-clapper-filled.ts';
