/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MuseumFilledIcon } from '../generated/components/museum-filled.tsx';
export { museumFilledIconDefinition } from '../generated/definitions/museum-filled.ts';
