/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MushroomFilledIcon } from '../generated/components/mushroom-filled.tsx';
export { mushroomFilledIconDefinition } from '../generated/definitions/mushroom-filled.ts';
