/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Mushroom1FilledIcon } from '../generated/components/mushroom-1-filled.tsx';
export { mushroom1FilledIconDefinition } from '../generated/definitions/mushroom-1-filled.ts';
