/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Mushroom1Icon } from '../generated/components/mushroom-1.tsx';
export { mushroom1IconDefinition } from '../generated/definitions/mushroom-1.ts';
