/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Music2Icon } from '../generated/components/music-2.tsx';
export { music2IconDefinition } from '../generated/definitions/music-2.ts';
