/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Music2FilledIcon } from '../generated/components/music-2-filled.tsx';
export { music2FilledIconDefinition } from '../generated/definitions/music-2-filled.ts';
