/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { MusicFilledIcon } from '../generated/components/music-filled.tsx';
export { musicFilledIconDefinition } from '../generated/definitions/music-filled.ts';
