/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NavigationArrowIcon } from '../generated/components/navigation-arrow.tsx';
export { navigationArrowIconDefinition } from '../generated/definitions/navigation-arrow.ts';
