/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NextFilledIcon } from '../generated/components/next-filled.tsx';
export { nextFilledIconDefinition } from '../generated/definitions/next-filled.ts';
