/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NoExpressionIcon } from '../generated/components/no-expression.tsx';
export { noExpressionIconDefinition } from '../generated/definitions/no-expression.ts';
