/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NoodleFilledIcon } from '../generated/components/noodle-filled.tsx';
export { noodleFilledIconDefinition } from '../generated/definitions/noodle-filled.ts';
