/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NoodleIcon } from '../generated/components/noodle.tsx';
export { noodleIconDefinition } from '../generated/definitions/noodle.ts';
