/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NotificationFilledIcon } from '../generated/components/notification-filled.tsx';
export { notificationFilledIconDefinition } from '../generated/definitions/notification-filled.ts';
