/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NotificationCircleFilledIcon } from '../generated/components/notification-circle-filled.tsx';
export { notificationCircleFilledIconDefinition } from '../generated/definitions/notification-circle-filled.ts';
