/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NotificationIcon } from '../generated/components/notification.tsx';
export { notificationIconDefinition } from '../generated/definitions/notification.ts';
