/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NotificationCircleIcon } from '../generated/components/notification-circle.tsx';
export { notificationCircleIconDefinition } from '../generated/definitions/notification-circle.ts';
