/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers9Icon } from '../generated/components/numbers-9.tsx';
export { numbers9IconDefinition } from '../generated/definitions/numbers-9.ts';
