/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NumbersCircle4FilledIcon } from '../generated/components/numbers-circle-4-filled.tsx';
export { numbersCircle4FilledIconDefinition } from '../generated/definitions/numbers-circle-4-filled.ts';
