/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NumbersCircle1FilledIcon } from '../generated/components/numbers-circle-1-filled.tsx';
export { numbersCircle1FilledIconDefinition } from '../generated/definitions/numbers-circle-1-filled.ts';
