/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers6Icon } from '../generated/components/numbers-6.tsx';
export { numbers6IconDefinition } from '../generated/definitions/numbers-6.ts';
