/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers61Icon } from '../generated/components/numbers-6-1.tsx';
export { numbers61IconDefinition } from '../generated/definitions/numbers-6-1.ts';
