/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers8Icon } from '../generated/components/numbers-8.tsx';
export { numbers8IconDefinition } from '../generated/definitions/numbers-8.ts';
