/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers41Icon } from '../generated/components/numbers-4-1.tsx';
export { numbers41IconDefinition } from '../generated/definitions/numbers-4-1.ts';
