/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Numbers3Icon } from '../generated/components/numbers-3.tsx';
export { numbers3IconDefinition } from '../generated/definitions/numbers-3.ts';
