/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NumbersCircle2FilledIcon } from '../generated/components/numbers-circle-2-filled.tsx';
export { numbersCircle2FilledIconDefinition } from '../generated/definitions/numbers-circle-2-filled.ts';
