/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { NutFilledIcon } from '../generated/components/nut-filled.tsx';
export { nutFilledIconDefinition } from '../generated/definitions/nut-filled.ts';
