/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ObjectStorageIcon } from '../generated/components/object-storage.tsx';
export { objectStorageIconDefinition } from '../generated/definitions/object-storage.ts';
