/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OperaFilledIcon } from '../generated/components/opera-filled.tsx';
export { operaFilledIconDefinition } from '../generated/definitions/opera-filled.ts';
