/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OrderDescendingIcon } from '../generated/components/order-descending.tsx';
export { orderDescendingIconDefinition } from '../generated/definitions/order-descending.ts';
