/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OrderListIcon } from '../generated/components/order-list.tsx';
export { orderListIconDefinition } from '../generated/definitions/order-list.ts';
