/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OrderAdjustmentColumnIcon } from '../generated/components/order-adjustment-column.tsx';
export { orderAdjustmentColumnIconDefinition } from '../generated/definitions/order-adjustment-column.ts';
