/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { OutboxIcon } from '../generated/components/outbox.tsx';
export { outboxIconDefinition } from '../generated/definitions/outbox.ts';
