/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PageFirstIcon } from '../generated/components/page-first.tsx';
export { pageFirstIconDefinition } from '../generated/definitions/page-first.ts';
