/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PageHeadFilledIcon } from '../generated/components/page-head-filled.tsx';
export { pageHeadFilledIconDefinition } from '../generated/definitions/page-head-filled.ts';
