/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PageHeadIcon } from '../generated/components/page-head.tsx';
export { pageHeadIconDefinition } from '../generated/definitions/page-head.ts';
