/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Palace3Icon } from '../generated/components/palace-3.tsx';
export { palace3IconDefinition } from '../generated/definitions/palace-3.ts';
