/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PalaceIcon } from '../generated/components/palace.tsx';
export { palaceIconDefinition } from '../generated/definitions/palace.ts';
