/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Palace3FilledIcon } from '../generated/components/palace-3-filled.tsx';
export { palace3FilledIconDefinition } from '../generated/definitions/palace-3-filled.ts';
