/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Palace1FilledIcon } from '../generated/components/palace-1-filled.tsx';
export { palace1FilledIconDefinition } from '../generated/definitions/palace-1-filled.ts';
