/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PalaceFilledIcon } from '../generated/components/palace-filled.tsx';
export { palaceFilledIconDefinition } from '../generated/definitions/palace-filled.ts';
