/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Palace1Icon } from '../generated/components/palace-1.tsx';
export { palace1IconDefinition } from '../generated/definitions/palace-1.ts';
