/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PaletteIcon } from '../generated/components/palette.tsx';
export { paletteIconDefinition } from '../generated/definitions/palette.ts';
