/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PaletteFilledIcon } from '../generated/components/palette-filled.tsx';
export { paletteFilledIconDefinition } from '../generated/definitions/palette-filled.ts';
