/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Palette1Icon } from '../generated/components/palette-1.tsx';
export { palette1IconDefinition } from '../generated/definitions/palette-1.ts';
