/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PanoramaVerticalIcon } from '../generated/components/panorama-vertical.tsx';
export { panoramaVerticalIconDefinition } from '../generated/definitions/panorama-vertical.ts';
