/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ParenthesesIcon } from '../generated/components/parentheses.tsx';
export { parenthesesIconDefinition } from '../generated/definitions/parentheses.ts';
