/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PasteFilledIcon } from '../generated/components/paste-filled.tsx';
export { pasteFilledIconDefinition } from '../generated/definitions/paste-filled.ts';
