/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PauseCircleStrokeIcon } from '../generated/components/pause-circle-stroke.tsx';
export { pauseCircleStrokeIconDefinition } from '../generated/definitions/pause-circle-stroke.ts';
