/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PearlOfTheOrientIcon } from '../generated/components/pearl-of-the-orient.tsx';
export { pearlOfTheOrientIconDefinition } from '../generated/definitions/pearl-of-the-orient.ts';
