/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PearIcon } from '../generated/components/pear.tsx';
export { pearIconDefinition } from '../generated/definitions/pear.ts';
