/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PearlOfTheOrientFilledIcon } from '../generated/components/pearl-of-the-orient-filled.tsx';
export { pearlOfTheOrientFilledIconDefinition } from '../generated/definitions/pearl-of-the-orient-filled.ts';
