/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenBallIcon } from '../generated/components/pen-ball.tsx';
export { penBallIconDefinition } from '../generated/definitions/pen-ball.ts';
