/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenMarkFilledIcon } from '../generated/components/pen-mark-filled.tsx';
export { penMarkFilledIconDefinition } from '../generated/definitions/pen-mark-filled.ts';
