/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenBallFilledIcon } from '../generated/components/pen-ball-filled.tsx';
export { penBallFilledIconDefinition } from '../generated/definitions/pen-ball-filled.ts';
