/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PenIcon } from '../generated/components/pen.tsx';
export { penIconDefinition } from '../generated/definitions/pen.ts';
