/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PendingIcon } from '../generated/components/pending.tsx';
export { pendingIconDefinition } from '../generated/definitions/pending.ts';
