/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PercentIcon } from '../generated/components/percent.tsx';
export { percentIconDefinition } from '../generated/definitions/percent.ts';
