/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PersonalInformationFilledIcon } from '../generated/components/personal-information-filled.tsx';
export { personalInformationFilledIconDefinition } from '../generated/definitions/personal-information-filled.ts';
