/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PhoneSearchFilledIcon } from '../generated/components/phone-search-filled.tsx';
export { phoneSearchFilledIconDefinition } from '../generated/definitions/phone-search-filled.ts';
