/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PhoneLockedFilledIcon } from '../generated/components/phone-locked-filled.tsx';
export { phoneLockedFilledIconDefinition } from '../generated/definitions/phone-locked-filled.ts';
