/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PhoneSearchIcon } from '../generated/components/phone-search.tsx';
export { phoneSearchIconDefinition } from '../generated/definitions/phone-search.ts';
