/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PinFilledIcon } from '../generated/components/pin-filled.tsx';
export { pinFilledIconDefinition } from '../generated/definitions/pin-filled.ts';
