/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PinIcon } from '../generated/components/pin.tsx';
export { pinIconDefinition } from '../generated/definitions/pin.ts';
