/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlaceholderIcon } from '../generated/components/placeholder.tsx';
export { placeholderIconDefinition } from '../generated/definitions/placeholder.ts';
