/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlaceholderFilledIcon } from '../generated/components/placeholder-filled.tsx';
export { placeholderFilledIconDefinition } from '../generated/definitions/placeholder-filled.ts';
