/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayRectangleFilledIcon } from '../generated/components/play-rectangle-filled.tsx';
export { playRectangleFilledIconDefinition } from '../generated/definitions/play-rectangle-filled.ts';
