/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayCircleIcon } from '../generated/components/play-circle.tsx';
export { playCircleIconDefinition } from '../generated/definitions/play-circle.ts';
