/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayChartIcon } from '../generated/components/play-chart.tsx';
export { playChartIconDefinition } from '../generated/definitions/play-chart.ts';
