/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayDemoFilledIcon } from '../generated/components/play-demo-filled.tsx';
export { playDemoFilledIconDefinition } from '../generated/definitions/play-demo-filled.ts';
