/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PlayCircleFilledIcon } from '../generated/components/play-circle-filled.tsx';
export { playCircleFilledIconDefinition } from '../generated/definitions/play-circle-filled.ts';
