/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PopsicleIcon } from '../generated/components/popsicle.tsx';
export { popsicleIconDefinition } from '../generated/definitions/popsicle.ts';
