/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PortraitIcon } from '../generated/components/portrait.tsx';
export { portraitIconDefinition } from '../generated/definitions/portrait.ts';
