/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PoutIcon } from '../generated/components/pout.tsx';
export { poutIconDefinition } from '../generated/definitions/pout.ts';
