/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PrintFilledIcon } from '../generated/components/print-filled.tsx';
export { printFilledIconDefinition } from '../generated/definitions/print-filled.ts';
