/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PrintIcon } from '../generated/components/print.tsx';
export { printIconDefinition } from '../generated/definitions/print.ts';
