/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PyramidIcon } from '../generated/components/pyramid.tsx';
export { pyramidIconDefinition } from '../generated/definitions/pyramid.ts';
