/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { PyramidFilledIcon } from '../generated/components/pyramid-filled.tsx';
export { pyramidFilledIconDefinition } from '../generated/definitions/pyramid-filled.ts';
