/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QuadraticIcon } from '../generated/components/quadratic.tsx';
export { quadraticIconDefinition } from '../generated/definitions/quadratic.ts';
