/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QuestionnaireIcon } from '../generated/components/questionnaire.tsx';
export { questionnaireIconDefinition } from '../generated/definitions/questionnaire.ts';
