/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QuestionnaireFilledIcon } from '../generated/components/questionnaire-filled.tsx';
export { questionnaireFilledIconDefinition } from '../generated/definitions/questionnaire-filled.ts';
