/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QueueFilledIcon } from '../generated/components/queue-filled.tsx';
export { queueFilledIconDefinition } from '../generated/definitions/queue-filled.ts';
