/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { QuoteIcon } from '../generated/components/quote.tsx';
export { quoteIconDefinition } from '../generated/definitions/quote.ts';
