/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RadarIcon } from '../generated/components/radar.tsx';
export { radarIconDefinition } from '../generated/definitions/radar.ts';
