/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RadishFilledIcon } from '../generated/components/radish-filled.tsx';
export { radishFilledIconDefinition } from '../generated/definitions/radish-filled.ts';
