/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Radio2Icon } from '../generated/components/radio-2.tsx';
export { radio2IconDefinition } from '../generated/definitions/radio-2.ts';
