/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RainHeavyIcon } from '../generated/components/rain-heavy.tsx';
export { rainHeavyIconDefinition } from '../generated/definitions/rain-heavy.ts';
