/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RainbowIcon } from '../generated/components/rainbow.tsx';
export { rainbowIconDefinition } from '../generated/definitions/rainbow.ts';
