/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RainLightFilledIcon } from '../generated/components/rain-light-filled.tsx';
export { rainLightFilledIconDefinition } from '../generated/definitions/rain-light-filled.ts';
