/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RainLightIcon } from '../generated/components/rain-light.tsx';
export { rainLightIconDefinition } from '../generated/definitions/rain-light.ts';
