/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RemoteWaveIcon } from '../generated/components/remote-wave.tsx';
export { remoteWaveIconDefinition } from '../generated/definitions/remote-wave.ts';
