/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RemoveIcon } from '../generated/components/remove.tsx';
export { removeIconDefinition } from '../generated/definitions/remove.ts';
