/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RiceFilledIcon } from '../generated/components/rice-filled.tsx';
export { riceFilledIconDefinition } from '../generated/definitions/rice-filled.ts';
