/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RiceIcon } from '../generated/components/rice.tsx';
export { riceIconDefinition } from '../generated/definitions/rice.ts';
