/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Robot1Icon } from '../generated/components/robot-1.tsx';
export { robot1IconDefinition } from '../generated/definitions/robot-1.ts';
