/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RollbackIcon } from '../generated/components/rollback.tsx';
export { rollbackIconDefinition } from '../generated/definitions/rollback.ts';
