/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RotationIcon } from '../generated/components/rotation.tsx';
export { rotationIconDefinition } from '../generated/definitions/rotation.ts';
