/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RotateIcon } from '../generated/components/rotate.tsx';
export { rotateIconDefinition } from '../generated/definitions/rotate.ts';
