/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RoundIcon } from '../generated/components/round.tsx';
export { roundIconDefinition } from '../generated/definitions/round.ts';
