/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RouterWaveFilledIcon } from '../generated/components/router-wave-filled.tsx';
export { routerWaveFilledIconDefinition } from '../generated/definitions/router-wave-filled.ts';
