/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { RssIcon } from '../generated/components/rss.tsx';
export { rssIconDefinition } from '../generated/definitions/rss.ts';
