/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SailingHotelIcon } from '../generated/components/sailing-hotel.tsx';
export { sailingHotelIconDefinition } from '../generated/definitions/sailing-hotel.ts';
