/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SailingHotelFilledIcon } from '../generated/components/sailing-hotel-filled.tsx';
export { sailingHotelFilledIconDefinition } from '../generated/definitions/sailing-hotel-filled.ts';
