/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SandwichIcon } from '../generated/components/sandwich.tsx';
export { sandwichIconDefinition } from '../generated/definitions/sandwich.ts';
