/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SaturationFilledIcon } from '../generated/components/saturation-filled.tsx';
export { saturationFilledIconDefinition } from '../generated/definitions/saturation-filled.ts';
