/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SausageFilledIcon } from '../generated/components/sausage-filled.tsx';
export { sausageFilledIconDefinition } from '../generated/definitions/sausage-filled.ts';
