/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SausageIcon } from '../generated/components/sausage.tsx';
export { sausageIconDefinition } from '../generated/definitions/sausage.ts';
