/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SaveFilledIcon } from '../generated/components/save-filled.tsx';
export { saveFilledIconDefinition } from '../generated/definitions/save-filled.ts';
