/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ScanIcon } from '../generated/components/scan.tsx';
export { scanIconDefinition } from '../generated/definitions/scan.ts';
