/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ScreenMirroringFilledIcon } from '../generated/components/screen-mirroring-filled.tsx';
export { screenMirroringFilledIconDefinition } from '../generated/definitions/screen-mirroring-filled.ts';
