/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ScreenMirroringIcon } from '../generated/components/screen-mirroring.tsx';
export { screenMirroringIconDefinition } from '../generated/definitions/screen-mirroring.ts';
