/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Screen4kIcon } from '../generated/components/screen-4k.tsx';
export { screen4kIconDefinition } from '../generated/definitions/screen-4k.ts';
