/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ScrollBarIcon } from '../generated/components/scroll-bar.tsx';
export { scrollBarIconDefinition } from '../generated/definitions/scroll-bar.ts';
