/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SealIcon } from '../generated/components/seal.tsx';
export { sealIconDefinition } from '../generated/definitions/seal.ts';
