/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SearchFilledIcon } from '../generated/components/search-filled.tsx';
export { searchFilledIconDefinition } from '../generated/definitions/search-filled.ts';
