/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SendIcon } from '../generated/components/send.tsx';
export { sendIconDefinition } from '../generated/definitions/send.ts';
