/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SendCancelIcon } from '../generated/components/send-cancel.tsx';
export { sendCancelIconDefinition } from '../generated/definitions/send-cancel.ts';
