/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Sensors2Icon } from '../generated/components/sensors-2.tsx';
export { sensors2IconDefinition } from '../generated/definitions/sensors-2.ts';
