/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Sensors1Icon } from '../generated/components/sensors-1.tsx';
export { sensors1IconDefinition } from '../generated/definitions/sensors-1.ts';
