/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SerenityIcon } from '../generated/components/serenity.tsx';
export { serenityIconDefinition } from '../generated/definitions/serenity.ts';
