/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShareIcon } from '../generated/components/share.tsx';
export { shareIconDefinition } from '../generated/definitions/share.ts';
