/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShareFilledIcon } from '../generated/components/share-filled.tsx';
export { shareFilledIconDefinition } from '../generated/definitions/share-filled.ts';
