/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SharpnessFilledIcon } from '../generated/components/sharpness-filled.tsx';
export { sharpnessFilledIconDefinition } from '../generated/definitions/sharpness-filled.ts';
