/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShieldErrorFilledIcon } from '../generated/components/shield-error-filled.tsx';
export { shieldErrorFilledIconDefinition } from '../generated/definitions/shield-error-filled.ts';
