/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShimenFilledIcon } from '../generated/components/shimen-filled.tsx';
export { shimenFilledIconDefinition } from '../generated/definitions/shimen-filled.ts';
