/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop5FilledIcon } from '../generated/components/shop-5-filled.tsx';
export { shop5FilledIconDefinition } from '../generated/definitions/shop-5-filled.ts';
