/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Shop4FilledIcon } from '../generated/components/shop-4-filled.tsx';
export { shop4FilledIconDefinition } from '../generated/definitions/shop-4-filled.ts';
