/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShopIcon } from '../generated/components/shop.tsx';
export { shopIconDefinition } from '../generated/definitions/shop.ts';
