/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShortcutIcon } from '../generated/components/shortcut.tsx';
export { shortcutIconDefinition } from '../generated/definitions/shortcut.ts';
