/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShrinkVerticalIcon } from '../generated/components/shrink-vertical.tsx';
export { shrinkVerticalIconDefinition } from '../generated/definitions/shrink-vertical.ts';
