/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShrinkHorizontalIcon } from '../generated/components/shrink-horizontal.tsx';
export { shrinkHorizontalIconDefinition } from '../generated/definitions/shrink-horizontal.ts';
