/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ShutterIcon } from '../generated/components/shutter.tsx';
export { shutterIconDefinition } from '../generated/definitions/shutter.ts';
