/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SinisterSmileIcon } from '../generated/components/sinister-smile.tsx';
export { sinisterSmileIconDefinition } from '../generated/definitions/sinister-smile.ts';
