/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SipFilledIcon } from '../generated/components/sip-filled.tsx';
export { sipFilledIconDefinition } from '../generated/definitions/sip-filled.ts';
