/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SipIcon } from '../generated/components/sip.tsx';
export { sipIconDefinition } from '../generated/definitions/sip.ts';
