/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SitemapIcon } from '../generated/components/sitemap.tsx';
export { sitemapIconDefinition } from '../generated/definitions/sitemap.ts';
