/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SizeChangeIcon } from '../generated/components/size-change.tsx';
export { sizeChangeIconDefinition } from '../generated/definitions/size-change.ts';
