/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SliceIcon } from '../generated/components/slice.tsx';
export { sliceIconDefinition } from '../generated/definitions/slice.ts';
