/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SneerIcon } from '../generated/components/sneer.tsx';
export { sneerIconDefinition } from '../generated/definitions/sneer.ts';
