/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SneerFilledIcon } from '../generated/components/sneer-filled.tsx';
export { sneerFilledIconDefinition } from '../generated/definitions/sneer-filled.ts';
