/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SnowflakeIcon } from '../generated/components/snowflake.tsx';
export { snowflakeIconDefinition } from '../generated/definitions/snowflake.ts';
