/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundMute1FilledIcon } from '../generated/components/sound-mute-1-filled.tsx';
export { soundMute1FilledIconDefinition } from '../generated/definitions/sound-mute-1-filled.ts';
