/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundFilledIcon } from '../generated/components/sound-filled.tsx';
export { soundFilledIconDefinition } from '../generated/definitions/sound-filled.ts';
