/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundUpIcon } from '../generated/components/sound-up.tsx';
export { soundUpIconDefinition } from '../generated/definitions/sound-up.ts';
