/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundHighFilledIcon } from '../generated/components/sound-high-filled.tsx';
export { soundHighFilledIconDefinition } from '../generated/definitions/sound-high-filled.ts';
