/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundDownFilledIcon } from '../generated/components/sound-down-filled.tsx';
export { soundDownFilledIconDefinition } from '../generated/definitions/sound-down-filled.ts';
