/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SoundHighIcon } from '../generated/components/sound-high.tsx';
export { soundHighIconDefinition } from '../generated/definitions/sound-high.ts';
