/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SpaceIcon } from '../generated/components/space.tsx';
export { spaceIconDefinition } from '../generated/definitions/space.ts';
