/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Speechless1Icon } from '../generated/components/speechless-1.tsx';
export { speechless1IconDefinition } from '../generated/definitions/speechless-1.ts';
