/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SpeechlessFilledIcon } from '../generated/components/speechless-filled.tsx';
export { speechlessFilledIconDefinition } from '../generated/definitions/speechless-filled.ts';
