/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StarIcon } from '../generated/components/star.tsx';
export { starIconDefinition } from '../generated/definitions/star.ts';
