/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StatueOfJesusIcon } from '../generated/components/statue-of-jesus.tsx';
export { statueOfJesusIconDefinition } from '../generated/definitions/statue-of-jesus.ts';
