/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StopCircleFilledIcon } from '../generated/components/stop-circle-filled.tsx';
export { stopCircleFilledIconDefinition } from '../generated/definitions/stop-circle-filled.ts';
