/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StopIcon } from '../generated/components/stop.tsx';
export { stopIconDefinition } from '../generated/definitions/stop.ts';
