/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StopCircleStrokeIcon } from '../generated/components/stop-circle-stroke.tsx';
export { stopCircleStrokeIconDefinition } from '../generated/definitions/stop-circle-stroke.ts';
