/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StopCircleStrokeFilledIcon } from '../generated/components/stop-circle-stroke-filled.tsx';
export { stopCircleStrokeFilledIconDefinition } from '../generated/definitions/stop-circle-stroke-filled.ts';
