/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StoreFilledIcon } from '../generated/components/store-filled.tsx';
export { storeFilledIconDefinition } from '../generated/definitions/store-filled.ts';
