/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StreetRoad1Icon } from '../generated/components/street-road-1.tsx';
export { streetRoad1IconDefinition } from '../generated/definitions/street-road-1.ts';
