/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { StreetRoadIcon } from '../generated/components/street-road.tsx';
export { streetRoadIconDefinition } from '../generated/definitions/street-road.ts';
