/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SubwayLineIcon } from '../generated/components/subway-line.tsx';
export { subwayLineIconDefinition } from '../generated/definitions/subway-line.ts';
