/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SubwayLineFilledIcon } from '../generated/components/subway-line-filled.tsx';
export { subwayLineFilledIconDefinition } from '../generated/definitions/subway-line-filled.ts';
