/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SummaryIcon } from '../generated/components/summary.tsx';
export { summaryIconDefinition } from '../generated/definitions/summary.ts';
