/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SunFallIcon } from '../generated/components/sun-fall.tsx';
export { sunFallIconDefinition } from '../generated/definitions/sun-fall.ts';
