/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SunnyIcon } from '../generated/components/sunny.tsx';
export { sunnyIconDefinition } from '../generated/definitions/sunny.ts';
