/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SunnyFilledIcon } from '../generated/components/sunny-filled.tsx';
export { sunnyFilledIconDefinition } from '../generated/definitions/sunny-filled.ts';
