/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SupportFilledIcon } from '../generated/components/support-filled.tsx';
export { supportFilledIconDefinition } from '../generated/definitions/support-filled.ts';
