/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SurprisedIcon } from '../generated/components/surprised.tsx';
export { surprisedIconDefinition } from '../generated/definitions/surprised.ts';
