/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SwapLeftIcon } from '../generated/components/swap-left.tsx';
export { swapLeftIconDefinition } from '../generated/definitions/swap-left.ts';
