/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SwapRightIcon } from '../generated/components/swap-right.tsx';
export { swapRightIconDefinition } from '../generated/definitions/swap-right.ts';
