/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SwapIcon } from '../generated/components/swap.tsx';
export { swapIconDefinition } from '../generated/definitions/swap.ts';
