/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Swear1FilledIcon } from '../generated/components/swear-1-filled.tsx';
export { swear1FilledIconDefinition } from '../generated/definitions/swear-1-filled.ts';
