/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Swear2Icon } from '../generated/components/swear-2.tsx';
export { swear2IconDefinition } from '../generated/definitions/swear-2.ts';
