/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemLogFilledIcon } from '../generated/components/system-log-filled.tsx';
export { systemLogFilledIconDefinition } from '../generated/definitions/system-log-filled.ts';
