/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemUnlockedFilledIcon } from '../generated/components/system-unlocked-filled.tsx';
export { systemUnlockedFilledIconDefinition } from '../generated/definitions/system-unlocked-filled.ts';
