/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemApplicationIcon } from '../generated/components/system-application.tsx';
export { systemApplicationIconDefinition } from '../generated/definitions/system-application.ts';
