/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemBlockedIcon } from '../generated/components/system-blocked.tsx';
export { systemBlockedIconDefinition } from '../generated/definitions/system-blocked.ts';
