/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { System3FilledIcon } from '../generated/components/system-3-filled.tsx';
export { system3FilledIconDefinition } from '../generated/definitions/system-3-filled.ts';
