/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemCoordinateFilledIcon } from '../generated/components/system-coordinate-filled.tsx';
export { systemCoordinateFilledIconDefinition } from '../generated/definitions/system-coordinate-filled.ts';
