/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemLockedIcon } from '../generated/components/system-locked.tsx';
export { systemLockedIconDefinition } from '../generated/definitions/system-locked.ts';
