/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemStorageIcon } from '../generated/components/system-storage.tsx';
export { systemStorageIconDefinition } from '../generated/definitions/system-storage.ts';
