/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemSearchFilledIcon } from '../generated/components/system-search-filled.tsx';
export { systemSearchFilledIconDefinition } from '../generated/definitions/system-search-filled.ts';
