/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemLogIcon } from '../generated/components/system-log.tsx';
export { systemLogIconDefinition } from '../generated/definitions/system-log.ts';
