/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemDeviceIcon } from '../generated/components/system-device.tsx';
export { systemDeviceIconDefinition } from '../generated/definitions/system-device.ts';
