/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemRegulationIcon } from '../generated/components/system-regulation.tsx';
export { systemRegulationIconDefinition } from '../generated/definitions/system-regulation.ts';
