/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemCodeFilledIcon } from '../generated/components/system-code-filled.tsx';
export { systemCodeFilledIconDefinition } from '../generated/definitions/system-code-filled.ts';
