/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { SystemInterfaceFilledIcon } from '../generated/components/system-interface-filled.tsx';
export { systemInterfaceFilledIconDefinition } from '../generated/definitions/system-interface-filled.ts';
