/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TabFilledIcon } from '../generated/components/tab-filled.tsx';
export { tabFilledIconDefinition } from '../generated/definitions/tab-filled.ts';
