/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TabIcon } from '../generated/components/tab.tsx';
export { tabIconDefinition } from '../generated/definitions/tab.ts';
