/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Table1FilledIcon } from '../generated/components/table-1-filled.tsx';
export { table1FilledIconDefinition } from '../generated/definitions/table-1-filled.ts';
