/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TableFilledIcon } from '../generated/components/table-filled.tsx';
export { tableFilledIconDefinition } from '../generated/definitions/table-filled.ts';
