/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TagFilledIcon } from '../generated/components/tag-filled.tsx';
export { tagFilledIconDefinition } from '../generated/definitions/tag-filled.ts';
