/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TangerinrIcon } from '../generated/components/tangerinr.tsx';
export { tangerinrIconDefinition } from '../generated/definitions/tangerinr.ts';
