/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TangerinrFilledIcon } from '../generated/components/tangerinr-filled.tsx';
export { tangerinrFilledIconDefinition } from '../generated/definitions/tangerinr-filled.ts';
