/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskErrorFilledIcon } from '../generated/components/task-error-filled.tsx';
export { taskErrorFilledIconDefinition } from '../generated/definitions/task-error-filled.ts';
