/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskIcon } from '../generated/components/task.tsx';
export { taskIconDefinition } from '../generated/definitions/task.ts';
