/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskCheckedFilledIcon } from '../generated/components/task-checked-filled.tsx';
export { taskCheckedFilledIconDefinition } from '../generated/definitions/task-checked-filled.ts';
