/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskAddIcon } from '../generated/components/task-add.tsx';
export { taskAddIconDefinition } from '../generated/definitions/task-add.ts';
