/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskCheckedIcon } from '../generated/components/task-checked.tsx';
export { taskCheckedIconDefinition } from '../generated/definitions/task-checked.ts';
