/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskErrorIcon } from '../generated/components/task-error.tsx';
export { taskErrorIconDefinition } from '../generated/definitions/task-error.ts';
