/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskSettingFilledIcon } from '../generated/components/task-setting-filled.tsx';
export { taskSettingFilledIconDefinition } from '../generated/definitions/task-setting-filled.ts';
