/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskFilledIcon } from '../generated/components/task-filled.tsx';
export { taskFilledIconDefinition } from '../generated/definitions/task-filled.ts';
