/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskAddFilledIcon } from '../generated/components/task-add-filled.tsx';
export { taskAddFilledIconDefinition } from '../generated/definitions/task-add-filled.ts';
