/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TaskTimeIcon } from '../generated/components/task-time.tsx';
export { taskTimeIconDefinition } from '../generated/definitions/task-time.ts';
