/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TeaFilledIcon } from '../generated/components/tea-filled.tsx';
export { teaFilledIconDefinition } from '../generated/definitions/tea-filled.ts';
