/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TempleIcon } from '../generated/components/temple.tsx';
export { templeIconDefinition } from '../generated/definitions/temple.ts';
