/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TerminalIcon } from '../generated/components/terminal.tsx';
export { terminalIconDefinition } from '../generated/definitions/terminal.ts';
