/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextIcon } from '../generated/components/text.tsx';
export { textIconDefinition } from '../generated/definitions/text.ts';
