/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextStyleIcon } from '../generated/components/text-style.tsx';
export { textStyleIconDefinition } from '../generated/definitions/text-style.ts';
