/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextDrawingFilledIcon } from '../generated/components/text-drawing-filled.tsx';
export { textDrawingFilledIconDefinition } from '../generated/definitions/text-drawing-filled.ts';
