/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TextformatLongerIcon } from '../generated/components/textformat-longer.tsx';
export { textformatLongerIconDefinition } from '../generated/definitions/textformat-longer.ts';
