/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TheatersIcon } from '../generated/components/theaters.tsx';
export { theatersIconDefinition } from '../generated/definitions/theaters.ts';
