/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbDown2Icon } from '../generated/components/thumb-down-2.tsx';
export { thumbDown2IconDefinition } from '../generated/definitions/thumb-down-2.ts';
