/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbUpFilledIcon } from '../generated/components/thumb-up-filled.tsx';
export { thumbUpFilledIconDefinition } from '../generated/definitions/thumb-up-filled.ts';
