/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbUp1Icon } from '../generated/components/thumb-up-1.tsx';
export { thumbUp1IconDefinition } from '../generated/definitions/thumb-up-1.ts';
