/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbDownFilledIcon } from '../generated/components/thumb-down-filled.tsx';
export { thumbDownFilledIconDefinition } from '../generated/definitions/thumb-down-filled.ts';
