/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbDown1Icon } from '../generated/components/thumb-down-1.tsx';
export { thumbDown1IconDefinition } from '../generated/definitions/thumb-down-1.ts';
