/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbUp2Icon } from '../generated/components/thumb-up-2.tsx';
export { thumbUp2IconDefinition } from '../generated/definitions/thumb-up-2.ts';
