/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThumbUp1FilledIcon } from '../generated/components/thumb-up-1-filled.tsx';
export { thumbUp1FilledIconDefinition } from '../generated/definitions/thumb-up-1-filled.ts';
