/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThunderstormIcon } from '../generated/components/thunderstorm.tsx';
export { thunderstormIconDefinition } from '../generated/definitions/thunderstorm.ts';
