/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThunderstormSunnyFilledIcon } from '../generated/components/thunderstorm-sunny-filled.tsx';
export { thunderstormSunnyFilledIconDefinition } from '../generated/definitions/thunderstorm-sunny-filled.ts';
