/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ThunderIcon } from '../generated/components/thunder.tsx';
export { thunderIconDefinition } from '../generated/definitions/thunder.ts';
