/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TicketIcon } from '../generated/components/ticket.tsx';
export { ticketIconDefinition } from '../generated/definitions/ticket.ts';
