/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TimeIcon } from '../generated/components/time.tsx';
export { timeIconDefinition } from '../generated/definitions/time.ts';
