/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TipsIcon } from '../generated/components/tips.tsx';
export { tipsIconDefinition } from '../generated/definitions/tips.ts';
