/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TipsFilledIcon } from '../generated/components/tips-filled.tsx';
export { tipsFilledIconDefinition } from '../generated/definitions/tips-filled.ts';
