/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TipsDoubleIcon } from '../generated/components/tips-double.tsx';
export { tipsDoubleIconDefinition } from '../generated/definitions/tips-double.ts';
