/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TowerIcon } from '../generated/components/tower.tsx';
export { towerIconDefinition } from '../generated/definitions/tower.ts';
