/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TowerClockIcon } from '../generated/components/tower-clock.tsx';
export { towerClockIconDefinition } from '../generated/definitions/tower-clock.ts';
