/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tower1FilledIcon } from '../generated/components/tower-1-filled.tsx';
export { tower1FilledIconDefinition } from '../generated/definitions/tower-1-filled.ts';
