/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tower2Icon } from '../generated/components/tower-2.tsx';
export { tower2IconDefinition } from '../generated/definitions/tower-2.ts';
