/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TowerFilledIcon } from '../generated/components/tower-filled.tsx';
export { towerFilledIconDefinition } from '../generated/definitions/tower-filled.ts';
