/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TowerClockFilledIcon } from '../generated/components/tower-clock-filled.tsx';
export { towerClockFilledIconDefinition } from '../generated/definitions/tower-clock-filled.ts';
