/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TownIcon } from '../generated/components/town.tsx';
export { townIconDefinition } from '../generated/definitions/town.ts';
