/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TrafficEventsFilledIcon } from '../generated/components/traffic-events-filled.tsx';
export { trafficEventsFilledIconDefinition } from '../generated/definitions/traffic-events-filled.ts';
