/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TrafficIcon } from '../generated/components/traffic.tsx';
export { trafficIconDefinition } from '../generated/definitions/traffic.ts';
