/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TransformIcon } from '../generated/components/transform.tsx';
export { transformIconDefinition } from '../generated/definitions/transform.ts';
