/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Transform3Icon } from '../generated/components/transform-3.tsx';
export { transform3IconDefinition } from '../generated/definitions/transform-3.ts';
