/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TranslateIcon } from '../generated/components/translate.tsx';
export { translateIconDefinition } from '../generated/definitions/translate.ts';
