/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Translate1Icon } from '../generated/components/translate-1.tsx';
export { translate1IconDefinition } from '../generated/definitions/translate-1.ts';
