/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeRoundDotVerticalFilledIcon } from '../generated/components/tree-round-dot-vertical-filled.tsx';
export { treeRoundDotVerticalFilledIconDefinition } from '../generated/definitions/tree-round-dot-vertical-filled.ts';
