/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeRoundDotIcon } from '../generated/components/tree-round-dot.tsx';
export { treeRoundDotIconDefinition } from '../generated/definitions/tree-round-dot.ts';
