/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeSquareDotVerticalIcon } from '../generated/components/tree-square-dot-vertical.tsx';
export { treeSquareDotVerticalIconDefinition } from '../generated/definitions/tree-square-dot-vertical.ts';
