/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeCatalogFilledIcon } from '../generated/components/tree-catalog-filled.tsx';
export { treeCatalogFilledIconDefinition } from '../generated/definitions/tree-catalog-filled.ts';
