/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TreeRoundDotVerticalIcon } from '../generated/components/tree-round-dot-vertical.tsx';
export { treeRoundDotVerticalIconDefinition } from '../generated/definitions/tree-round-dot-vertical.ts';
