/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TrendingUpIcon } from '../generated/components/trending-up.tsx';
export { trendingUpIconDefinition } from '../generated/definitions/trending-up.ts';
