/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Tv2Icon } from '../generated/components/tv-2.tsx';
export { tv2IconDefinition } from '../generated/definitions/tv-2.ts';
