/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TvIcon } from '../generated/components/tv.tsx';
export { tvIconDefinition } from '../generated/definitions/tv.ts';
