/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { TypographyIcon } from '../generated/components/typography.tsx';
export { typographyIconDefinition } from '../generated/definitions/typography.ts';
