/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Uncomfortable1Icon } from '../generated/components/uncomfortable-1.tsx';
export { uncomfortable1IconDefinition } from '../generated/definitions/uncomfortable-1.ts';
