/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UncomfortableIcon } from '../generated/components/uncomfortable.tsx';
export { uncomfortableIconDefinition } from '../generated/definitions/uncomfortable.ts';
