/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Uncomfortable2Icon } from '../generated/components/uncomfortable-2.tsx';
export { uncomfortable2IconDefinition } from '../generated/definitions/uncomfortable-2.ts';
