/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeTransactionFilledIcon } from '../generated/components/undertake-transaction-filled.tsx';
export { undertakeTransactionFilledIconDefinition } from '../generated/definitions/undertake-transaction-filled.ts';
