/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeTransactionIcon } from '../generated/components/undertake-transaction.tsx';
export { undertakeTransactionIconDefinition } from '../generated/definitions/undertake-transaction.ts';
