/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeHoldUpIcon } from '../generated/components/undertake-hold-up.tsx';
export { undertakeHoldUpIconDefinition } from '../generated/definitions/undertake-hold-up.ts';
