/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeEnvironmentProtectionFilledIcon } from '../generated/components/undertake-environment-protection-filled.tsx';
export { undertakeEnvironmentProtectionFilledIconDefinition } from '../generated/definitions/undertake-environment-protection-filled.ts';
