/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UndertakeHoldUpFilledIcon } from '../generated/components/undertake-hold-up-filled.tsx';
export { undertakeHoldUpFilledIconDefinition } from '../generated/definitions/undertake-hold-up-filled.ts';
