/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UnfoldLessIcon } from '../generated/components/unfold-less.tsx';
export { unfoldLessIconDefinition } from '../generated/definitions/unfold-less.ts';
