/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UninstallFilledIcon } from '../generated/components/uninstall-filled.tsx';
export { uninstallFilledIconDefinition } from '../generated/definitions/uninstall-filled.ts';
