/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UninstallIcon } from '../generated/components/uninstall.tsx';
export { uninstallIconDefinition } from '../generated/definitions/uninstall.ts';
