/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UpscaleIcon } from '../generated/components/upscale.tsx';
export { upscaleIconDefinition } from '../generated/definitions/upscale.ts';
