/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsbFilledIcon } from '../generated/components/usb-filled.tsx';
export { usbFilledIconDefinition } from '../generated/definitions/usb-filled.ts';
