/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserUnknownFilledIcon } from '../generated/components/user-unknown-filled.tsx';
export { userUnknownFilledIconDefinition } from '../generated/definitions/user-unknown-filled.ts';
