/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserSafetyIcon } from '../generated/components/user-safety.tsx';
export { userSafetyIconDefinition } from '../generated/definitions/user-safety.ts';
