/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserAddIcon } from '../generated/components/user-add.tsx';
export { userAddIconDefinition } from '../generated/definitions/user-add.ts';
