/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserTalkIcon } from '../generated/components/user-talk.tsx';
export { userTalkIconDefinition } from '../generated/definitions/user-talk.ts';
