/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserMarkedIcon } from '../generated/components/user-marked.tsx';
export { userMarkedIconDefinition } from '../generated/definitions/user-marked.ts';
