/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserIcon } from '../generated/components/user.tsx';
export { userIconDefinition } from '../generated/definitions/user.ts';
