/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserPasswordIcon } from '../generated/components/user-password.tsx';
export { userPasswordIconDefinition } from '../generated/definitions/user-password.ts';
