/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupClearIcon } from '../generated/components/usergroup-clear.tsx';
export { usergroupClearIconDefinition } from '../generated/definitions/usergroup-clear.ts';
