/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserSearchIcon } from '../generated/components/user-search.tsx';
export { userSearchIconDefinition } from '../generated/definitions/user-search.ts';
