/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowDownFilledIcon } from '../generated/components/user-arrow-down-filled.tsx';
export { userArrowDownFilledIconDefinition } from '../generated/definitions/user-arrow-down-filled.ts';
