/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserSettingFilledIcon } from '../generated/components/user-setting-filled.tsx';
export { userSettingFilledIconDefinition } from '../generated/definitions/user-setting-filled.ts';
