/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserVisibleFilledIcon } from '../generated/components/user-visible-filled.tsx';
export { userVisibleFilledIconDefinition } from '../generated/definitions/user-visible-filled.ts';
