/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserTransmitIcon } from '../generated/components/user-transmit.tsx';
export { userTransmitIconDefinition } from '../generated/definitions/user-transmit.ts';
