/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserTimeFilledIcon } from '../generated/components/user-time-filled.tsx';
export { userTimeFilledIconDefinition } from '../generated/definitions/user-time-filled.ts';
