/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupAddIcon } from '../generated/components/usergroup-add.tsx';
export { usergroupAddIconDefinition } from '../generated/definitions/usergroup-add.ts';
