/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserUnknownIcon } from '../generated/components/user-unknown.tsx';
export { userUnknownIconDefinition } from '../generated/definitions/user-unknown.ts';
