/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserInvisibleFilledIcon } from '../generated/components/user-invisible-filled.tsx';
export { userInvisibleFilledIconDefinition } from '../generated/definitions/user-invisible-filled.ts';
