/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserLockedFilledIcon } from '../generated/components/user-locked-filled.tsx';
export { userLockedFilledIconDefinition } from '../generated/definitions/user-locked-filled.ts';
