/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowUpIcon } from '../generated/components/user-arrow-up.tsx';
export { userArrowUpIconDefinition } from '../generated/definitions/user-arrow-up.ts';
