/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserTimeIcon } from '../generated/components/user-time.tsx';
export { userTimeIconDefinition } from '../generated/definitions/user-time.ts';
