/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserError1Icon } from '../generated/components/user-error-1.tsx';
export { userError1IconDefinition } from '../generated/definitions/user-error-1.ts';
