/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserVipIcon } from '../generated/components/user-vip.tsx';
export { userVipIconDefinition } from '../generated/definitions/user-vip.ts';
