/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserSettingIcon } from '../generated/components/user-setting.tsx';
export { userSettingIconDefinition } from '../generated/definitions/user-setting.ts';
