/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsercaseLinkIcon } from '../generated/components/usercase-link.tsx';
export { usercaseLinkIconDefinition } from '../generated/definitions/usercase-link.ts';
