/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UsergroupCircleFilledIcon } from '../generated/components/usergroup-circle-filled.tsx';
export { usergroupCircleFilledIconDefinition } from '../generated/definitions/usergroup-circle-filled.ts';
