/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserArrowRightIcon } from '../generated/components/user-arrow-right.tsx';
export { userArrowRightIconDefinition } from '../generated/definitions/user-arrow-right.ts';
