/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { UserUnlockedFilledIcon } from '../generated/components/user-unlocked-filled.tsx';
export { userUnlockedFilledIconDefinition } from '../generated/definitions/user-unlocked-filled.ts';
