/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VerifiedFilledIcon } from '../generated/components/verified-filled.tsx';
export { verifiedFilledIconDefinition } from '../generated/definitions/verified-filled.ts';
