/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VerifyIcon } from '../generated/components/verify.tsx';
export { verifyIconDefinition } from '../generated/definitions/verify.ts';
