/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VerifyFilledIcon } from '../generated/components/verify-filled.tsx';
export { verifyFilledIconDefinition } from '../generated/definitions/verify-filled.ts';
