/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCamera2Icon } from '../generated/components/video-camera-2.tsx';
export { videoCamera2IconDefinition } from '../generated/definitions/video-camera-2.ts';
