/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCamera1Icon } from '../generated/components/video-camera-1.tsx';
export { videoCamera1IconDefinition } from '../generated/definitions/video-camera-1.ts';
