/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraIcon } from '../generated/components/video-camera.tsx';
export { videoCameraIconDefinition } from '../generated/definitions/video-camera.ts';
