/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoLibraryFilledIcon } from '../generated/components/video-library-filled.tsx';
export { videoLibraryFilledIconDefinition } from '../generated/definitions/video-library-filled.ts';
