/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoFilledIcon } from '../generated/components/video-filled.tsx';
export { videoFilledIconDefinition } from '../generated/definitions/video-filled.ts';
