/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraOffFilledIcon } from '../generated/components/video-camera-off-filled.tsx';
export { videoCameraOffFilledIconDefinition } from '../generated/definitions/video-camera-off-filled.ts';
