/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VideoCameraDollarIcon } from '../generated/components/video-camera-dollar.tsx';
export { videoCameraDollarIconDefinition } from '../generated/definitions/video-camera-dollar.ts';
