/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewOrganizationIcon } from '../generated/components/view-organization.tsx';
export { viewOrganizationIconDefinition } from '../generated/definitions/view-organization.ts';
