/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewModuleIcon } from '../generated/components/view-module.tsx';
export { viewModuleIconDefinition } from '../generated/definitions/view-module.ts';
