/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ViewAgendaFilledIcon } from '../generated/components/view-agenda-filled.tsx';
export { viewAgendaFilledIconDefinition } from '../generated/definitions/view-agenda-filled.ts';
