/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { VisualRecognitionIcon } from '../generated/components/visual-recognition.tsx';
export { visualRecognitionIconDefinition } from '../generated/definitions/visual-recognition.ts';
