/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WalletFilledIcon } from '../generated/components/wallet-filled.tsx';
export { walletFilledIconDefinition } from '../generated/definitions/wallet-filled.ts';
