/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WalletIcon } from '../generated/components/wallet.tsx';
export { walletIconDefinition } from '../generated/definitions/wallet.ts';
