/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WatchIcon } from '../generated/components/watch.tsx';
export { watchIconDefinition } from '../generated/definitions/watch.ts';
