/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WatchFilledIcon } from '../generated/components/watch-filled.tsx';
export { watchFilledIconDefinition } from '../generated/definitions/watch-filled.ts';
