/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WatermelonFilledIcon } from '../generated/components/watermelon-filled.tsx';
export { watermelonFilledIconDefinition } from '../generated/definitions/watermelon-filled.ts';
