/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WaveRightFilledIcon } from '../generated/components/wave-right-filled.tsx';
export { waveRightFilledIconDefinition } from '../generated/definitions/wave-right-filled.ts';
