/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WaveLeftFilledIcon } from '../generated/components/wave-left-filled.tsx';
export { waveLeftFilledIconDefinition } from '../generated/definitions/wave-left-filled.ts';
