/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WealthFilledIcon } from '../generated/components/wealth-filled.tsx';
export { wealthFilledIconDefinition } from '../generated/definitions/wealth-filled.ts';
