/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Wealth1Icon } from '../generated/components/wealth-1.tsx';
export { wealth1IconDefinition } from '../generated/definitions/wealth-1.ts';
