/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WebIcon } from '../generated/components/web.tsx';
export { webIconDefinition } from '../generated/definitions/web.ts';
