/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WidgetFilledIcon } from '../generated/components/widget-filled.tsx';
export { widgetFilledIconDefinition } from '../generated/definitions/widget-filled.ts';
