/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WidgetIcon } from '../generated/components/widget.tsx';
export { widgetIconDefinition } from '../generated/definitions/widget.ts';
