/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Wifi1Icon } from '../generated/components/wifi-1.tsx';
export { wifi1IconDefinition } from '../generated/definitions/wifi-1.ts';
