/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WifiOffIcon } from '../generated/components/wifi-off.tsx';
export { wifiOffIconDefinition } from '../generated/definitions/wifi-off.ts';
