/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WifiOff1Icon } from '../generated/components/wifi-off-1.tsx';
export { wifiOff1IconDefinition } from '../generated/definitions/wifi-off-1.ts';
