/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WifiIcon } from '../generated/components/wifi.tsx';
export { wifiIconDefinition } from '../generated/definitions/wifi.ts';
