/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WindowIcon } from '../generated/components/window.tsx';
export { windowIconDefinition } from '../generated/definitions/window.ts';
