/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WindowFilledIcon } from '../generated/components/window-filled.tsx';
export { windowFilledIconDefinition } from '../generated/definitions/window-filled.ts';
