/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { Window1Icon } from '../generated/components/window-1.tsx';
export { window1IconDefinition } from '../generated/definitions/window-1.ts';
