/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkFilledIcon } from '../generated/components/work-filled.tsx';
export { workFilledIconDefinition } from '../generated/definitions/work-filled.ts';
