/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkHistoryFilledIcon } from '../generated/components/work-history-filled.tsx';
export { workHistoryFilledIconDefinition } from '../generated/definitions/work-history-filled.ts';
