/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkHistoryIcon } from '../generated/components/work-history.tsx';
export { workHistoryIconDefinition } from '../generated/definitions/work-history.ts';
