/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkIcon } from '../generated/components/work.tsx';
export { workIconDefinition } from '../generated/definitions/work.ts';
