/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkOffIcon } from '../generated/components/work-off.tsx';
export { workOffIconDefinition } from '../generated/definitions/work-off.ts';
