/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WorkOffFilledIcon } from '../generated/components/work-off-filled.tsx';
export { workOffFilledIconDefinition } from '../generated/definitions/work-off-filled.ts';
