/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { WrySmileIcon } from '../generated/components/wry-smile.tsx';
export { wrySmileIconDefinition } from '../generated/definitions/wry-smile.ts';
