/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ZoomInIcon } from '../generated/components/zoom-in.tsx';
export { zoomInIconDefinition } from '../generated/definitions/zoom-in.ts';
