/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ZoomInFilledIcon } from '../generated/components/zoom-in-filled.tsx';
export { zoomInFilledIconDefinition } from '../generated/definitions/zoom-in-filled.ts';
