/* eslint-disable */
// This file is auto-generated by packages/icons/scripts/generate-icons.mjs.
// Do not edit manually.

export { ZoomOutFilledIcon } from '../generated/components/zoom-out-filled.tsx';
export { zoomOutFilledIconDefinition } from '../generated/definitions/zoom-out-filled.ts';
